// 오둥이 하루 — 프롬프트 빌더 공용 데이터
// 모든 옵션 라벨은 한글, 프롬프트 출력은 영어로 매핑됨.

window.ODUNGI_DATA = (function () {
  // ─────────────────────────────────────────────────────────
  // 캐릭터 프리셋 (영문 설명은 이미지 생성 AI 일관성용)
  const CHARACTER_PRESETS = {
    "배추": {
      name_en: "Baechu",
      kind: "강아지",
      emoji: "🐶",
      description:
        "American Cocker Spaniel, Medium-sized 15kg dog, golden beige cream silky wavy fur, long floppy ears with flowing wavy fur, large warm gentle brown eyes, small black round nose, sweet innocent gentle expression, fluffy chest fur, warm golden tan coloring throughout",
    },
    "상추": {
      name_en: "Sangchu",
      kind: "강아지",
      emoji: "🐕",
      description:
        "Old English Sheepdog, Large and sturdy 35kg heavy-set breed, entire head and both ears MUST be 100% pure solid white without any grey markings, white chest and front legs, dark charcoal grey fur starting strictly from the shoulders and covering the back and hindquarters, very cute big round gentle puppy eyes with heterochromia (one soft brown and one soft blue, sparkling and kind expression), the tail is an entirely solid dark charcoal grey very short stubby tail with absolutely NO white color at the tip",
    },
    "열무": {
      name_en: "Yeolmu",
      kind: "강아지",
      emoji: "🦴",
      description:
        "Papillon dog, Small and dainty 5kg toy breed, brown and white coloring, very distinctive large butterfly-shaped ears with brown and white long fur, big round expressive warm brown eyes, white chest and belly, dainty elegant small frame",
    },
    "까미": {
      name_en: "Ggami",
      kind: "고양이",
      emoji: "🐱",
      description:
        "Gray tuxedo cat, dark charcoal gray body with white chest and belly, distinctive thick black mustache marking above lips, sharp piercing yellow amber eyes with intense tsundere gaze, small pink heart-shaped nose, pink heart-shaped paw pads, muscular compact body, long gray tail, grumpy exterior but secretly caring personality",
    },
    "김치": {
      name_en: "Gimchi",
      kind: "고양이",
      emoji: "🐈",
      description:
        "Scottish Fold cat, all white fluffy coat, distinctive folded flat ears pressed close to very round chubby head, sharp yellow amber eyes with perpetually grumpy stern furrowed brow expression, small pink heart-shaped nose, plump round chubby body, short stubby legs, always looks displeased and unimpressed",
    },
    "드니로": {
      name_en: "Dniro",
      kind: "사람",
      emoji: "👨",
      description:
        "Male human in Ghibli animation style, dark brown short straight hair, wearing casual everyday clothes such as hoodies or simple shirts and jeans, young adult in late 20s to early 30s, gentle kind warm face, soft warm eyes, natural relaxed confident posture",
    },
    "엘사": {
      name_en: "Elsa",
      kind: "사람",
      emoji: "👩",
      description:
        "Female human in Ghibli animation style, medium length dark brown slightly wavy hair, casual everyday style clothing such as hoodies or simple tops, young adult woman in late 20s, warm thoughtful gentle expression, soft natural features, approachable and calm appearance",
    },
    "정만": {
      name_en: "Jeongman",
      kind: "사람",
      emoji: "👩‍🦱",
      description:
        "Female human in Ghibli animation style, long dark black flowing wavy hair, distinctive round glasses, casual blue or earth-tone clothing, warm gentle smile, nature and outdoor lover vibe, thoughtful intellectual appearance, kind warm eyes behind glasses",
    },
  };
  const ANIMAL_KEYS = ["배추", "상추", "열무", "까미", "김치"];

  // ─────────────────────────────────────────────────────────
  // 한글 라벨 ➜ 영문 프롬프트 매핑 (없으면 라벨 그대로 사용)
  const pair = (ko, en) => ({ ko, en });

  // 시간대 (100+)
  const TIME_OF_DAY = [
    pair("새벽", "predawn"),
    pair("동트는 시각", "first light"),
    pair("일출", "sunrise"),
    pair("이른 아침", "early morning"),
    pair("아침", "morning"),
    pair("늦은 아침", "late morning"),
    pair("오전", "AM daylight"),
    pair("정오", "high noon"),
    pair("한낮", "midday"),
    pair("점심 시간", "lunchtime light"),
    pair("이른 오후", "early afternoon"),
    pair("오후", "afternoon"),
    pair("늦은 오후", "late afternoon"),
    pair("황금시간대", "golden hour"),
    pair("매직아워", "magic hour"),
    pair("블루아워", "blue hour"),
    pair("해질녘", "dusk"),
    pair("노을", "sunset glow"),
    pair("일몰", "sunset"),
    pair("저녁", "evening"),
    pair("이른 저녁", "early evening"),
    pair("늦은 저녁", "late evening"),
    pair("초저녁", "twilight"),
    pair("황혼", "gloaming"),
    pair("밤", "night"),
    pair("깊은 밤", "deep night"),
    pair("한밤중", "middle of the night"),
    pair("자정", "midnight"),
    pair("새벽 1시", "1 AM"),
    pair("새벽 2시", "2 AM"),
    pair("새벽 3시", "3 AM"),
    pair("새벽 4시", "4 AM"),
    pair("새벽 5시", "5 AM"),
    pair("아침 6시", "6 AM"),
    pair("아침 7시", "7 AM"),
    pair("오전 8시", "8 AM"),
    pair("오전 9시", "9 AM"),
    pair("오전 10시", "10 AM"),
    pair("오전 11시", "11 AM"),
    pair("오후 1시", "1 PM"),
    pair("오후 2시", "2 PM"),
    pair("오후 3시", "3 PM"),
    pair("오후 4시", "4 PM"),
    pair("오후 5시", "5 PM"),
    pair("오후 6시", "6 PM"),
    pair("저녁 7시", "7 PM"),
    pair("저녁 8시", "8 PM"),
    pair("밤 9시", "9 PM"),
    pair("밤 10시", "10 PM"),
    pair("밤 11시", "11 PM"),
    pair("봄 아침", "spring morning"),
    pair("봄 오후", "spring afternoon"),
    pair("여름 새벽", "summer dawn"),
    pair("여름 한낮", "summer midday"),
    pair("여름 저녁", "summer evening"),
    pair("가을 아침", "autumn morning"),
    pair("가을 오후", "autumn afternoon"),
    pair("가을 저녁", "autumn evening"),
    pair("겨울 아침", "winter morning"),
    pair("겨울 오후", "winter afternoon"),
    pair("겨울 저녁", "winter evening"),
    pair("크리스마스 이브", "christmas eve night"),
    pair("새해 자정", "new year midnight"),
    pair("정월 대보름", "full moon night"),
    pair("초승달 밤", "crescent moon night"),
    pair("보름달 밤", "full moon night"),
    pair("별이 빛나는 밤", "starry night"),
    pair("은하수 밤", "milky way night"),
    pair("유성우 밤", "meteor shower night"),
    pair("오로라 밤", "aurora night"),
    pair("폭풍 전 정적", "pre-storm stillness"),
    pair("폭풍 직후", "just after the storm"),
    pair("비 오기 직전", "moments before rain"),
    pair("비 갠 직후 아침", "morning right after rain"),
    pair("눈 내리는 새벽", "snowy dawn"),
    pair("눈 그친 저녁", "evening after snow"),
    pair("안개 낀 새벽", "foggy dawn"),
    pair("안개 낀 저녁", "foggy evening"),
    pair("흐린 정오", "overcast noon"),
    pair("개기일식 순간", "total solar eclipse"),
    pair("개기월식 순간", "total lunar eclipse"),
    pair("일출 직전", "moments before sunrise"),
    pair("일몰 직후", "moments after sunset"),
    pair("한여름 밤", "midsummer night"),
    pair("한겨울 새벽", "midwinter dawn"),
    pair("입학식 아침", "school opening morning"),
    pair("졸업식 오후", "graduation afternoon"),
    pair("주말 아침", "weekend morning"),
    pair("주말 오후", "weekend afternoon"),
    pair("월요일 출근길", "monday commute morning"),
    pair("금요일 저녁", "friday evening"),
    pair("토요일 밤", "saturday night"),
    pair("일요일 오후", "sunday afternoon"),
    pair("휴일 정오", "holiday noon"),
    pair("야시장 시간", "night market hour"),
    pair("새벽 시장", "dawn market"),
    pair("등굣길 아침", "school walk morning"),
    pair("하굣길 오후", "after-school afternoon"),
    pair("산책 시간", "walking-the-dog hour"),
    pair("티타임 오후", "afternoon tea time"),
    pair("브런치 오전", "brunch hour"),
    pair("야식 시간", "late-night snack hour"),
    pair("늦은 밤 독서", "late-night reading hour"),
  ];

  // 날씨 (100+)
  const WEATHER = [
    pair("맑음", "clear sky"),
    pair("쾌청", "bright clear weather"),
    pair("부분적으로 흐림", "partly cloudy"),
    pair("흐림", "overcast"),
    pair("뭉게구름", "fluffy cumulus clouds"),
    pair("새털구름", "wispy cirrus clouds"),
    pair("양떼구름", "altocumulus clouds"),
    pair("먹구름", "dark thunderclouds"),
    pair("비", "rain"),
    pair("이슬비", "drizzle"),
    pair("보슬비", "light drizzle"),
    pair("소나기", "sudden shower"),
    pair("장맛비", "monsoon rain"),
    pair("폭우", "heavy downpour"),
    pair("천둥번개", "thunder and lightning"),
    pair("벼락", "lightning strike"),
    pair("우박", "hail"),
    pair("진눈깨비", "sleet"),
    pair("싸락눈", "ice pellets"),
    pair("눈", "snow"),
    pair("함박눈", "big snowflakes falling"),
    pair("폭설", "blizzard"),
    pair("눈보라", "snow storm"),
    pair("가루눈", "powder snow"),
    pair("첫눈", "first snowfall"),
    pair("밤새 내린 눈", "overnight snowfall covering everything"),
    pair("바람", "windy"),
    pair("산들바람", "gentle breeze"),
    pair("강풍", "strong wind"),
    pair("돌풍", "wind gust"),
    pair("회오리바람", "whirlwind"),
    pair("태풍", "typhoon"),
    pair("허리케인", "hurricane"),
    pair("토네이도", "tornado"),
    pair("황사", "yellow dust haze"),
    pair("미세먼지", "fine dust haze"),
    pair("매연", "smog"),
    pair("안개", "fog"),
    pair("짙은 안개", "thick fog"),
    pair("물안개", "river mist"),
    pair("산안개", "mountain mist"),
    pair("이슬", "morning dew"),
    pair("서리", "frost"),
    pair("된서리", "heavy frost"),
    pair("성에", "frost on windows"),
    pair("얼음", "icy surfaces"),
    pair("결빙", "freezing surface"),
    pair("폭염", "heatwave"),
    pair("열대야", "tropical night heat"),
    pair("푹푹 찌는 더위", "sweltering humid heat"),
    pair("쨍쨍한 햇살", "blazing sunshine"),
    pair("강한 자외선", "strong UV daylight"),
    pair("아지랑이", "heat shimmer"),
    pair("미풍", "soft breeze"),
    pair("훈풍", "warm spring breeze"),
    pair("찬바람", "cold wind"),
    pair("칼바람", "biting cold wind"),
    pair("동장군", "hard winter cold"),
    pair("한파", "cold wave"),
    pair("꽃샘추위", "spring cold snap"),
    pair("늦더위", "lingering late summer heat"),
    pair("초가을 선선함", "crisp early autumn"),
    pair("쌀쌀함", "chilly air"),
    pair("포근함", "mild warm weather"),
    pair("아늑한 날씨", "cozy weather"),
    pair("비 갠 후", "after the rain"),
    pair("무지개", "rainbow"),
    pair("쌍무지개", "double rainbow"),
    pair("노을빛 구름", "sunset-lit clouds"),
    pair("핑크빛 하늘", "pink sky"),
    pair("보랏빛 하늘", "violet sky"),
    pair("주황빛 하늘", "orange sky"),
    pair("회색 하늘", "grey sky"),
    pair("푸른 하늘", "deep blue sky"),
    pair("쨍한 파란 하늘", "vivid blue sky"),
    pair("별이 보이는 맑은 밤", "clear starlit night"),
    pair("달무리", "moon halo"),
    pair("해무리", "sun halo"),
    pair("물방울 떨어지는 처마", "raindrops dripping from eaves"),
    pair("창문에 맺힌 빗방울", "raindrops on the window"),
    pair("바닥에 고인 물웅덩이", "puddles on the ground"),
    pair("젖은 도로", "wet asphalt"),
    pair("진흙탕", "muddy ground"),
    pair("눈 덮인 풍경", "snow-covered landscape"),
    pair("얼어붙은 호수", "frozen lake"),
    pair("얼음장 같은 강", "icy river"),
    pair("바람에 흔들리는 나뭇잎", "leaves rustling in the wind"),
    pair("바람에 날리는 벚꽃", "cherry blossoms blowing in wind"),
    pair("바람에 날리는 은행잎", "ginkgo leaves blowing in wind"),
    pair("바람에 날리는 단풍잎", "maple leaves blowing in wind"),
    pair("낙엽 가득한 거리", "street full of fallen leaves"),
    pair("벚꽃 흩날림", "cherry blossom petals falling"),
    pair("매화꽃 흩날림", "plum blossom petals falling"),
    pair("황금 들녘", "golden rice field"),
    pair("푸른 들녘", "green rice field"),
    pair("폭우 후 무지개", "rainbow after heavy rain"),
    pair("비 오는 야경", "rainy night cityscape"),
    pair("눈 오는 야경", "snowy night cityscape"),
    pair("새벽이슬 머금은 잔디", "dewy grass at dawn"),
    pair("아침 안개 자욱한 숲", "morning mist in the forest"),
    pair("저녁노을 구름", "sunset-streaked clouds"),
    pair("우산이 필요한 비", "umbrella weather"),
  ];

  // 배경 (500+ — 카테고리별 그룹)
  const SCENE = [
    // 도시
    pair("도심 한복판", "downtown city center"),
    pair("서울 광화문 광장", "Gwanghwamun square Seoul"),
    pair("서울 명동 거리", "Myeongdong street Seoul"),
    pair("서울 홍대 거리", "Hongdae street Seoul"),
    pair("서울 강남대로", "Gangnam boulevard Seoul"),
    pair("서울 한강 둔치", "Han river park Seoul"),
    pair("서울 남산타워 전망대", "N Seoul Tower observatory"),
    pair("서울 북촌 한옥마을", "Bukchon hanok village"),
    pair("서울 인사동 골목", "Insadong alley"),
    pair("서울 이태원 거리", "Itaewon street"),
    pair("서울 청계천", "Cheonggyecheon stream"),
    pair("서울 성수동 카페거리", "Seongsu cafe street"),
    pair("서울 익선동 한옥카페", "Ikseondong hanok cafe street"),
    pair("부산 해운대 해변", "Haeundae beach Busan"),
    pair("부산 광안리 해변", "Gwangalli beach"),
    pair("부산 감천문화마을", "Gamcheon culture village"),
    pair("부산 자갈치 시장", "Jagalchi fish market"),
    pair("제주 협재 해변", "Hyeopjae beach Jeju"),
    pair("제주 우도", "Udo island Jeju"),
    pair("제주 한라산", "Hallasan mountain"),
    pair("제주 성산일출봉", "Seongsan Ilchulbong"),
    pair("제주 올레길", "Jeju Olle trail"),
    pair("경주 황리단길", "Hwangnidan street Gyeongju"),
    pair("경주 첨성대 잔디밭", "Cheomseongdae lawn"),
    pair("전주 한옥마을", "Jeonju hanok village"),
    pair("강릉 안목 커피거리", "Anmok coffee street Gangneung"),
    pair("강릉 경포대 해변", "Gyeongpodae beach"),
    pair("속초 동명항", "Donghang port Sokcho"),
    pair("여수 밤바다", "Yeosu night sea"),
    pair("순천만 갈대밭", "Suncheon Bay reed field"),
    pair("담양 메타세쿼이아길", "Damyang metasequoia road"),
    pair("안동 하회마을", "Andong hahoe village"),
    pair("도쿄 시부야 교차로", "Shibuya crossing Tokyo"),
    pair("도쿄 신주쿠 골목", "Shinjuku alley"),
    pair("도쿄 아사쿠사 절", "Asakusa temple"),
    pair("교토 기온 거리", "Gion street Kyoto"),
    pair("오사카 도톤보리", "Dotonbori Osaka"),
    pair("홋카이도 설경 마을", "Hokkaido snowy village"),
    pair("뉴욕 타임스퀘어", "Times Square New York"),
    pair("뉴욕 센트럴파크", "Central Park"),
    pair("파리 에펠탑 광장", "Eiffel Tower plaza"),
    pair("파리 몽마르트 언덕", "Montmartre hill"),
    pair("런던 빅벤 앞", "Big Ben London"),
    pair("로마 콜로세움", "Colosseum Rome"),
    pair("베네치아 운하", "Venice canal"),
    pair("산토리니 골목", "Santorini alley"),
    pair("뉴질랜드 호빗마을", "Hobbiton style village"),
    pair("아이슬란드 빙하", "Iceland glacier"),
    // 자연
    pair("푸른 잔디 언덕", "rolling green grass hill"),
    pair("들꽃 가득한 들판", "wildflower meadow"),
    pair("유채꽃밭", "canola flower field"),
    pair("해바라기밭", "sunflower field"),
    pair("라벤더밭", "lavender field"),
    pair("튤립밭", "tulip field"),
    pair("코스모스밭", "cosmos field"),
    pair("벚꽃 가로수길", "cherry blossom tree avenue"),
    pair("벚꽃 만개한 공원", "park in full cherry bloom"),
    pair("매화나무 아래", "under a plum blossom tree"),
    pair("은행나무 가로수길", "ginkgo tree-lined road"),
    pair("단풍 가득한 산길", "mountain trail full of autumn leaves"),
    pair("소나무 숲", "pine forest"),
    pair("대나무 숲", "bamboo grove"),
    pair("자작나무 숲", "birch forest"),
    pair("울창한 활엽수림", "dense broadleaf forest"),
    pair("열대우림", "tropical rainforest"),
    pair("이끼 낀 숲", "mossy forest floor"),
    pair("계곡 옆 너럭바위", "flat rock by a creek"),
    pair("폭포 앞", "in front of a waterfall"),
    pair("호숫가", "lakeside"),
    pair("호수 위 나무 데크", "wooden dock over a lake"),
    pair("바닷가 모래사장", "sandy beach"),
    pair("바닷가 자갈밭", "pebble beach"),
    pair("바위 해안", "rocky coastline"),
    pair("등대 앞 절벽", "cliff in front of a lighthouse"),
    pair("백사장과 야자수", "white beach with palm trees"),
    pair("산호초 바다", "coral reef sea"),
    pair("심해", "deep ocean"),
    pair("강가 자갈밭", "river pebble bed"),
    pair("강변 풀밭", "grassy riverbank"),
    pair("폭포수 아래", "underneath a waterfall"),
    pair("호수 위 안개", "mist over a lake"),
    pair("산 정상", "mountain peak"),
    pair("산 능선", "mountain ridge"),
    pair("설산", "snow-capped mountain"),
    pair("화산 분화구", "volcano crater"),
    pair("협곡", "canyon"),
    pair("사막 한가운데", "in the middle of the desert"),
    pair("사막 오아시스", "desert oasis"),
    pair("모래언덕", "sand dunes"),
    pair("초원", "wide prairie"),
    pair("툰드라", "tundra landscape"),
    pair("빙하", "glacier"),
    pair("얼어붙은 호수 위", "on a frozen lake"),
    pair("바위 동굴", "rock cave"),
    pair("종유석 동굴", "stalactite cave"),
    pair("얼음 동굴", "ice cave"),
    pair("산속 옹달샘", "mountain spring"),
    pair("개울가", "by a small stream"),
    pair("이끼 낀 돌담", "mossy stone wall"),
    // 시골/전원
    pair("시골 논두렁", "rural rice paddy path"),
    pair("황금 논", "golden rice paddy"),
    pair("배추밭", "cabbage field"),
    pair("고추밭", "chili pepper field"),
    pair("사과 과수원", "apple orchard"),
    pair("감나무 마당", "yard with a persimmon tree"),
    pair("매실 농장", "plum farm"),
    pair("귤 농장", "tangerine farm"),
    pair("초가집 마당", "thatched house yard"),
    pair("기와집 마당", "tiled-roof hanok yard"),
    pair("툇마루", "hanok wooden porch"),
    pair("마당 평상", "yard wooden bench"),
    pair("우물가", "by an old well"),
    pair("장독대", "row of earthen jars"),
    pair("외양간", "old cowshed"),
    pair("닭장", "chicken coop"),
    pair("개울 위 징검다리", "stepping stones over a stream"),
    pair("시골 버스 정류장", "rural bus stop"),
    pair("시골 기차역", "small countryside train station"),
    pair("코스모스 핀 시골길", "country road with cosmos"),
    pair("벼 베기 직전 들판", "rice field just before harvest"),
    pair("허수아비 선 논", "scarecrow standing in a rice paddy"),
    pair("시골 5일장", "rural five-day market"),
    pair("산골 화전민 집", "mountain hut"),
    // 실내 — 집
    pair("아늑한 거실 소파", "cozy living room sofa"),
    pair("우드톤 거실", "warm wooden living room"),
    pair("미니멀 거실", "minimal living room"),
    pair("벽난로 앞", "in front of a fireplace"),
    pair("크리스마스 트리 옆", "next to a christmas tree"),
    pair("창가 의자", "chair by the window"),
    pair("창가 햇살 드는 자리", "sunlit window seat"),
    pair("부엌 식탁", "kitchen dining table"),
    pair("아일랜드 조리대", "kitchen island"),
    pair("아침 식사 차린 식탁", "breakfast table"),
    pair("커피 내리는 부엌", "kitchen with coffee being brewed"),
    pair("빵 굽는 오븐 앞", "in front of a baking oven"),
    pair("침실 침대 위", "on a bedroom bed"),
    pair("러그 깔린 바닥", "rug on the floor"),
    pair("이불 위", "on a duvet"),
    pair("창가 책상", "desk by the window"),
    pair("책장 가득한 서재", "study room full of bookshelves"),
    pair("작은 작업실", "small home studio"),
    pair("욕실 욕조", "bathroom bathtub"),
    pair("샤워 부스 앞", "in front of a shower"),
    pair("드레스룸", "walk-in closet"),
    pair("발코니", "balcony"),
    pair("작은 베란다 정원", "small balcony garden"),
    pair("옥상 정원", "rooftop garden"),
    pair("옥탑방", "rooftop room"),
    pair("다락방", "attic room"),
    pair("지하 창고", "basement storage room"),
    pair("현관", "front entrance hallway"),
    pair("신발장 앞", "in front of the shoe cabinet"),
    pair("거실 카펫 위 캠핑", "indoor camping on the living room rug"),
    // 카페/식당
    pair("따뜻한 우드톤 카페", "warm wooden cafe"),
    pair("화이트톤 미니멀 카페", "white minimal cafe"),
    pair("브런치 카페 야외 테이블", "brunch cafe outdoor table"),
    pair("로스터리 카페", "specialty roastery cafe"),
    pair("골목 작은 카페", "small alley cafe"),
    pair("한옥 카페", "hanok-style cafe"),
    pair("북카페", "book cafe"),
    pair("디저트 카페", "dessert cafe"),
    pair("도넛 가게", "donut shop"),
    pair("베이커리", "bakery"),
    pair("동네 빵집 앞", "in front of a neighborhood bakery"),
    pair("아이스크림 가게", "ice cream parlor"),
    pair("핫초코 가게", "hot chocolate shop"),
    pair("뱅쇼 끓는 카페", "cafe with mulled wine simmering"),
    pair("이자카야", "japanese izakaya"),
    pair("선술집", "korean pojangmacha"),
    pair("포장마차", "street food cart"),
    pair("국숫집", "noodle restaurant"),
    pair("분식집", "korean snack shop"),
    pair("떡볶이 가게", "tteokbokki shop"),
    pair("치킨집 테이블", "fried chicken restaurant table"),
    pair("삼겹살집", "korean BBQ restaurant"),
    pair("스시 카운터", "sushi counter"),
    pair("라멘집", "ramen shop"),
    pair("이탈리안 레스토랑", "italian restaurant"),
    pair("프렌치 비스트로", "french bistro"),
    pair("파인다이닝", "fine dining restaurant"),
    pair("푸드트럭 앞", "in front of a food truck"),
    pair("야시장 노점", "night market street stall"),
    pair("재래시장 골목", "traditional market alley"),
    // 학교/일터
    pair("초등학교 운동장", "elementary school playground"),
    pair("중학교 복도", "middle school hallway"),
    pair("고등학교 교실", "high school classroom"),
    pair("대학교 캠퍼스 잔디밭", "university campus lawn"),
    pair("대학교 도서관", "university library"),
    pair("학원 강의실", "private academy classroom"),
    pair("작은 사무실", "small office"),
    pair("코워킹 스페이스", "coworking space"),
    pair("회의실", "meeting room"),
    pair("회사 옥상 휴게실", "office rooftop lounge"),
    pair("회사 탕비실", "office pantry"),
    pair("창고형 작업실", "warehouse style studio"),
    pair("화가의 아틀리에", "painter's atelier"),
    pair("도예 공방", "ceramic pottery studio"),
    pair("목공방", "woodworking shop"),
    pair("미용실", "hair salon"),
    pair("플라워샵", "flower shop"),
    pair("동네 책방", "neighborhood bookshop"),
    pair("문구점", "stationery shop"),
    pair("음반 가게", "record store"),
    pair("악기 가게", "musical instrument store"),
    pair("필름 사진관", "film photo studio"),
    pair("스튜디오 촬영장", "photography studio"),
    pair("영화관 객석", "movie theater seat"),
    pair("작은 극장", "small theater"),
    pair("미술관 전시실", "art museum gallery"),
    pair("박물관 복도", "museum hallway"),
    // 교통
    pair("기차 창가 좌석", "train window seat"),
    pair("기차 식당칸", "train dining car"),
    pair("KTX 좌석", "KTX seat"),
    pair("시골 무궁화호 안", "saemaul train interior"),
    pair("지하철 안", "subway car"),
    pair("지하철 플랫폼", "subway platform"),
    pair("버스 안", "city bus interior"),
    pair("버스 정류장", "bus stop"),
    pair("택시 뒷좌석", "taxi back seat"),
    pair("자동차 운전석", "car driver seat"),
    pair("자동차 조수석", "car passenger seat"),
    pair("캠핑카 안", "RV camper interior"),
    pair("비행기 창가 자리", "airplane window seat"),
    pair("비행기 화물칸 펫박스", "airplane pet box"),
    pair("공항 게이트", "airport gate"),
    pair("공항 활주로", "airport runway"),
    pair("기차역 대합실", "train station waiting room"),
    pair("자전거 뒷자리", "back of a bicycle"),
    pair("스쿠터 발판", "scooter footboard"),
    pair("페리 갑판", "ferry deck"),
    pair("요트 갑판", "yacht deck"),
    pair("열기구 바구니", "hot air balloon basket"),
    pair("케이블카 안", "cable car interior"),
    pair("자전거 도로", "bike lane"),
    pair("산악자전거 트레일", "mountain bike trail"),
    // 야외 활동
    pair("캠핑장 텐트 앞", "campsite in front of a tent"),
    pair("글램핑 사이트", "glamping site"),
    pair("캠핑 모닥불 앞", "in front of a campfire"),
    pair("바비큐 그릴 옆", "next to a BBQ grill"),
    pair("강가 캠핑", "riverside camping"),
    pair("산속 캠핑", "mountain camping"),
    pair("계곡 물놀이", "valley water play"),
    pair("해변 파라솔 아래", "under a beach parasol"),
    pair("스노클링", "snorkeling underwater"),
    pair("서핑 보드 위", "on a surfboard"),
    pair("패들보드 위", "on a paddle board"),
    pair("카약", "in a kayak"),
    pair("등산로", "hiking trail"),
    pair("등산로 정상 표지석", "mountain peak marker"),
    pair("나무다리", "wooden bridge"),
    pair("출렁다리", "suspension bridge"),
    pair("자전거 한강길", "Han river bike path"),
    pair("스케이트장", "ice skating rink"),
    pair("스키 슬로프", "ski slope"),
    pair("스노보드 슬로프", "snowboard slope"),
    pair("눈썰매장", "snow sled hill"),
    pair("아이스링크 한복판", "center of an ice rink"),
    pair("놀이공원", "amusement park"),
    pair("회전목마 앞", "in front of a carousel"),
    pair("관람차 안", "inside a ferris wheel"),
    pair("롤러코스터 트랙", "roller coaster track"),
    pair("워터파크 슬라이드", "water park slide"),
    pair("동물원 사파리", "zoo safari area"),
    pair("수족관 터널", "aquarium tunnel"),
    pair("식물원 온실", "botanical garden greenhouse"),
    pair("국립공원 산책로", "national park trail"),
    pair("골프장 페어웨이", "golf course fairway"),
    pair("축구 경기장", "soccer stadium"),
    pair("야구장 외야석", "baseball outfield seats"),
    pair("테니스 코트", "tennis court"),
    pair("농구 코트", "basketball court"),
    pair("배드민턴장", "badminton court"),
    pair("수영장 풀사이드", "swimming pool side"),
    pair("실내 클라이밍장", "indoor climbing gym"),
    pair("승마장", "horse riding arena"),
    pair("양궁장", "archery range"),
    // 판타지/스타일라이즈드
    pair("환상의 꽃밭", "fantasy flower meadow"),
    pair("반딧불 가득한 숲", "forest full of fireflies"),
    pair("거대 버섯 숲", "giant mushroom forest"),
    pair("동화 속 마을", "fairytale village"),
    pair("마법의 도서관", "magical library"),
    pair("물 위에 떠 있는 섬", "floating island over water"),
    pair("구름 위 정원", "garden above the clouds"),
    pair("별 가득한 밤하늘 아래", "under a star-filled night sky"),
    pair("은하수 아래 들판", "field under the milky way"),
    pair("우주 정거장", "space station interior"),
    pair("달 표면", "moon surface"),
    pair("화성 표면", "mars surface"),
    pair("외계 행성", "alien planet"),
    pair("수중 도시", "underwater city"),
    pair("얼음 궁전", "ice palace"),
    pair("거대한 도서탑", "giant tower library"),
    pair("이세계 시장", "isekai market street"),
    pair("판타지 성", "fantasy castle"),
    pair("드래곤 둥지", "dragon nest"),
    pair("정령의 숲", "spirit forest"),
    pair("이끼 정령 호수", "moss spirit lake"),
    pair("거대 고래가 헤엄치는 하늘", "sky with giant whales swimming"),
    pair("종이 접기 마을", "origami paper village"),
    pair("거대한 책상 위", "on top of a giant desk"),
    pair("거대한 케이크 위", "on top of a giant cake"),
    pair("도서관 책탑 사이", "between towers of stacked books"),
    pair("뜨개질 같은 풍경", "knitted yarn landscape"),
    pair("종이 콜라주 풍경", "paper collage landscape"),
    pair("크레용으로 그린 마을", "crayon drawn village"),
    pair("픽셀 아트 도시", "pixel art city"),
    pair("미니어처 정원", "miniature garden"),
    pair("디오라마 박스", "diorama box"),
    pair("스노우볼 안", "inside a snow globe"),
    pair("유리병 속 풍경", "landscape inside a glass bottle"),
    pair("거대한 컵 안 카페", "cafe inside a giant cup"),
    pair("이불 요새", "blanket fort"),
    pair("쿠션 더미 위", "on top of a pile of cushions"),
    pair("종이 비행기 가득한 하늘", "sky full of paper planes"),
    pair("열기구 가득한 하늘", "sky full of hot air balloons"),
    pair("등불 가득한 강", "river full of paper lanterns"),
    pair("풍선 가득한 광장", "plaza full of balloons"),
    pair("거품 가득한 욕조", "bubble-filled bathtub"),
    pair("물풍선 가득한 마당", "yard full of water balloons"),
    pair("낙엽 풀장", "pile of fallen leaves"),
    pair("밀가루 폭발한 부엌", "kitchen exploded with flour"),
    pair("케이크 부스러기 가득한 식탁", "table covered in cake crumbs"),
    pair("선물 상자 더미", "pile of gift boxes"),
    pair("크리스마스 양말 옆 벽난로", "fireplace with christmas stockings"),
    pair("할로윈 호박 정원", "halloween pumpkin patch"),
    pair("폭죽 터지는 하늘", "fireworks in the sky"),
    pair("불꽃놀이 강변", "riverside fireworks"),
    pair("일루미네이션 거리", "illumination street"),
    pair("거대한 LED 광장", "giant LED billboard plaza"),
    pair("네온사인 골목", "neon sign alley"),
    pair("사이버펑크 거리", "cyberpunk street"),
    pair("미래도시 옥상", "futuristic city rooftop"),
    pair("스팀펑크 항구", "steampunk harbor"),
    pair("빈티지 70년대 거리", "vintage 70s street"),
    pair("80년대 신스웨이브 풍경", "80s synthwave landscape"),
    pair("90년대 도쿄 골목", "90s Tokyo alley"),
    pair("개항기 항구", "old harbor town"),
    pair("조선시대 저잣거리", "joseon era market street"),
    pair("고려시대 궁궐", "goryeo palace"),
    pair("일제강점기 학교", "early 20th century korean school"),
    pair("60년대 다방", "1960s korean dabang"),
    pair("80년대 만화방", "1980s comic book rental shop"),
    pair("90년대 오락실", "1990s arcade"),
    pair("PC방", "korean PC bang"),
    pair("노래방", "korean karaoke room"),
    pair("동전 노래방", "coin karaoke booth"),
    pair("사진관 인생네컷 부스", "korean photo booth"),
    pair("코인 빨래방", "coin laundromat"),
    pair("24시간 편의점", "24-hour convenience store"),
    pair("늦은 밤 편의점 앞 테이블", "late night convenience store outdoor table"),
    pair("심야식당", "midnight diner"),
    pair("심야 영화관", "late-night movie theater"),
    pair("24시 해장국집", "24-hour haejangguk restaurant"),
    pair("새벽 시장 어묵 가게", "early morning fishcake stall"),
    pair("호텔 로비", "hotel lobby"),
    pair("호텔 방", "hotel room"),
    pair("스파 사우나", "spa sauna"),
    pair("찜질방", "korean jjimjilbang"),
    pair("목욕탕", "korean public bathhouse"),
    pair("동네 미용실", "neighborhood beauty salon"),
    pair("동네 세탁소", "neighborhood dry cleaners"),
    pair("동네 철물점", "neighborhood hardware store"),
    pair("동네 떡집", "neighborhood rice cake shop"),
    pair("우체국 앞", "in front of a post office"),
    pair("동사무소", "neighborhood community center"),
    pair("도서관 열람실", "library reading room"),
    pair("도서관 어린이 코너", "library children's corner"),
    pair("공원 벤치", "park bench"),
    pair("동네 놀이터", "neighborhood playground"),
    pair("그네 앞", "in front of a swing"),
    pair("미끄럼틀 위", "on top of a slide"),
    pair("시소 위", "on a seesaw"),
    pair("정자 안", "inside a traditional pavilion"),
    pair("정자 아래 그늘", "in the shade of a pavilion"),
    pair("산책로 벤치", "trail bench"),
    pair("강아지 운동장", "dog park"),
    pair("강아지 카페", "dog cafe"),
    pair("고양이 카페", "cat cafe"),
    pair("애견 미용실", "pet grooming salon"),
    pair("동물병원 대기실", "vet clinic waiting room"),
    pair("동물병원 진료실", "vet examination room"),
    pair("펫샵 진열대", "pet shop shelf"),
    pair("강아지 호텔 객실", "pet hotel room"),
    pair("강아지 유치원", "doggy daycare"),
    pair("강아지 수영장", "dog swimming pool"),
    pair("야외 도그런", "outdoor dog run"),
    // 추가 일상
    pair("동네 산책길", "neighborhood walking path"),
    pair("아파트 단지 놀이터", "apartment complex playground"),
    pair("아파트 단지 정원", "apartment complex garden"),
    pair("주차장", "parking lot"),
    pair("지하주차장", "underground parking lot"),
    pair("엘리베이터 안", "inside an elevator"),
    pair("계단 층계참", "stairwell landing"),
    pair("옥상 빨래줄", "rooftop laundry line"),
    pair("이불 널어둔 베란다", "balcony with hanging laundry"),
    pair("창틀에 화분", "window sill with potted plants"),
    pair("실내 정원", "indoor garden"),
    pair("화분 가득한 거실", "living room full of houseplants"),
    pair("난로 위 주전자", "kettle on a stove"),
    pair("벽시계 아래", "below a wall clock"),
    pair("커다란 거울 앞", "in front of a large mirror"),
    pair("창문에 비친 모습", "reflection on a window"),
    pair("물웅덩이에 비친 풍경", "reflection in a puddle"),
    pair("자동차 백미러", "car rearview mirror reflection"),
    pair("열차 차창 너머", "view through a train window"),
    pair("비행기 창 너머 구름", "clouds outside an airplane window"),
    pair("배 창문 너머 바다", "sea outside a ship porthole"),
    pair("터널 입구", "tunnel entrance"),
    pair("터널 안 가로등", "tunnel interior lights"),
    pair("골목 막다른 길", "alley dead end"),
    pair("좁은 골목길", "narrow alley"),
    pair("벽 가득 그래피티 골목", "graffiti-filled alley"),
    pair("벽화 마을 골목", "mural village alley"),
    pair("계단식 골목", "stepped alley"),
    pair("언덕 위 동네", "hilltop neighborhood"),
    pair("바다 보이는 언덕", "hill with a sea view"),
    pair("야경 보이는 옥상", "rooftop with a night cityscape view"),
  ];

  // 카메라 뷰
  const CAMERA = [
    pair("투시뷰", "perspective view"),
    pair("미디엄뷰", "medium shot"),
    pair("전신뷰", "full body shot"),
    pair("측면뷰", "side profile view"),
    pair("정면뷰", "front view"),
    pair("후면뷰", "back view"),
    pair("로우앵글뷰", "low angle view"),
    pair("클로즈업뷰", "close-up shot"),
    pair("익스트림 클로즈업", "extreme close-up"),
    pair("와이드뷰", "wide angle shot"),
    pair("버드아이뷰", "bird's eye view"),
    pair("아이소메트릭뷰", "isometric view"),
    pair("3/4 뷰", "three-quarter view"),
    pair("탑다운뷰", "top down view"),
    pair("드론샷", "drone shot"),
    pair("어깨너머 샷", "over-the-shoulder shot"),
    pair("더치 앵글", "dutch angle"),
    pair("매크로 샷", "macro shot"),
  ];

  // 광원
  const LIGHTING = [
    pair("햇빛", "natural sunlight"),
    pair("아침 햇살", "morning sunlight"),
    pair("황금빛 햇살", "golden hour sunlight"),
    pair("창문 통과 햇살", "sunlight through a window"),
    pair("나무 사이 햇살", "dappled sunlight through trees"),
    pair("달빛", "moonlight"),
    pair("별빛", "starlight"),
    pair("불빛", "firelight"),
    pair("모닥불 빛", "campfire light"),
    pair("벽난로 빛", "fireplace glow"),
    pair("촛불", "candlelight"),
    pair("랜턴", "lantern light"),
    pair("종이등 빛", "paper lantern light"),
    pair("전등", "incandescent bulb"),
    pair("형광등", "fluorescent light"),
    pair("백열등", "warm tungsten light"),
    pair("LED 조명", "LED lighting"),
    pair("네온사인", "neon signs"),
    pair("크리스마스 전구", "christmas string lights"),
    pair("스튜디오 조명", "studio softbox lighting"),
    pair("림 라이트", "rim lighting"),
    pair("백라이트", "backlight"),
    pair("사이드 라이트", "side lighting"),
    pair("실루엣 라이트", "silhouette lighting"),
    pair("스포트라이트", "spotlight"),
    pair("프로젝터 빛", "projector light"),
    pair("화면 불빛", "screen glow"),
    pair("반딧불빛", "firefly glow"),
    pair("바이오 루미네선스", "bioluminescent glow"),
  ];

  // 화풍
  const STYLE = [
    pair("유화", "oil painting"),
    pair("수채화", "watercolor painting"),
    pair("색연필화", "colored pencil drawing"),
    pair("크레파스화", "crayon drawing"),
    pair("펜화", "pen and ink drawing"),
    pair("연필화", "pencil sketch"),
    pair("목탄화", "charcoal drawing"),
    pair("수묵화", "ink wash painting"),
    pair("동양화", "traditional korean painting"),
    pair("민화", "korean minhwa folk painting"),
    pair("아크릴화", "acrylic painting"),
    pair("파스텔화", "soft pastel painting"),
    pair("과슈화", "gouache painting"),
    pair("디지털 페인팅", "digital painting"),
    pair("픽셀 아트", "pixel art"),
    pair("벡터 일러스트", "vector flat illustration"),
    pair("3D 렌더", "3D rendered illustration"),
    pair("클레이메이션", "claymation style"),
    pair("종이접기 스타일", "origami paper craft style"),
    pair("종이콜라주", "paper collage style"),
    pair("자수 스타일", "embroidery style"),
    pair("뜨개질 스타일", "knitted yarn style"),
    pair("펠트 인형 스타일", "felt doll style"),
    pair("지브리 스타일", "studio ghibli style"),
    pair("디즈니 스타일", "disney animation style"),
    pair("픽사 스타일", "pixar 3D style"),
    pair("애니메이션 셀화", "anime cel animation style"),
    pair("만화책 스타일", "comic book style"),
    pair("동화책 일러스트", "children's storybook illustration"),
    pair("그래픽 노블", "graphic novel style"),
    pair("스토리보드 스케치", "storyboard sketch"),
    pair("포토리얼리스틱", "photorealistic"),
    pair("하이퍼리얼리즘", "hyperrealism"),
    pair("필름 사진", "film photography"),
    pair("폴라로이드", "polaroid photo"),
    pair("빈티지 사진", "vintage photograph"),
    pair("로모그래피", "lomography"),
  ];

  // 기법
  const TECHNIQUE = [
    pair("붓 터치", "brush stroke texture"),
    pair("나이프 터치", "palette knife texture"),
    pair("스펀지 텍스처", "sponge texture"),
    pair("손가락 페인팅", "finger painting texture"),
    pair("세밀화", "highly detailed rendering"),
    pair("라인 드로잉", "line drawing"),
    pair("물 번짐", "wet-on-wet bleeding"),
    pair("물감 흩뿌리기", "paint splatter"),
    pair("임파스토", "impasto thick paint"),
    pair("마띠에르", "textured matiere"),
    pair("색 쌓기", "layered color glazing"),
    pair("입체감 강조", "strong sense of depth"),
    pair("투명한 표현", "transparent translucent rendering"),
    pair("여백의 미", "generous negative space"),
    pair("3가지 색만 사용", "limited 3-color palette"),
    pair("낮은 채도", "muted desaturated tones"),
    pair("높은 채도", "highly saturated colors"),
    pair("따뜻한 톤", "warm color palette"),
    pair("차가운 톤", "cool color palette"),
    pair("모노톤", "monochrome palette"),
    pair("세피아톤", "sepia tone"),
    pair("그레인 텍스처", "film grain texture"),
    pair("종이 텍스처", "paper grain texture"),
    pair("캔버스 텍스처", "canvas texture"),
    pair("부드러운 그라데이션", "soft gradient blending"),
    pair("플랫 컬러", "flat color blocking"),
    pair("크로스해칭", "cross-hatching shading"),
    pair("점묘법", "pointillism"),
    pair("스텐실", "stencil style"),
    pair("실루엣 강조", "strong silhouette emphasis"),
    pair("강한 명암 대비", "high chiaroscuro contrast"),
    pair("부드러운 명암", "soft gentle shading"),
    pair("얕은 피사계심도", "shallow depth of field"),
    pair("보케 배경", "bokeh background"),
    pair("렌즈 플레어", "lens flare"),
    pair("긴 노출", "long exposure motion"),
    pair("틸트시프트", "tilt-shift miniature"),
  ];

  // 비율
  const RATIO = [
    pair("1:1", "1:1 square"),
    pair("16:9", "16:9 widescreen"),
    pair("9:16", "9:16 vertical"),
    pair("4:3", "4:3 standard"),
    pair("3:4", "3:4 portrait"),
    pair("3:2", "3:2 photo"),
    pair("2:3", "2:3 vertical photo"),
    pair("2:1", "2:1 cinematic"),
    pair("5:4", "5:4 medium format"),
    pair("7:5", "7:5 print"),
  ];

  // ─────────────────────────────────────────────────────────
  // 음악 — 장르 (100+)
  const GENRE = [
    pair("팝", "pop"),
    pair("락", "rock"),
    pair("하드락", "hard rock"),
    pair("소프트락", "soft rock"),
    pair("얼터너티브 락", "alternative rock"),
    pair("인디 락", "indie rock"),
    pair("펑크 락", "punk rock"),
    pair("포스트 펑크", "post punk"),
    pair("메탈", "heavy metal"),
    pair("그런지", "grunge"),
    pair("이모", "emo"),
    pair("힙합", "hip hop"),
    pair("붐뱁", "boom bap"),
    pair("트랩", "trap"),
    pair("로파이 힙합", "lofi hip hop"),
    pair("R&B", "R&B"),
    pair("네오 소울", "neo soul"),
    pair("소울", "soul"),
    pair("펑크", "funk"),
    pair("디스코", "disco"),
    pair("재즈", "jazz"),
    pair("스무스 재즈", "smooth jazz"),
    pair("스윙 재즈", "swing jazz"),
    pair("보사노바", "bossa nova"),
    pair("라틴", "latin"),
    pair("살사", "salsa"),
    pair("탱고", "tango"),
    pair("쿠바 음악", "cuban music"),
    pair("플라멩코", "flamenco"),
    pair("레게", "reggae"),
    pair("스카", "ska"),
    pair("덥", "dub"),
    pair("일렉트로닉", "electronic"),
    pair("EDM", "EDM"),
    pair("하우스", "house"),
    pair("딥 하우스", "deep house"),
    pair("테크노", "techno"),
    pair("트랜스", "trance"),
    pair("덥스텝", "dubstep"),
    pair("드럼앤베이스", "drum and bass"),
    pair("앰비언트", "ambient"),
    pair("칠아웃", "chillout"),
    pair("로파이", "lofi"),
    pair("신스웨이브", "synthwave"),
    pair("뉴웨이브", "new wave"),
    pair("시티팝", "city pop"),
    pair("재즈 퓨전", "jazz fusion"),
    pair("클래식", "classical orchestral"),
    pair("실내악", "chamber music"),
    pair("피아노 솔로", "solo piano"),
    pair("바이올린 솔로", "solo violin"),
    pair("첼로 솔로", "solo cello"),
    pair("기타 솔로", "acoustic guitar solo"),
    pair("어쿠스틱", "acoustic"),
    pair("포크", "folk"),
    pair("인디 포크", "indie folk"),
    pair("컨트리", "country"),
    pair("블루스", "blues"),
    pair("가스펠", "gospel"),
    pair("재즈 보컬", "vocal jazz"),
    pair("스탠다드", "jazz standard"),
    pair("샹송", "french chanson"),
    pair("이탈리아 칸초네", "italian canzone"),
    pair("월드뮤직", "world music"),
    pair("켈틱", "celtic"),
    pair("아일랜드 포크", "irish folk"),
    pair("스코틀랜드 민속", "scottish folk"),
    pair("아프리카 드럼", "african drum"),
    pair("인도 라가", "indian raga"),
    pair("중동 음악", "middle eastern music"),
    pair("국악", "korean traditional gugak"),
    pair("판소리", "pansori"),
    pair("사물놀이", "samulnori"),
    pair("일본 전통음악", "japanese traditional music"),
    pair("중국 전통음악", "chinese traditional music"),
    pair("뉴에이지", "new age"),
    pair("필름 스코어", "film score"),
    pair("게임 OST", "video game soundtrack"),
    pair("애니메이션 OST", "anime soundtrack"),
    pair("뮤지컬", "musical theater"),
    pair("디즈니 스타일", "disney musical style"),
    pair("크리스마스 캐롤", "christmas carol"),
    pair("자장가", "lullaby"),
    pair("동요", "children's song"),
    pair("K-팝", "K-pop"),
    pair("K-발라드", "korean ballad"),
    pair("트로트", "trot"),
    pair("J-팝", "J-pop"),
    pair("시티팝 일본", "japanese city pop"),
    pair("애시드 재즈", "acid jazz"),
    pair("프로그레시브 락", "progressive rock"),
    pair("싸이키델릭", "psychedelic"),
    pair("슈게이즈", "shoegaze"),
    pair("드림팝", "dream pop"),
    pair("베드룸 팝", "bedroom pop"),
    pair("힙합 재즈", "jazz hip hop"),
    pair("부기우기", "boogie woogie"),
    pair("랙타임", "ragtime"),
    pair("자이브", "jive"),
    pair("로커빌리", "rockabilly"),
    pair("서프 락", "surf rock"),
    pair("스카 펑크", "ska punk"),
  ];

  // 분위기 (100+)
  const MOOD = [
    pair("행복한", "happy"),
    pair("기쁜", "joyful"),
    pair("들뜬", "excited"),
    pair("신나는", "upbeat energetic"),
    pair("경쾌한", "cheerful"),
    pair("발랄한", "bubbly"),
    pair("귀여운", "cute"),
    pair("사랑스러운", "lovely"),
    pair("로맨틱한", "romantic"),
    pair("달콤한", "sweet"),
    pair("두근거리는", "fluttering"),
    pair("애틋한", "tender"),
    pair("따뜻한", "warm"),
    pair("포근한", "cozy"),
    pair("아늑한", "snug"),
    pair("편안한", "relaxed"),
    pair("느긋한", "laid-back"),
    pair("평화로운", "peaceful"),
    pair("고요한", "serene"),
    pair("차분한", "calm"),
    pair("잔잔한", "gentle and mellow"),
    pair("나른한", "languid"),
    pair("졸린", "drowsy"),
    pair("몽환적인", "dreamy"),
    pair("환상적인", "fantastical"),
    pair("신비로운", "mysterious"),
    pair("마법 같은", "magical"),
    pair("동화 같은", "fairytale-like"),
    pair("향수 어린", "nostalgic"),
    pair("아련한", "wistful"),
    pair("그리운", "longing"),
    pair("쓸쓸한", "lonely"),
    pair("외로운", "lonesome"),
    pair("슬픈", "sad"),
    pair("애잔한", "melancholic"),
    pair("우울한", "blue"),
    pair("처량한", "forlorn"),
    pair("비통한", "sorrowful"),
    pair("절절한", "heart-wrenching"),
    pair("희망찬", "hopeful"),
    pair("벅찬", "uplifting"),
    pair("감동적인", "moving"),
    pair("위로가 되는", "comforting"),
    pair("따스한 위로", "soothing"),
    pair("응원하는", "encouraging"),
    pair("씩씩한", "brave"),
    pair("당당한", "confident"),
    pair("도전적인", "challenging"),
    pair("열정적인", "passionate"),
    pair("뜨거운", "fiery"),
    pair("강렬한", "intense"),
    pair("웅장한", "epic majestic"),
    pair("거대한", "grand"),
    pair("드라마틱한", "dramatic"),
    pair("긴장감 있는", "suspenseful"),
    pair("스릴 있는", "thrilling"),
    pair("어두운", "dark"),
    pair("음산한", "eerie"),
    pair("으스스한", "spooky"),
    pair("기괴한", "uncanny"),
    pair("불안한", "uneasy"),
    pair("초조한", "anxious"),
    pair("화난", "angry"),
    pair("격앙된", "fierce"),
    pair("반항적인", "rebellious"),
    pair("차가운", "cold"),
    pair("쿨한", "cool"),
    pair("도시적인", "urban"),
    pair("세련된", "sophisticated"),
    pair("우아한", "elegant"),
    pair("고상한", "graceful"),
    pair("기품 있는", "dignified"),
    pair("장난기 있는", "playful"),
    pair("천진난만한", "innocent"),
    pair("순수한", "pure"),
    pair("개구쟁이 같은", "mischievous"),
    pair("우스꽝스러운", "goofy"),
    pair("코믹한", "comical"),
    pair("재미있는", "fun"),
    pair("기분 좋은", "feel-good"),
    pair("산뜻한", "refreshing"),
    pair("청량한", "crisp"),
    pair("청순한", "wholesome"),
    pair("순박한", "humble"),
    pair("정겨운", "heartwarming"),
    pair("쓸데없이 진지한", "absurdly serious"),
    pair("진중한", "thoughtful"),
    pair("사색적인", "contemplative"),
    pair("철학적인", "philosophical"),
    pair("명상적인", "meditative"),
    pair("영적인", "spiritual"),
    pair("성스러운", "sacred"),
    pair("경건한", "reverent"),
    pair("축제 같은", "festive"),
    pair("파티 분위기", "party vibe"),
    pair("여름밤 같은", "summer night feel"),
    pair("크리스마스 같은", "christmasy"),
    pair("새해 같은", "new year feel"),
    pair("가을밤 같은", "autumn night feel"),
    pair("봄날 같은", "spring day feel"),
    pair("겨울 아침 같은", "winter morning feel"),
    pair("바다 같은", "ocean-like vast"),
    pair("산 같은", "mountain-like grounded"),
  ];

  // 보컬
  const VOCAL = [
    pair("남성", "male vocalist"),
    pair("여성", "female vocalist"),
    pair("혼성", "mixed gender vocals"),
    pair("듀엣", "duet"),
    pair("그룹 합창", "group choir"),
    pair("가창력 있는", "powerful vocal performance"),
    pair("멜로디 라인 강조", "strong melodic line"),
    pair("저음", "low register baritone"),
    pair("고음", "high register vocals"),
    pair("허스키", "husky voice"),
    pair("부드러운 음색", "soft warm tone"),
    pair("맑은 음색", "clear tone"),
    pair("거친 음색", "raspy tone"),
    pair("속삭임", "whispered vocals"),
    pair("팔세토", "falsetto"),
    pair("스캣", "scat singing"),
    pair("랩", "rap"),
    pair("스포큰 워드", "spoken word"),
    pair("아카펠라", "a cappella"),
    pair("인스트루멘탈", "instrumental no vocals"),
  ];

  // 코러스
  const CHORUS = [
    pair("남성 영어 코러스", "male english background chorus"),
    pair("여성 영어 코러스", "female english background chorus"),
    pair("혼성 영어 코러스", "mixed english background chorus"),
    pair("코러스 없음", "no background chorus"),
  ];

  // 가사 언어
  const LYRIC_LANG = [
    pair("한글 가사", "korean lyrics"),
    pair("영문 가사", "english lyrics"),
    pair("혼합 (한영)", "mixed korean and english lyrics"),
    pair("가사 없음", "no lyrics, instrumental"),
  ];

  // ─────────────────────────────────────────────────────────
  // 탈무드 카테고리 × 스토리 (각 100개 — 시드+조합 생성)
  // 카테고리 ➜ 영문 + 시드 스토리들
  const TALMUD_CATEGORIES = {
    "지혜": {
      en: "wisdom",
      seeds: [
        "현명한 자는 듣고 어리석은 자는 말한다",
        "두 손에 떡을 쥐려다 둘 다 떨어뜨린다",
        "보이는 것이 전부가 아니다",
        "묻는 것이 잠시의 부끄러움, 모르는 것이 평생의 부끄러움",
        "지혜는 강요할 수 없고 스스로 깨달아야 한다",
        "현자에게는 모든 사람이 스승이다",
        "지식은 짐이 아니고 깃털이다",
        "어둠 속에서도 길은 있다",
        "작은 등불이 큰 어둠을 밝힌다",
        "오래 보아야 보이는 것이 있다",
      ],
    },
    "우정": {
      en: "friendship",
      seeds: [
        "친구는 거울이다",
        "함께 웃을 친구보다 함께 울 친구가 더 귀하다",
        "오래된 친구가 새 친구보다 따뜻하다",
        "친구의 결점을 덮어주는 것이 우정이다",
        "친구를 시험하지 말고 믿어라",
        "한 친구가 천 명의 적보다 강하다",
        "친구의 그림자도 함께 걷는다",
        "비밀을 지키는 친구가 진짜 친구다",
        "친구는 받는 자가 아니라 주는 자다",
        "거리가 멀어도 마음이 가까우면 친구다",
      ],
    },
    "정직": {
      en: "honesty",
      seeds: [
        "거짓말은 다리가 짧다",
        "한 번의 거짓이 백 번의 진실을 가린다",
        "정직한 자는 베개를 베고 잠든다",
        "남을 속이는 자는 결국 자신을 속인다",
        "진실은 무겁지만 가볍게 만드는 것은 거짓이다",
        "진심은 시간이 증명한다",
        "약속은 종이가 아니라 마음에 적는 것",
        "정직은 가장 큰 자본이다",
        "거짓의 성은 무너지기 마련",
        "진실은 가난해도 부끄럽지 않다",
      ],
    },
    "인내": {
      en: "patience",
      seeds: [
        "기다리는 자에게 길이 열린다",
        "참는 자가 이긴다",
        "조급함은 후회의 어머니",
        "한 번 더 참으면 다른 길이 보인다",
        "씨앗은 흙 속에서 시간을 견딘다",
        "강물은 서두르지 않고 멀리 간다",
        "참는 것은 약함이 아니라 큰 힘",
        "오늘의 인내가 내일의 기쁨이 된다",
        "분노가 입을 떠나기 전 셋을 세라",
        "기다림에도 연습이 필요하다",
      ],
    },
    "감사": {
      en: "gratitude",
      seeds: [
        "가진 것을 헤아리는 자가 부자다",
        "감사는 작게 시작해서 크게 자란다",
        "받은 것을 잊지 않는 것이 예의",
        "감사할 일이 없을 때 감사하라",
        "한 잔의 물도 감사하면 술이 된다",
        "오늘 하루도 선물이다",
        "가족이 곁에 있는 것이 큰 복",
        "건강한 발걸음 자체가 감사다",
        "감사는 행복을 부르는 주문",
        "잃은 뒤에 알면 늦다",
      ],
    },
    "용기": {
      en: "courage",
      seeds: [
        "두려움을 느끼면서도 나아가는 것이 용기",
        "넘어진 자리에서 일어서는 것이 진짜 힘",
        "작은 한 걸음이 큰 변화를 만든다",
        "혼자라도 옳은 길을 가는 것이 용기",
        "모르는 것을 모른다고 말하는 용기",
        "도움을 청하는 것도 용기다",
        "포기하지 않는 것이 가장 큰 용기",
        "어둠 속에서 빛을 찾는 자",
        "용기는 큰 소리가 아니라 작은 행동",
        "다시 시작할 용기가 가장 어렵다",
      ],
    },
    "겸손": {
      en: "humility",
      seeds: [
        "벼는 익을수록 고개를 숙인다",
        "내가 다 알지 못한다는 사실을 아는 것",
        "남보다 한 발 뒤에 서는 자가 멀리 본다",
        "큰 그릇은 자기를 비운다",
        "자랑은 입에서 나오면 가벼워진다",
        "겸손은 강함의 표시다",
        "낮은 자리에서 더 많이 보인다",
        "스승은 늘 자기를 학생이라 부른다",
        "박수받을 때 한 걸음 물러서라",
        "겸손한 자는 잃을 것이 없다",
      ],
    },
    "가족": {
      en: "family",
      seeds: [
        "가족은 마지막까지 남는 등불",
        "한 끼를 함께하는 것이 사랑",
        "부모의 마음은 거리만큼 깊어진다",
        "형제는 같은 뿌리의 두 가지",
        "집이 클 필요는 없다, 마음이 크면 된다",
        "함께 늙어가는 것이 행복",
        "가족의 침묵에도 사랑이 있다",
        "잠든 모습을 지켜보는 것이 사랑",
        "다 큰 자식도 부모에겐 어린아이",
        "집은 사람이 아니라 사랑이 만든다",
      ],
    },
    "노력": {
      en: "diligence",
      seeds: [
        "작은 물방울이 바위를 뚫는다",
        "재능보다 꾸준함이 멀리 간다",
        "노력은 배신하지 않는다",
        "어제의 나를 이기는 자가 강한 자",
        "씨를 뿌리지 않고는 거둘 수 없다",
        "한 걸음씩이 정상에 닿게 한다",
        "성실은 가장 큰 재능이다",
        "내가 흘린 땀은 내 것이 된다",
        "지름길보다 옳은 길이 빠르다",
        "오늘의 한 시간이 미래의 하루다",
      ],
    },
    "절제": {
      en: "self-control",
      seeds: [
        "혀를 다스리는 자가 자신을 다스린다",
        "성냄은 자신을 태우는 불",
        "한 입 덜 먹는 것이 보약",
        "욕심은 가까울수록 멀어 보인다",
        "쉬는 것도 능력이다",
        "필요와 욕심을 구별하라",
        "충분함을 아는 것이 부자",
        "감정의 주인이 되어라",
        "참는 입이 인생을 살린다",
        "절제는 자유로 가는 길",
      ],
    },
    "베풂": {
      en: "generosity",
      seeds: [
        "주는 손이 받는 손보다 행복하다",
        "작은 친절은 큰 파도가 된다",
        "베풂은 손해가 아니라 투자다",
        "이름 없이 베푼 자가 가장 큰 사람이다",
        "남을 비추면 나도 밝아진다",
        "나누면 가벼워지고 움켜쥐면 무거워진다",
        "가난해도 베풀 마음은 부자다",
        "한 끼의 나눔이 평생의 인연이 된다",
        "베풂은 마음의 운동이다",
        "주는 자가 결국 더 받는다",
        "빈손으로도 따뜻한 말은 줄 수 있다",
        "작은 빵 한 조각이 누군가의 하루를 살린다",
        "베풂에는 영수증이 필요 없다",
        "받을 것을 세지 않는 손이 진짜 베푸는 손이다",
        "그늘을 만드는 나무는 제 열매를 먹지 않는다",
        "도움은 받은 사람보다 준 사람을 더 오래 따뜻하게 한다",
        "손을 펴야 더 많이 담을 수 있다",
        "베풂은 씨앗이고 시간은 그것을 나무로 키운다",
        "가진 것이 적어도 마음은 넉넉할 수 있다",
        "누군가의 짐을 들어 주면 내 어깨도 가벼워진다",
        "나눈 기쁨은 두 배가 되고 나눈 슬픔은 절반이 된다",
        "베풂은 돌려받기 위한 거래가 아니다",
        "보이지 않는 곳에서 베푼 친절이 가장 빛난다",
        "한 사람의 작은 도움이 다른 이의 큰 용기가 된다",
        "베풀 줄 아는 사람은 외롭지 않다",
        "줄 것이 없다면 미소라도 건네라",
        "친절은 이자 없이 돌아오는 빚이다",
        "베풂은 부의 크기가 아니라 마음의 크기다",
        "빈 그릇을 채워 주는 손이 가장 아름답다",
        "베풂은 받은 은혜를 다음 사람에게 흘려보내는 일이다",
        "작은 등불 하나가 어두운 길을 여러 사람에게 밝힌다",
        "줄 때 망설이면 그 마음은 이미 절반이 식는다",
        "베풂의 크기보다 베푸는 마음의 온도가 중요하다",
        "누군가에게 길을 알려 주는 것도 베풂이다",
        "베풂은 가진 자의 의무가 아니라 모두의 기쁨이다",
        "한 번의 나눔이 누군가의 평생 기억이 된다",
        "베풀고 잊는 사람이 가장 크게 베푸는 사람이다",
        "도움을 청한 손을 잡아 주는 것이 사람의 도리다",
        "베풂은 강물처럼 흘러야 썩지 않는다",
        "가장 가난한 날에 베푼 한 끼가 가장 귀하다",
        "베풂은 남을 위한 것 같지만 결국 나를 키운다",
        "따뜻한 말 한마디도 누군가에겐 큰 선물이다",
        "베풀 때는 오른손이 한 일을 왼손이 모르게 하라",
        "나눔은 나누는 사람을 먼저 부자로 만든다",
        "베풂에 조건을 달면 그것은 거래일 뿐이다",
        "어려운 이웃을 외면하지 않는 것이 진짜 부유함이다",
        "베풂은 작게 시작해도 크게 번진다",
        "누군가의 눈물을 닦아 주는 손이 가장 깨끗하다",
        "베풂은 받을 사람을 가리지 않는다",
        "줄수록 마음의 곳간이 커진다",
        "베풂은 오늘 심어 내일 거두는 농사다",
        "가진 것을 움켜쥐면 더 가난해진다",
        "베풂은 세상을 조금 더 살 만하게 만든다",
        "작은 선의가 모이면 큰 강이 된다",
        "베풀 줄 아는 아이가 마음 넉넉한 어른이 된다",
        "도움은 미루지 않을 때 가장 값지다",
        "베풂은 자랑하는 순간 빛을 잃는다",
        "빈 주머니로도 마음은 나눌 수 있다",
        "베풂은 받는 이의 자존심을 다치지 않게 하는 기술이다",
        "누군가를 도운 날의 잠은 더 깊고 평안하다",
        "나눔에는 끝이 없고 베풂에는 후회가 없다",
        "베풂은 마음의 문을 여는 열쇠다",
        "작은 친절이 큰 적의도 녹인다",
        "베풀면 잃는 것 같지만 사실은 쌓이는 것이다",
        "한 그루의 나무가 수많은 새를 쉬게 한다",
        "베풂은 가르치지 않아도 전염된다",
        "도움을 받은 기억은 사람을 더 따뜻하게 만든다",
        "베풂은 부자의 특권이 아니라 사람의 본성이다",
        "줄 수 있을 때 주는 것이 가장 큰 행운이다",
        "베풂은 보답을 기다리지 않을 때 완성된다",
        "마음을 나누면 적도 친구가 된다",
        "베풂은 손해처럼 보이지만 가장 확실한 이득이다",
        "누군가의 빈자리를 채워 주는 것이 베풂이다",
        "작은 도움이라도 늦지 않게 건네라",
        "베풂은 받은 사랑을 세상에 되돌리는 길이다",
        "가진 것을 자랑하지 말고 나눈 것을 기억하라",
        "베풂은 메마른 땅에 내리는 비와 같다",
        "누군가를 일으켜 세우면 나도 함께 일어선다",
        "베풂은 입으로 하는 것이 아니라 손으로 하는 것이다",
        "작은 나눔이 큰 신뢰를 만든다",
        "베풂은 마음이 가난해지지 않게 하는 약이다",
        "줄 것을 아끼면 받을 마음도 줄어든다",
        "베풂은 오늘의 나를 내일의 누군가에게 보내는 일이다",
        "한 사람의 따뜻함이 마을 전체를 데운다",
        "베풂은 헤아리지 않을수록 커진다",
        "도움을 준 손은 시간이 지나도 부끄럽지 않다",
        "베풂은 가장 조용한 영웅의 행동이다",
        "나눌수록 마음의 그릇은 깊어진다",
        "베풂은 받는 자를 빚쟁이로 만들지 않는다",
        "작은 정성이 큰 감동을 만든다",
        "베풂은 세상에 빚을 갚는 가장 아름다운 방법이다",
        "누군가의 추위를 덜어 주면 내 봄이 빨리 온다",
        "베풂은 후하게, 자랑은 인색하게 하라",
        "가진 것보다 나눈 것이 그 사람을 말해 준다",
        "베풂은 끝났다고 생각할 때 다시 시작된다",
        "한 손을 내밀면 두 사람이 함께 걷는다",
        "베풂은 마음의 근육이라 쓸수록 단단해진다",
        "도움은 작아도 진심이면 무겁다",
        "베풂은 받을 자격을 묻지 않는다",
        "오늘 베푼 친절이 내일의 누군가를 살린다",
      ],
    },
    "성찰": {
      en: "self-reflection",
      seeds: [
        "남을 탓하기 전에 자신을 먼저 돌아보라",
        "거울은 흙 묻은 얼굴을 가리지 않는다",
        "고요할 때 비로소 자신이 보인다",
        "하루의 끝에 자신을 한 줄로 적어 두어라",
        "잘못은 인정할수록 작아진다",
        "후회는 배움의 어머니다",
        "남의 허물은 작게, 내 허물은 크게 보라",
        "내일을 위해 오늘의 나를 돌아보라",
        "성찰은 가장 조용한 성장이다",
        "자신을 아는 사람이 세상을 안다",
        "거울 앞에서 솔직한 사람이 가장 용감하다",
        "멈춰 서야 자신이 어디 있는지 보인다",
        "변명은 성장을 가로막는 가장 부드러운 벽이다",
        "자기를 속이는 자는 가장 가까운 적을 가진 셈이다",
        "반성 없는 하루는 흘러간 모래와 같다",
        "잘못을 덮으면 자라고 마주하면 사라진다",
        "자신을 비추는 거울은 마음 안에 있다",
        "남을 가리키는 손가락 셋은 나를 향한다",
        "침묵 속에서 양심의 목소리가 들린다",
        "어제의 나를 평가할 줄 알아야 내일이 달라진다",
        "성찰은 자신과 나누는 가장 정직한 대화다",
        "깨진 그릇도 들여다봐야 다시 빚을 수 있다",
        "잘못을 웃어넘기는 사람은 같은 실수를 반복한다",
        "마음의 먼지는 자주 닦아야 쌓이지 않는다",
        "성찰은 채찍이 아니라 등불이다",
        "나를 향한 질문이 가장 어렵고 가장 값지다",
        "후회를 곱씹지 말고 교훈으로 빚어라",
        "자신을 미워하지 말되 자신에게 무르지도 마라",
        "거울은 정직하지만 그 앞에 설 용기는 내 몫이다",
        "하루를 돌아보지 않으면 같은 하루를 또 산다",
        "성찰은 과거를 후회하는 것이 아니라 다듬는 것이다",
        "내 마음을 모르면 누구의 마음도 알 수 없다",
        "잘못 앞에서 멈추는 사람이 멀리 간다",
        "자신을 들여다보는 눈이 가장 밝은 눈이다",
        "반성은 무릎 꿇는 것이 아니라 다시 서는 것이다",
        "남의 평가보다 자신의 점검이 먼저다",
        "흔들릴수록 내면을 들여다보라",
        "성찰은 마음의 거울을 닦는 일이다",
        "자기 그림자를 외면하면 빛도 보이지 않는다",
        "오늘의 실수를 적어 두면 내일의 스승이 된다",
        "자신에게 솔직한 사람만이 진짜로 자유롭다",
        "성찰 없는 경험은 나이만 먹게 한다",
        "깊은 우물일수록 조용히 자신을 비춘다",
        "마음을 들여다보는 시간이 가장 생산적인 휴식이다",
        "잘못을 변명하면 두 번 잘못하는 것이다",
        "점검하는 사람은 같은 함정에 두 번 빠지지 않는다",
        "성찰은 어제의 나에게 배우는 일이다",
        "거울을 깨지 말고 얼굴을 닦아라",
        "내 안의 소리를 들으려면 바깥의 소음을 줄여야 한다",
        "반성은 짧게, 다짐은 분명하게 하라",
        "자신을 속인 거짓말이 가장 오래 남는다",
        "하루의 끝에서 묻는 한마디가 사람을 키운다",
        "성찰은 패배의 기록이 아니라 성장의 지도다",
        "마음의 방을 자주 청소해야 어둠이 머물지 않는다",
        "자기 잘못을 먼저 보는 눈이 가장 어른스럽다",
        "후회가 깊을수록 다짐은 단단해야 한다",
        "성찰은 멈춤이 아니라 더 멀리 가기 위한 숨고르기다",
        "자신을 똑바로 본 사람만이 남을 너그럽게 본다",
        "마음의 거울에 김이 서리면 잠시 멈춰 닦아라",
        "어제와 같은 나라면 오늘은 헛산 것이다",
        "성찰은 자신을 벌하는 것이 아니라 이해하는 것이다",
        "잘못을 마주한 밤이 가장 깊은 배움의 밤이다",
        "내 안을 모르고 멀리 가면 길을 잃는다",
        "반성하는 사람의 발걸음은 흔들려도 앞을 향한다",
        "자기 점검은 가장 값싸고 가장 확실한 스승이다",
        "마음을 비추는 빛은 조용한 시간에 켜진다",
        "성찰은 어제의 나와 화해하는 일이다",
        "흠을 숨기면 곪고 드러내면 아문다",
        "자신에게 던지는 정직한 질문이 인생을 바꾼다",
        "거울은 답을 주지 않지만 진실은 보여 준다",
        "성찰 없는 성공은 다음 실패의 씨앗이다",
        "돌아본 사람은 같은 돌부리에 다시 걸리지 않는다",
        "마음의 흙탕물은 가만히 두어야 맑아진다",
        "반성은 과거를 향하지만 그 빛은 미래를 비춘다",
        "자신을 아는 깊이만큼 사람을 품을 수 있다",
        "오늘 나를 점검하지 않으면 내일이 나를 시험한다",
        "성찰은 가장 작은 방에서 일어나는 가장 큰 변화다",
        "잘못을 부끄러워하되 자신을 미워하지는 마라",
        "내면을 들여다본 사람의 말은 가볍지 않다",
        "거울 앞 1분이 헛된 하루를 구한다",
        "성찰은 자랑할 일이 아니라 조용히 할 일이다",
        "마음의 주인이 되려면 먼저 자기를 살펴야 한다",
        "흔들린 날일수록 자신에게 더 정직하라",
        "반성은 어제를 지우는 것이 아니라 다듬는 것이다",
        "자신을 비춘 빛이 결국 남도 비춘다",
        "마음의 장부는 매일 정산해야 빚이 쌓이지 않는다",
        "성찰은 멈춰 선 자리에서 길을 다시 찾는 일이다",
        "자기 허물을 아는 것이 지혜의 첫걸음이다",
        "후회만 하면 제자리, 돌아보면 한 걸음 앞이다",
        "내 안의 어둠을 인정해야 빛을 들일 수 있다",
        "성찰은 조용하지만 가장 멀리 가는 발걸음이다",
        "자신을 속이지 않는 하루가 가장 든든한 하루다",
        "거울을 자주 보는 사람이 길을 잃지 않는다",
        "반성은 어제의 나를 오늘의 스승으로 삼는 일이다",
        "마음을 들여다본 만큼 세상이 넓게 보인다",
        "성찰은 끝이 아니라 더 나은 시작의 문이다",
        "점검을 게을리한 마음에는 먼지가 쌓인다",
        "잘못 앞 솔직한 한마디가 백 마디 변명을 이긴다",
        "자신을 돌아본 밤이 다음 날을 다르게 만든다",
        "오늘의 성찰이 내일의 나를 빚는다",
      ],
    },
  };

  // 카테고리당 100개로 패딩 (시드 + 변형)
  const STORY_VARIANTS = [
    "에 관한 이야기",
    "의 다른 얼굴",
    "이 작은 마을에서 일어난 일",
    "을 깨달은 어느 날",
    "을 잊고 살았던 시간",
    "이 가르쳐준 교훈",
    "을 다시 배우다",
    "을 시험받는 순간",
    "이 빛나는 순간",
    "을 둘러싼 작은 소동",
  ];

  for (const cat of Object.keys(TALMUD_CATEGORIES)) {
    const seeds = TALMUD_CATEGORIES[cat].seeds;
    const out = [];
    let i = 0;
    while (out.length < 100) {
      const base = seeds[i % seeds.length];
      const variantIdx = Math.floor(i / seeds.length);
      if (variantIdx === 0) {
        out.push(base);
      } else {
        const suffix = STORY_VARIANTS[(variantIdx - 1) % STORY_VARIANTS.length];
        out.push(`${base}${suffix}`);
      }
      i++;
    }
    TALMUD_CATEGORIES[cat].stories = out;
  }

  return {
    CHARACTER_PRESETS,
    ANIMAL_KEYS,
    TIME_OF_DAY,
    WEATHER,
    SCENE,
    CAMERA,
    LIGHTING,
    STYLE,
    TECHNIQUE,
    RATIO,
    GENRE,
    MOOD,
    VOCAL,
    CHORUS,
    LYRIC_LANG,
    TALMUD_CATEGORIES,
  };
})();
