// 그림그리기 — 프롬프트 빌더 공용 데이터
// 모든 옵션 라벨은 한글, 프롬프트 출력은 영어로 매핑됨.

window.ODUNGI_DATA = (function () {
  // ─────────────────────────────────────────────────────────
  // 캐릭터 프리셋 (영문 설명은 이미지 생성 AI 일관성용)
  const CHARACTER_PRESETS = {
    "배추": {
      name_en: "Baechu",
      kind: "강아지",
      emoji: "🐶",
      description:
        "American Cocker Spaniel, Medium-sized 15kg dog, golden beige cream silky wavy fur, long floppy ears with flowing wavy fur, large warm gentle brown eyes, small black round nose, sweet innocent gentle expression, fluffy chest fur, warm golden tan coloring throughout",
    },
    "상추": {
      name_en: "Sangchu",
      kind: "강아지",
      emoji: "🐕",
      description:
        "Old English Sheepdog, Large and sturdy 35kg heavy-set breed, entire head and both ears MUST be 100% pure solid white without any grey markings, white chest and front legs, dark charcoal grey fur starting strictly from the shoulders and covering the back and hindquarters, very cute big round gentle puppy eyes with heterochromia (one soft brown and one soft blue, sparkling and kind expression), the tail is an entirely solid dark charcoal grey very short stubby tail with absolutely NO white color at the tip",
    },
    "열무": {
      name_en: "Yeolmu",
      kind: "강아지",
      emoji: "🦴",
      description:
        "Papillon dog, Small and dainty 5kg toy breed, brown and white coloring, very distinctive large butterfly-shaped ears with brown and white long fur, big round expressive warm brown eyes, white chest and belly, dainty elegant small frame",
    },
    "까미": {
      name_en: "Ggami",
      kind: "고양이",
      emoji: "🐱",
      description:
        "Gray tuxedo cat, dark charcoal gray body with white chest and belly, distinctive thick black mustache marking above lips, sharp piercing yellow amber eyes with intense tsundere gaze, small pink heart-shaped nose, pink heart-shaped paw pads, muscular compact body, long gray tail, grumpy exterior but secretly caring personality",
    },
    "김치": {
      name_en: "Gimchi",
      kind: "고양이",
      emoji: "🐈",
      description:
        "Scottish Fold cat, all white fluffy coat, distinctive folded flat ears pressed close to very round chubby head, sharp yellow amber eyes with perpetually grumpy stern furrowed brow expression, small pink heart-shaped nose, plump round chubby body, short stubby legs, always looks displeased and unimpressed",
    },
    "드니로": {
      name_en: "Dniro",
      kind: "사람",
      emoji: "👨",
      description:
        "Male human in Ghibli animation style, dark brown short straight hair, wearing casual everyday clothes such as hoodies or simple shirts and jeans, young adult in late 20s to early 30s, gentle kind warm face, soft warm eyes, natural relaxed confident posture",
    },
    "엘사": {
      name_en: "Elsa",
      kind: "사람",
      emoji: "👩",
      description:
        "Female human in Ghibli animation style, medium length dark brown slightly wavy hair, casual everyday style clothing such as hoodies or simple tops, young adult woman in late 20s, warm thoughtful gentle expression, soft natural features, approachable and calm appearance",
    },
    "정만": {
      name_en: "Jeongman",
      kind: "사람",
      emoji: "👩‍🦱",
      description:
        "Female human in Ghibli animation style, long dark black flowing wavy hair, distinctive round glasses, casual blue or earth-tone clothing, warm gentle smile, nature and outdoor lover vibe, thoughtful intellectual appearance, kind warm eyes behind glasses",
    },
  };
  const ANIMAL_KEYS = ["배추", "상추", "열무", "까미", "김치"];

  // ─────────────────────────────────────────────────────────
  // 한글 라벨 ➜ 영문 프롬프트 매핑 (없으면 라벨 그대로 사용)
  const pair = (ko, en) => ({ ko, en });

  // 시간대 (100+)
  const TIME_OF_DAY = [
    pair("새벽", "predawn"),
    pair("동트는 시각", "first light"),
    pair("일출", "sunrise"),
    pair("이른 아침", "early morning"),
    pair("아침", "morning"),
    pair("늦은 아침", "late morning"),
    pair("오전", "AM daylight"),
    pair("정오", "high noon"),
    pair("한낮", "midday"),
    pair("점심 시간", "lunchtime light"),
    pair("이른 오후", "early afternoon"),
    pair("오후", "afternoon"),
    pair("늦은 오후", "late afternoon"),
    pair("황금시간대", "golden hour"),
    pair("매직아워", "magic hour"),
    pair("블루아워", "blue hour"),
    pair("해질녘", "dusk"),
    pair("노을", "sunset glow"),
    pair("일몰", "sunset"),
    pair("저녁", "evening"),
    pair("이른 저녁", "early evening"),
    pair("늦은 저녁", "late evening"),
    pair("초저녁", "twilight"),
    pair("황혼", "gloaming"),
    pair("밤", "night"),
    pair("깊은 밤", "deep night"),
    pair("한밤중", "middle of the night"),
    pair("자정", "midnight"),
    pair("새벽 1시", "1 AM"),
    pair("새벽 2시", "2 AM"),
    pair("새벽 3시", "3 AM"),
    pair("새벽 4시", "4 AM"),
    pair("새벽 5시", "5 AM"),
    pair("아침 6시", "6 AM"),
    pair("아침 7시", "7 AM"),
    pair("오전 8시", "8 AM"),
    pair("오전 9시", "9 AM"),
    pair("오전 10시", "10 AM"),
    pair("오전 11시", "11 AM"),
    pair("오후 1시", "1 PM"),
    pair("오후 2시", "2 PM"),
    pair("오후 3시", "3 PM"),
    pair("오후 4시", "4 PM"),
    pair("오후 5시", "5 PM"),
    pair("오후 6시", "6 PM"),
    pair("저녁 7시", "7 PM"),
    pair("저녁 8시", "8 PM"),
    pair("밤 9시", "9 PM"),
    pair("밤 10시", "10 PM"),
    pair("밤 11시", "11 PM"),
    pair("봄 아침", "spring morning"),
    pair("봄 오후", "spring afternoon"),
    pair("여름 새벽", "summer dawn"),
    pair("여름 한낮", "summer midday"),
    pair("여름 저녁", "summer evening"),
    pair("가을 아침", "autumn morning"),
    pair("가을 오후", "autumn afternoon"),
    pair("가을 저녁", "autumn evening"),
    pair("겨울 아침", "winter morning"),
    pair("겨울 오후", "winter afternoon"),
    pair("겨울 저녁", "winter evening"),
    pair("크리스마스 이브", "christmas eve night"),
    pair("새해 자정", "new year midnight"),
    pair("정월 대보름", "full moon night"),
    pair("초승달 밤", "crescent moon night"),
    pair("보름달 밤", "full moon night"),
    pair("별이 빛나는 밤", "starry night"),
    pair("은하수 밤", "milky way night"),
    pair("유성우 밤", "meteor shower night"),
    pair("오로라 밤", "aurora night"),
    pair("폭풍 전 정적", "pre-storm stillness"),
    pair("폭풍 직후", "just after the storm"),
    pair("비 오기 직전", "moments before rain"),
    pair("비 갠 직후 아침", "morning right after rain"),
    pair("눈 내리는 새벽", "snowy dawn"),
    pair("눈 그친 저녁", "evening after snow"),
    pair("안개 낀 새벽", "foggy dawn"),
    pair("안개 낀 저녁", "foggy evening"),
    pair("흐린 정오", "overcast noon"),
    pair("개기일식 순간", "total solar eclipse"),
    pair("개기월식 순간", "total lunar eclipse"),
    pair("일출 직전", "moments before sunrise"),
    pair("일몰 직후", "moments after sunset"),
    pair("한여름 밤", "midsummer night"),
    pair("한겨울 새벽", "midwinter dawn"),
    pair("입학식 아침", "school opening morning"),
    pair("졸업식 오후", "graduation afternoon"),
    pair("주말 아침", "weekend morning"),
    pair("주말 오후", "weekend afternoon"),
    pair("월요일 출근길", "monday commute morning"),
    pair("금요일 저녁", "friday evening"),
    pair("토요일 밤", "saturday night"),
    pair("일요일 오후", "sunday afternoon"),
    pair("휴일 정오", "holiday noon"),
    pair("야시장 시간", "night market hour"),
    pair("새벽 시장", "dawn market"),
    pair("등굣길 아침", "school walk morning"),
    pair("하굣길 오후", "after-school afternoon"),
    pair("산책 시간", "walking-the-dog hour"),
    pair("티타임 오후", "afternoon tea time"),
    pair("브런치 오전", "brunch hour"),
    pair("야식 시간", "late-night snack hour"),
    pair("늦은 밤 독서", "late-night reading hour"),
  ];

  // 날씨 (100+)
  const WEATHER = [
    pair("맑음", "clear sky"),
    pair("쾌청", "bright clear weather"),
    pair("부분적으로 흐림", "partly cloudy"),
    pair("흐림", "overcast"),
    pair("뭉게구름", "fluffy cumulus clouds"),
    pair("새털구름", "wispy cirrus clouds"),
    pair("양떼구름", "altocumulus clouds"),
    pair("먹구름", "dark thunderclouds"),
    pair("비", "rain"),
    pair("이슬비", "drizzle"),
    pair("보슬비", "light drizzle"),
    pair("소나기", "sudden shower"),
    pair("장맛비", "monsoon rain"),
    pair("폭우", "heavy downpour"),
    pair("천둥번개", "thunder and lightning"),
    pair("벼락", "lightning strike"),
    pair("우박", "hail"),
    pair("진눈깨비", "sleet"),
    pair("싸락눈", "ice pellets"),
    pair("눈", "snow"),
    pair("함박눈", "big snowflakes falling"),
    pair("폭설", "blizzard"),
    pair("눈보라", "snow storm"),
    pair("가루눈", "powder snow"),
    pair("첫눈", "first snowfall"),
    pair("밤새 내린 눈", "overnight snowfall covering everything"),
    pair("바람", "windy"),
    pair("산들바람", "gentle breeze"),
    pair("강풍", "strong wind"),
    pair("돌풍", "wind gust"),
    pair("회오리바람", "whirlwind"),
    pair("태풍", "typhoon"),
    pair("허리케인", "hurricane"),
    pair("토네이도", "tornado"),
    pair("황사", "yellow dust haze"),
    pair("미세먼지", "fine dust haze"),
    pair("매연", "smog"),
    pair("안개", "fog"),
    pair("짙은 안개", "thick fog"),
    pair("물안개", "river mist"),
    pair("산안개", "mountain mist"),
    pair("이슬", "morning dew"),
    pair("서리", "frost"),
    pair("된서리", "heavy frost"),
    pair("성에", "frost on windows"),
    pair("얼음", "icy surfaces"),
    pair("결빙", "freezing surface"),
    pair("폭염", "heatwave"),
    pair("열대야", "tropical night heat"),
    pair("푹푹 찌는 더위", "sweltering humid heat"),
    pair("쨍쨍한 햇살", "blazing sunshine"),
    pair("강한 자외선", "strong UV daylight"),
    pair("아지랑이", "heat shimmer"),
    pair("미풍", "soft breeze"),
    pair("훈풍", "warm spring breeze"),
    pair("찬바람", "cold wind"),
    pair("칼바람", "biting cold wind"),
    pair("동장군", "hard winter cold"),
    pair("한파", "cold wave"),
    pair("꽃샘추위", "spring cold snap"),
    pair("늦더위", "lingering late summer heat"),
    pair("초가을 선선함", "crisp early autumn"),
    pair("쌀쌀함", "chilly air"),
    pair("포근함", "mild warm weather"),
    pair("아늑한 날씨", "cozy weather"),
    pair("비 갠 후", "after the rain"),
    pair("무지개", "rainbow"),
    pair("쌍무지개", "double rainbow"),
    pair("노을빛 구름", "sunset-lit clouds"),
    pair("핑크빛 하늘", "pink sky"),
    pair("보랏빛 하늘", "violet sky"),
    pair("주황빛 하늘", "orange sky"),
    pair("회색 하늘", "grey sky"),
    pair("푸른 하늘", "deep blue sky"),
    pair("쨍한 파란 하늘", "vivid blue sky"),
    pair("별이 보이는 맑은 밤", "clear starlit night"),
    pair("달무리", "moon halo"),
    pair("해무리", "sun halo"),
    pair("물방울 떨어지는 처마", "raindrops dripping from eaves"),
    pair("창문에 맺힌 빗방울", "raindrops on the window"),
    pair("바닥에 고인 물웅덩이", "puddles on the ground"),
    pair("젖은 도로", "wet asphalt"),
    pair("진흙탕", "muddy ground"),
    pair("눈 덮인 풍경", "snow-covered landscape"),
    pair("얼어붙은 호수", "frozen lake"),
    pair("얼음장 같은 강", "icy river"),
    pair("바람에 흔들리는 나뭇잎", "leaves rustling in the wind"),
    pair("바람에 날리는 벚꽃", "cherry blossoms blowing in wind"),
    pair("바람에 날리는 은행잎", "ginkgo leaves blowing in wind"),
    pair("바람에 날리는 단풍잎", "maple leaves blowing in wind"),
    pair("낙엽 가득한 거리", "street full of fallen leaves"),
    pair("벚꽃 흩날림", "cherry blossom petals falling"),
    pair("매화꽃 흩날림", "plum blossom petals falling"),
    pair("황금 들녘", "golden rice field"),
    pair("푸른 들녘", "green rice field"),
    pair("폭우 후 무지개", "rainbow after heavy rain"),
    pair("비 오는 야경", "rainy night cityscape"),
    pair("눈 오는 야경", "snowy night cityscape"),
    pair("새벽이슬 머금은 잔디", "dewy grass at dawn"),
    pair("아침 안개 자욱한 숲", "morning mist in the forest"),
    pair("저녁노을 구름", "sunset-streaked clouds"),
    pair("우산이 필요한 비", "umbrella weather"),
  ];

  // 배경 (500+ — 카테고리별 그룹)
  const SCENE = [
    // 도시
    pair("도심 한복판", "downtown city center"),
    pair("서울 광화문 광장", "Gwanghwamun square Seoul"),
    pair("서울 명동 거리", "Myeongdong street Seoul"),
    pair("서울 홍대 거리", "Hongdae street Seoul"),
    pair("서울 강남대로", "Gangnam boulevard Seoul"),
    pair("서울 한강 둔치", "Han river park Seoul"),
    pair("서울 남산타워 전망대", "N Seoul Tower observatory"),
    pair("서울 북촌 한옥마을", "Bukchon hanok village"),
    pair("서울 인사동 골목", "Insadong alley"),
    pair("서울 이태원 거리", "Itaewon street"),
    pair("서울 청계천", "Cheonggyecheon stream"),
    pair("서울 성수동 카페거리", "Seongsu cafe street"),
    pair("서울 익선동 한옥카페", "Ikseondong hanok cafe street"),
    pair("부산 해운대 해변", "Haeundae beach Busan"),
    pair("부산 광안리 해변", "Gwangalli beach"),
    pair("부산 감천문화마을", "Gamcheon culture village"),
    pair("부산 자갈치 시장", "Jagalchi fish market"),
    pair("제주 협재 해변", "Hyeopjae beach Jeju"),
    pair("제주 우도", "Udo island Jeju"),
    pair("제주 한라산", "Hallasan mountain"),
    pair("제주 성산일출봉", "Seongsan Ilchulbong"),
    pair("제주 올레길", "Jeju Olle trail"),
    pair("경주 황리단길", "Hwangnidan street Gyeongju"),
    pair("경주 첨성대 잔디밭", "Cheomseongdae lawn"),
    pair("전주 한옥마을", "Jeonju hanok village"),
    pair("강릉 안목 커피거리", "Anmok coffee street Gangneung"),
    pair("강릉 경포대 해변", "Gyeongpodae beach"),
    pair("속초 동명항", "Donghang port Sokcho"),
    pair("여수 밤바다", "Yeosu night sea"),
    pair("순천만 갈대밭", "Suncheon Bay reed field"),
    pair("담양 메타세쿼이아길", "Damyang metasequoia road"),
    pair("안동 하회마을", "Andong hahoe village"),
    pair("도쿄 시부야 교차로", "Shibuya crossing Tokyo"),
    pair("도쿄 신주쿠 골목", "Shinjuku alley"),
    pair("도쿄 아사쿠사 절", "Asakusa temple"),
    pair("교토 기온 거리", "Gion street Kyoto"),
    pair("오사카 도톤보리", "Dotonbori Osaka"),
    pair("홋카이도 설경 마을", "Hokkaido snowy village"),
    pair("뉴욕 타임스퀘어", "Times Square New York"),
    pair("뉴욕 센트럴파크", "Central Park"),
    pair("파리 에펠탑 광장", "Eiffel Tower plaza"),
    pair("파리 몽마르트 언덕", "Montmartre hill"),
    pair("런던 빅벤 앞", "Big Ben London"),
    pair("로마 콜로세움", "Colosseum Rome"),
    pair("베네치아 운하", "Venice canal"),
    pair("산토리니 골목", "Santorini alley"),
    pair("뉴질랜드 호빗마을", "Hobbiton style village"),
    pair("아이슬란드 빙하", "Iceland glacier"),
    // 자연
    pair("푸른 잔디 언덕", "rolling green grass hill"),
    pair("들꽃 가득한 들판", "wildflower meadow"),
    pair("유채꽃밭", "canola flower field"),
    pair("해바라기밭", "sunflower field"),
    pair("라벤더밭", "lavender field"),
    pair("튤립밭", "tulip field"),
    pair("코스모스밭", "cosmos field"),
    pair("벚꽃 가로수길", "cherry blossom tree avenue"),
    pair("벚꽃 만개한 공원", "park in full cherry bloom"),
    pair("매화나무 아래", "under a plum blossom tree"),
    pair("은행나무 가로수길", "ginkgo tree-lined road"),
    pair("단풍 가득한 산길", "mountain trail full of autumn leaves"),
    pair("소나무 숲", "pine forest"),
    pair("대나무 숲", "bamboo grove"),
    pair("자작나무 숲", "birch forest"),
    pair("울창한 활엽수림", "dense broadleaf forest"),
    pair("열대우림", "tropical rainforest"),
    pair("이끼 낀 숲", "mossy forest floor"),
    pair("계곡 옆 너럭바위", "flat rock by a creek"),
    pair("폭포 앞", "in front of a waterfall"),
    pair("호숫가", "lakeside"),
    pair("호수 위 나무 데크", "wooden dock over a lake"),
    pair("바닷가 모래사장", "sandy beach"),
    pair("바닷가 자갈밭", "pebble beach"),
    pair("바위 해안", "rocky coastline"),
    pair("등대 앞 절벽", "cliff in front of a lighthouse"),
    pair("백사장과 야자수", "white beach with palm trees"),
    pair("산호초 바다", "coral reef sea"),
    pair("심해", "deep ocean"),
    pair("강가 자갈밭", "river pebble bed"),
    pair("강변 풀밭", "grassy riverbank"),
    pair("폭포수 아래", "underneath a waterfall"),
    pair("호수 위 안개", "mist over a lake"),
    pair("산 정상", "mountain peak"),
    pair("산 능선", "mountain ridge"),
    pair("설산", "snow-capped mountain"),
    pair("화산 분화구", "volcano crater"),
    pair("협곡", "canyon"),
    pair("사막 한가운데", "in the middle of the desert"),
    pair("사막 오아시스", "desert oasis"),
    pair("모래언덕", "sand dunes"),
    pair("초원", "wide prairie"),
    pair("툰드라", "tundra landscape"),
    pair("빙하", "glacier"),
    pair("얼어붙은 호수 위", "on a frozen lake"),
    pair("바위 동굴", "rock cave"),
    pair("종유석 동굴", "stalactite cave"),
    pair("얼음 동굴", "ice cave"),
    pair("산속 옹달샘", "mountain spring"),
    pair("개울가", "by a small stream"),
    pair("이끼 낀 돌담", "mossy stone wall"),
    // 시골/전원
    pair("시골 논두렁", "rural rice paddy path"),
    pair("황금 논", "golden rice paddy"),
    pair("배추밭", "cabbage field"),
    pair("고추밭", "chili pepper field"),
    pair("사과 과수원", "apple orchard"),
    pair("감나무 마당", "yard with a persimmon tree"),
    pair("매실 농장", "plum farm"),
    pair("귤 농장", "tangerine farm"),
    pair("초가집 마당", "thatched house yard"),
    pair("기와집 마당", "tiled-roof hanok yard"),
    pair("툇마루", "hanok wooden porch"),
    pair("마당 평상", "yard wooden bench"),
    pair("우물가", "by an old well"),
    pair("장독대", "row of earthen jars"),
    pair("외양간", "old cowshed"),
    pair("닭장", "chicken coop"),
    pair("개울 위 징검다리", "stepping stones over a stream"),
    pair("시골 버스 정류장", "rural bus stop"),
    pair("시골 기차역", "small countryside train station"),
    pair("코스모스 핀 시골길", "country road with cosmos"),
    pair("벼 베기 직전 들판", "rice field just before harvest"),
    pair("허수아비 선 논", "scarecrow standing in a rice paddy"),
    pair("시골 5일장", "rural five-day market"),
    pair("산골 화전민 집", "mountain hut"),
    // 실내 — 집
    pair("아늑한 거실 소파", "cozy living room sofa"),
    pair("우드톤 거실", "warm wooden living room"),
    pair("미니멀 거실", "minimal living room"),
    pair("벽난로 앞", "in front of a fireplace"),
    pair("크리스마스 트리 옆", "next to a christmas tree"),
    pair("창가 의자", "chair by the window"),
    pair("창가 햇살 드는 자리", "sunlit window seat"),
    pair("부엌 식탁", "kitchen dining table"),
    pair("아일랜드 조리대", "kitchen island"),
    pair("아침 식사 차린 식탁", "breakfast table"),
    pair("커피 내리는 부엌", "kitchen with coffee being brewed"),
    pair("빵 굽는 오븐 앞", "in front of a baking oven"),
    pair("침실 침대 위", "on a bedroom bed"),
    pair("러그 깔린 바닥", "rug on the floor"),
    pair("이불 위", "on a duvet"),
    pair("창가 책상", "desk by the window"),
    pair("책장 가득한 서재", "study room full of bookshelves"),
    pair("작은 작업실", "small home studio"),
    pair("욕실 욕조", "bathroom bathtub"),
    pair("샤워 부스 앞", "in front of a shower"),
    pair("드레스룸", "walk-in closet"),
    pair("발코니", "balcony"),
    pair("작은 베란다 정원", "small balcony garden"),
    pair("옥상 정원", "rooftop garden"),
    pair("옥탑방", "rooftop room"),
    pair("다락방", "attic room"),
    pair("지하 창고", "basement storage room"),
    pair("현관", "front entrance hallway"),
    pair("신발장 앞", "in front of the shoe cabinet"),
    pair("거실 카펫 위 캠핑", "indoor camping on the living room rug"),
    // 카페/식당
    pair("따뜻한 우드톤 카페", "warm wooden cafe"),
    pair("화이트톤 미니멀 카페", "white minimal cafe"),
    pair("브런치 카페 야외 테이블", "brunch cafe outdoor table"),
    pair("로스터리 카페", "specialty roastery cafe"),
    pair("골목 작은 카페", "small alley cafe"),
    pair("한옥 카페", "hanok-style cafe"),
    pair("북카페", "book cafe"),
    pair("디저트 카페", "dessert cafe"),
    pair("도넛 가게", "donut shop"),
    pair("베이커리", "bakery"),
    pair("동네 빵집 앞", "in front of a neighborhood bakery"),
    pair("아이스크림 가게", "ice cream parlor"),
    pair("핫초코 가게", "hot chocolate shop"),
    pair("뱅쇼 끓는 카페", "cafe with mulled wine simmering"),
    pair("이자카야", "japanese izakaya"),
    pair("선술집", "korean pojangmacha"),
    pair("포장마차", "street food cart"),
    pair("국숫집", "noodle restaurant"),
    pair("분식집", "korean snack shop"),
    pair("떡볶이 가게", "tteokbokki shop"),
    pair("치킨집 테이블", "fried chicken restaurant table"),
    pair("삼겹살집", "korean BBQ restaurant"),
    pair("스시 카운터", "sushi counter"),
    pair("라멘집", "ramen shop"),
    pair("이탈리안 레스토랑", "italian restaurant"),
    pair("프렌치 비스트로", "french bistro"),
    pair("파인다이닝", "fine dining restaurant"),
    pair("푸드트럭 앞", "in front of a food truck"),
    pair("야시장 노점", "night market street stall"),
    pair("재래시장 골목", "traditional market alley"),
    // 학교/일터
    pair("초등학교 운동장", "elementary school playground"),
    pair("중학교 복도", "middle school hallway"),
    pair("고등학교 교실", "high school classroom"),
    pair("대학교 캠퍼스 잔디밭", "university campus lawn"),
    pair("대학교 도서관", "university library"),
    pair("학원 강의실", "private academy classroom"),
    pair("작은 사무실", "small office"),
    pair("코워킹 스페이스", "coworking space"),
    pair("회의실", "meeting room"),
    pair("회사 옥상 휴게실", "office rooftop lounge"),
    pair("회사 탕비실", "office pantry"),
    pair("창고형 작업실", "warehouse style studio"),
    pair("화가의 아틀리에", "painter's atelier"),
    pair("도예 공방", "ceramic pottery studio"),
    pair("목공방", "woodworking shop"),
    pair("미용실", "hair salon"),
    pair("플라워샵", "flower shop"),
    pair("동네 책방", "neighborhood bookshop"),
    pair("문구점", "stationery shop"),
    pair("음반 가게", "record store"),
    pair("악기 가게", "musical instrument store"),
    pair("필름 사진관", "film photo studio"),
    pair("스튜디오 촬영장", "photography studio"),
    pair("영화관 객석", "movie theater seat"),
    pair("작은 극장", "small theater"),
    pair("미술관 전시실", "art museum gallery"),
    pair("박물관 복도", "museum hallway"),
    // 교통
    pair("기차 창가 좌석", "train window seat"),
    pair("기차 식당칸", "train dining car"),
    pair("KTX 좌석", "KTX seat"),
    pair("시골 무궁화호 안", "saemaul train interior"),
    pair("지하철 안", "subway car"),
    pair("지하철 플랫폼", "subway platform"),
    pair("버스 안", "city bus interior"),
    pair("버스 정류장", "bus stop"),
    pair("택시 뒷좌석", "taxi back seat"),
    pair("자동차 운전석", "car driver seat"),
    pair("자동차 조수석", "car passenger seat"),
    pair("캠핑카 안", "RV camper interior"),
    pair("비행기 창가 자리", "airplane window seat"),
    pair("비행기 화물칸 펫박스", "airplane pet box"),
    pair("공항 게이트", "airport gate"),
    pair("공항 활주로", "airport runway"),
    pair("기차역 대합실", "train station waiting room"),
    pair("자전거 뒷자리", "back of a bicycle"),
    pair("스쿠터 발판", "scooter footboard"),
    pair("페리 갑판", "ferry deck"),
    pair("요트 갑판", "yacht deck"),
    pair("열기구 바구니", "hot air balloon basket"),
    pair("케이블카 안", "cable car interior"),
    pair("자전거 도로", "bike lane"),
    pair("산악자전거 트레일", "mountain bike trail"),
    // 야외 활동
    pair("캠핑장 텐트 앞", "campsite in front of a tent"),
    pair("글램핑 사이트", "glamping site"),
    pair("캠핑 모닥불 앞", "in front of a campfire"),
    pair("바비큐 그릴 옆", "next to a BBQ grill"),
    pair("강가 캠핑", "riverside camping"),
    pair("산속 캠핑", "mountain camping"),
    pair("계곡 물놀이", "valley water play"),
    pair("해변 파라솔 아래", "under a beach parasol"),
    pair("스노클링", "snorkeling underwater"),
    pair("서핑 보드 위", "on a surfboard"),
    pair("패들보드 위", "on a paddle board"),
    pair("카약", "in a kayak"),
    pair("등산로", "hiking trail"),
    pair("등산로 정상 표지석", "mountain peak marker"),
    pair("나무다리", "wooden bridge"),
    pair("출렁다리", "suspension bridge"),
    pair("자전거 한강길", "Han river bike path"),
    pair("스케이트장", "ice skating rink"),
    pair("스키 슬로프", "ski slope"),
    pair("스노보드 슬로프", "snowboard slope"),
    pair("눈썰매장", "snow sled hill"),
    pair("아이스링크 한복판", "center of an ice rink"),
    pair("놀이공원", "amusement park"),
    pair("회전목마 앞", "in front of a carousel"),
    pair("관람차 안", "inside a ferris wheel"),
    pair("롤러코스터 트랙", "roller coaster track"),
    pair("워터파크 슬라이드", "water park slide"),
    pair("동물원 사파리", "zoo safari area"),
    pair("수족관 터널", "aquarium tunnel"),
    pair("식물원 온실", "botanical garden greenhouse"),
    pair("국립공원 산책로", "national park trail"),
    pair("골프장 페어웨이", "golf course fairway"),
    pair("축구 경기장", "soccer stadium"),
    pair("야구장 외야석", "baseball outfield seats"),
    pair("테니스 코트", "tennis court"),
    pair("농구 코트", "basketball court"),
    pair("배드민턴장", "badminton court"),
    pair("수영장 풀사이드", "swimming pool side"),
    pair("실내 클라이밍장", "indoor climbing gym"),
    pair("승마장", "horse riding arena"),
    pair("양궁장", "archery range"),
    // 판타지/스타일라이즈드
    pair("환상의 꽃밭", "fantasy flower meadow"),
    pair("반딧불 가득한 숲", "forest full of fireflies"),
    pair("거대 버섯 숲", "giant mushroom forest"),
    pair("동화 속 마을", "fairytale village"),
    pair("마법의 도서관", "magical library"),
    pair("물 위에 떠 있는 섬", "floating island over water"),
    pair("구름 위 정원", "garden above the clouds"),
    pair("별 가득한 밤하늘 아래", "under a star-filled night sky"),
    pair("은하수 아래 들판", "field under the milky way"),
    pair("우주 정거장", "space station interior"),
    pair("달 표면", "moon surface"),
    pair("화성 표면", "mars surface"),
    pair("외계 행성", "alien planet"),
    pair("수중 도시", "underwater city"),
    pair("얼음 궁전", "ice palace"),
    pair("거대한 도서탑", "giant tower library"),
    pair("이세계 시장", "isekai market street"),
    pair("판타지 성", "fantasy castle"),
    pair("드래곤 둥지", "dragon nest"),
    pair("정령의 숲", "spirit forest"),
    pair("이끼 정령 호수", "moss spirit lake"),
    pair("거대 고래가 헤엄치는 하늘", "sky with giant whales swimming"),
    pair("종이 접기 마을", "origami paper village"),
    pair("거대한 책상 위", "on top of a giant desk"),
    pair("거대한 케이크 위", "on top of a giant cake"),
    pair("도서관 책탑 사이", "between towers of stacked books"),
    pair("뜨개질 같은 풍경", "knitted yarn landscape"),
    pair("종이 콜라주 풍경", "paper collage landscape"),
    pair("크레용으로 그린 마을", "crayon drawn village"),
    pair("픽셀 아트 도시", "pixel art city"),
    pair("미니어처 정원", "miniature garden"),
    pair("디오라마 박스", "diorama box"),
    pair("스노우볼 안", "inside a snow globe"),
    pair("유리병 속 풍경", "landscape inside a glass bottle"),
    pair("거대한 컵 안 카페", "cafe inside a giant cup"),
    pair("이불 요새", "blanket fort"),
    pair("쿠션 더미 위", "on top of a pile of cushions"),
    pair("종이 비행기 가득한 하늘", "sky full of paper planes"),
    pair("열기구 가득한 하늘", "sky full of hot air balloons"),
    pair("등불 가득한 강", "river full of paper lanterns"),
    pair("풍선 가득한 광장", "plaza full of balloons"),
    pair("거품 가득한 욕조", "bubble-filled bathtub"),
    pair("물풍선 가득한 마당", "yard full of water balloons"),
    pair("낙엽 풀장", "pile of fallen leaves"),
    pair("밀가루 폭발한 부엌", "kitchen exploded with flour"),
    pair("케이크 부스러기 가득한 식탁", "table covered in cake crumbs"),
    pair("선물 상자 더미", "pile of gift boxes"),
    pair("크리스마스 양말 옆 벽난로", "fireplace with christmas stockings"),
    pair("할로윈 호박 정원", "halloween pumpkin patch"),
    pair("폭죽 터지는 하늘", "fireworks in the sky"),
    pair("불꽃놀이 강변", "riverside fireworks"),
    pair("일루미네이션 거리", "illumination street"),
    pair("거대한 LED 광장", "giant LED billboard plaza"),
    pair("네온사인 골목", "neon sign alley"),
    pair("사이버펑크 거리", "cyberpunk street"),
    pair("미래도시 옥상", "futuristic city rooftop"),
    pair("스팀펑크 항구", "steampunk harbor"),
    pair("빈티지 70년대 거리", "vintage 70s street"),
    pair("80년대 신스웨이브 풍경", "80s synthwave landscape"),
    pair("90년대 도쿄 골목", "90s Tokyo alley"),
    pair("개항기 항구", "old harbor town"),
    pair("조선시대 저잣거리", "joseon era market street"),
    pair("고려시대 궁궐", "goryeo palace"),
    pair("일제강점기 학교", "early 20th century korean school"),
    pair("60년대 다방", "1960s korean dabang"),
    pair("80년대 만화방", "1980s comic book rental shop"),
    pair("90년대 오락실", "1990s arcade"),
    pair("PC방", "korean PC bang"),
    pair("노래방", "korean karaoke room"),
    pair("동전 노래방", "coin karaoke booth"),
    pair("사진관 인생네컷 부스", "korean photo booth"),
    pair("코인 빨래방", "coin laundromat"),
    pair("24시간 편의점", "24-hour convenience store"),
    pair("늦은 밤 편의점 앞 테이블", "late night convenience store outdoor table"),
    pair("심야식당", "midnight diner"),
    pair("심야 영화관", "late-night movie theater"),
    pair("24시 해장국집", "24-hour haejangguk restaurant"),
    pair("새벽 시장 어묵 가게", "early morning fishcake stall"),
    pair("호텔 로비", "hotel lobby"),
    pair("호텔 방", "hotel room"),
    pair("스파 사우나", "spa sauna"),
    pair("찜질방", "korean jjimjilbang"),
    pair("목욕탕", "korean public bathhouse"),
    pair("동네 미용실", "neighborhood beauty salon"),
    pair("동네 세탁소", "neighborhood dry cleaners"),
    pair("동네 철물점", "neighborhood hardware store"),
    pair("동네 떡집", "neighborhood rice cake shop"),
    pair("우체국 앞", "in front of a post office"),
    pair("동사무소", "neighborhood community center"),
    pair("도서관 열람실", "library reading room"),
    pair("도서관 어린이 코너", "library children's corner"),
    pair("공원 벤치", "park bench"),
    pair("동네 놀이터", "neighborhood playground"),
    pair("그네 앞", "in front of a swing"),
    pair("미끄럼틀 위", "on top of a slide"),
    pair("시소 위", "on a seesaw"),
    pair("정자 안", "inside a traditional pavilion"),
    pair("정자 아래 그늘", "in the shade of a pavilion"),
    pair("산책로 벤치", "trail bench"),
    pair("강아지 운동장", "dog park"),
    pair("강아지 카페", "dog cafe"),
    pair("고양이 카페", "cat cafe"),
    pair("애견 미용실", "pet grooming salon"),
    pair("동물병원 대기실", "vet clinic waiting room"),
    pair("동물병원 진료실", "vet examination room"),
    pair("펫샵 진열대", "pet shop shelf"),
    pair("강아지 호텔 객실", "pet hotel room"),
    pair("강아지 유치원", "doggy daycare"),
    pair("강아지 수영장", "dog swimming pool"),
    pair("야외 도그런", "outdoor dog run"),
    // 추가 일상
    pair("동네 산책길", "neighborhood walking path"),
    pair("아파트 단지 놀이터", "apartment complex playground"),
    pair("아파트 단지 정원", "apartment complex garden"),
    pair("주차장", "parking lot"),
    pair("지하주차장", "underground parking lot"),
    pair("엘리베이터 안", "inside an elevator"),
    pair("계단 층계참", "stairwell landing"),
    pair("옥상 빨래줄", "rooftop laundry line"),
    pair("이불 널어둔 베란다", "balcony with hanging laundry"),
    pair("창틀에 화분", "window sill with potted plants"),
    pair("실내 정원", "indoor garden"),
    pair("화분 가득한 거실", "living room full of houseplants"),
    pair("난로 위 주전자", "kettle on a stove"),
    pair("벽시계 아래", "below a wall clock"),
    pair("커다란 거울 앞", "in front of a large mirror"),
    pair("창문에 비친 모습", "reflection on a window"),
    pair("물웅덩이에 비친 풍경", "reflection in a puddle"),
    pair("자동차 백미러", "car rearview mirror reflection"),
    pair("열차 차창 너머", "view through a train window"),
    pair("비행기 창 너머 구름", "clouds outside an airplane window"),
    pair("배 창문 너머 바다", "sea outside a ship porthole"),
    pair("터널 입구", "tunnel entrance"),
    pair("터널 안 가로등", "tunnel interior lights"),
    pair("골목 막다른 길", "alley dead end"),
    pair("좁은 골목길", "narrow alley"),
    pair("벽 가득 그래피티 골목", "graffiti-filled alley"),
    pair("벽화 마을 골목", "mural village alley"),
    pair("계단식 골목", "stepped alley"),
    pair("언덕 위 동네", "hilltop neighborhood"),
    pair("바다 보이는 언덕", "hill with a sea view"),
    pair("야경 보이는 옥상", "rooftop with a night cityscape view"),
  ];

  // 카메라 뷰
  const CAMERA = [
    pair("투시뷰", "perspective view"),
    pair("미디엄뷰", "medium shot"),
    pair("전신뷰", "full body shot"),
    pair("측면뷰", "side profile view"),
    pair("정면뷰", "front view"),
    pair("후면뷰", "back view"),
    pair("로우앵글뷰", "low angle view"),
    pair("클로즈업뷰", "close-up shot"),
    pair("익스트림 클로즈업", "extreme close-up"),
    pair("와이드뷰", "wide angle shot"),
    pair("버드아이뷰", "bird's eye view"),
    pair("아이소메트릭뷰", "isometric view"),
    pair("3/4 뷰", "three-quarter view"),
    pair("탑다운뷰", "top down view"),
    pair("드론샷", "drone shot"),
    pair("어깨너머 샷", "over-the-shoulder shot"),
    pair("더치 앵글", "dutch angle"),
    pair("매크로 샷", "macro shot"),
  ];

  // 광원
  const LIGHTING = [
    pair("햇빛", "natural sunlight"),
    pair("아침 햇살", "morning sunlight"),
    pair("황금빛 햇살", "golden hour sunlight"),
    pair("창문 통과 햇살", "sunlight through a window"),
    pair("나무 사이 햇살", "dappled sunlight through trees"),
    pair("달빛", "moonlight"),
    pair("별빛", "starlight"),
    pair("불빛", "firelight"),
    pair("모닥불 빛", "campfire light"),
    pair("벽난로 빛", "fireplace glow"),
    pair("촛불", "candlelight"),
    pair("랜턴", "lantern light"),
    pair("종이등 빛", "paper lantern light"),
    pair("전등", "incandescent bulb"),
    pair("형광등", "fluorescent light"),
    pair("백열등", "warm tungsten light"),
    pair("LED 조명", "LED lighting"),
    pair("네온사인", "neon signs"),
    pair("크리스마스 전구", "christmas string lights"),
    pair("스튜디오 조명", "studio softbox lighting"),
    pair("림 라이트", "rim lighting"),
    pair("백라이트", "backlight"),
    pair("사이드 라이트", "side lighting"),
    pair("실루엣 라이트", "silhouette lighting"),
    pair("스포트라이트", "spotlight"),
    pair("프로젝터 빛", "projector light"),
    pair("화면 불빛", "screen glow"),
    pair("반딧불빛", "firefly glow"),
    pair("바이오 루미네선스", "bioluminescent glow"),
  ];

  // 화풍
  const STYLE = [
    pair("유화", "oil painting"),
    pair("수채화", "watercolor painting"),
    pair("색연필화", "colored pencil drawing"),
    pair("크레파스화", "crayon drawing"),
    pair("펜화", "pen and ink drawing"),
    pair("연필화", "pencil sketch"),
    pair("목탄화", "charcoal drawing"),
    pair("수묵화", "ink wash painting"),
    pair("동양화", "traditional korean painting"),
    pair("민화", "korean minhwa folk painting"),
    pair("아크릴화", "acrylic painting"),
    pair("파스텔화", "soft pastel painting"),
    pair("과슈화", "gouache painting"),
    pair("디지털 페인팅", "digital painting"),
    pair("픽셀 아트", "pixel art"),
    pair("벡터 일러스트", "vector flat illustration"),
    pair("3D 렌더", "3D rendered illustration"),
    pair("클레이메이션", "claymation style"),
    pair("종이접기 스타일", "origami paper craft style"),
    pair("종이콜라주", "paper collage style"),
    pair("자수 스타일", "embroidery style"),
    pair("뜨개질 스타일", "knitted yarn style"),
    pair("펠트 인형 스타일", "felt doll style"),
    pair("지브리 스타일", "studio ghibli style"),
    pair("디즈니 스타일", "disney animation style"),
    pair("픽사 스타일", "pixar 3D style"),
    pair("애니메이션 셀화", "anime cel animation style"),
    pair("만화책 스타일", "comic book style"),
    pair("동화책 일러스트", "children's storybook illustration"),
    pair("그래픽 노블", "graphic novel style"),
    pair("스토리보드 스케치", "storyboard sketch"),
    pair("포토리얼리스틱", "photorealistic"),
    pair("하이퍼리얼리즘", "hyperrealism"),
    pair("필름 사진", "film photography"),
    pair("폴라로이드", "polaroid photo"),
    pair("빈티지 사진", "vintage photograph"),
    pair("로모그래피", "lomography"),
  ];

  // 기법
  const TECHNIQUE = [
    pair("붓 터치", "brush stroke texture"),
    pair("나이프 터치", "palette knife texture"),
    pair("스펀지 텍스처", "sponge texture"),
    pair("손가락 페인팅", "finger painting texture"),
    pair("세밀화", "highly detailed rendering"),
    pair("라인 드로잉", "line drawing"),
    pair("물 번짐", "wet-on-wet bleeding"),
    pair("물감 흩뿌리기", "paint splatter"),
    pair("임파스토", "impasto thick paint"),
    pair("마띠에르", "textured matiere"),
    pair("색 쌓기", "layered color glazing"),
    pair("입체감 강조", "strong sense of depth"),
    pair("투명한 표현", "transparent translucent rendering"),
    pair("여백의 미", "generous negative space"),
    pair("3가지 색만 사용", "limited 3-color palette"),
    pair("낮은 채도", "muted desaturated tones"),
    pair("높은 채도", "highly saturated colors"),
    pair("따뜻한 톤", "warm color palette"),
    pair("차가운 톤", "cool color palette"),
    pair("모노톤", "monochrome palette"),
    pair("세피아톤", "sepia tone"),
    pair("그레인 텍스처", "film grain texture"),
    pair("종이 텍스처", "paper grain texture"),
    pair("캔버스 텍스처", "canvas texture"),
    pair("부드러운 그라데이션", "soft gradient blending"),
    pair("플랫 컬러", "flat color blocking"),
    pair("크로스해칭", "cross-hatching shading"),
    pair("점묘법", "pointillism"),
    pair("스텐실", "stencil style"),
    pair("실루엣 강조", "strong silhouette emphasis"),
    pair("강한 명암 대비", "high chiaroscuro contrast"),
    pair("부드러운 명암", "soft gentle shading"),
    pair("얕은 피사계심도", "shallow depth of field"),
    pair("보케 배경", "bokeh background"),
    pair("렌즈 플레어", "lens flare"),
    pair("긴 노출", "long exposure motion"),
    pair("틸트시프트", "tilt-shift miniature"),
  ];

  // 비율
  const RATIO = [
    pair("1:1", "1:1 square"),
    pair("16:9", "16:9 widescreen"),
    pair("9:16", "9:16 vertical"),
    pair("4:3", "4:3 standard"),
    pair("3:4", "3:4 portrait"),
    pair("3:2", "3:2 photo"),
    pair("2:3", "2:3 vertical photo"),
    pair("2:1", "2:1 cinematic"),
    pair("5:4", "5:4 medium format"),
    pair("7:5", "7:5 print"),
  ];

  // ─────────────────────────────────────────────────────────
  // 음악 — 장르 (100+)
  const GENRE = [
    pair("팝", "pop"),
    pair("락", "rock"),
    pair("하드락", "hard rock"),
    pair("소프트락", "soft rock"),
    pair("얼터너티브 락", "alternative rock"),
    pair("인디 락", "indie rock"),
    pair("펑크 락", "punk rock"),
    pair("포스트 펑크", "post punk"),
    pair("메탈", "heavy metal"),
    pair("그런지", "grunge"),
    pair("이모", "emo"),
    pair("힙합", "hip hop"),
    pair("붐뱁", "boom bap"),
    pair("트랩", "trap"),
    pair("로파이 힙합", "lofi hip hop"),
    pair("R&B", "R&B"),
    pair("네오 소울", "neo soul"),
    pair("소울", "soul"),
    pair("펑크", "funk"),
    pair("디스코", "disco"),
    pair("재즈", "jazz"),
    pair("스무스 재즈", "smooth jazz"),
    pair("스윙 재즈", "swing jazz"),
    pair("보사노바", "bossa nova"),
    pair("라틴", "latin"),
    pair("살사", "salsa"),
    pair("탱고", "tango"),
    pair("쿠바 음악", "cuban music"),
    pair("플라멩코", "flamenco"),
    pair("레게", "reggae"),
    pair("스카", "ska"),
    pair("덥", "dub"),
    pair("일렉트로닉", "electronic"),
    pair("EDM", "EDM"),
    pair("하우스", "house"),
    pair("딥 하우스", "deep house"),
    pair("테크노", "techno"),
    pair("트랜스", "trance"),
    pair("덥스텝", "dubstep"),
    pair("드럼앤베이스", "drum and bass"),
    pair("앰비언트", "ambient"),
    pair("칠아웃", "chillout"),
    pair("로파이", "lofi"),
    pair("신스웨이브", "synthwave"),
    pair("뉴웨이브", "new wave"),
    pair("시티팝", "city pop"),
    pair("재즈 퓨전", "jazz fusion"),
    pair("클래식", "classical orchestral"),
    pair("실내악", "chamber music"),
    pair("피아노 솔로", "solo piano"),
    pair("바이올린 솔로", "solo violin"),
    pair("첼로 솔로", "solo cello"),
    pair("기타 솔로", "acoustic guitar solo"),
    pair("어쿠스틱", "acoustic"),
    pair("포크", "folk"),
    pair("인디 포크", "indie folk"),
    pair("컨트리", "country"),
    pair("블루스", "blues"),
    pair("가스펠", "gospel"),
    pair("재즈 보컬", "vocal jazz"),
    pair("스탠다드", "jazz standard"),
    pair("샹송", "french chanson"),
    pair("이탈리아 칸초네", "italian canzone"),
    pair("월드뮤직", "world music"),
    pair("켈틱", "celtic"),
    pair("아일랜드 포크", "irish folk"),
    pair("스코틀랜드 민속", "scottish folk"),
    pair("아프리카 드럼", "african drum"),
    pair("인도 라가", "indian raga"),
    pair("중동 음악", "middle eastern music"),
    pair("국악", "korean traditional gugak"),
    pair("판소리", "pansori"),
    pair("사물놀이", "samulnori"),
    pair("일본 전통음악", "japanese traditional music"),
    pair("중국 전통음악", "chinese traditional music"),
    pair("뉴에이지", "new age"),
    pair("필름 스코어", "film score"),
    pair("게임 OST", "video game soundtrack"),
    pair("애니메이션 OST", "anime soundtrack"),
    pair("뮤지컬", "musical theater"),
    pair("디즈니 스타일", "disney musical style"),
    pair("크리스마스 캐롤", "christmas carol"),
    pair("자장가", "lullaby"),
    pair("동요", "children's song"),
    pair("K-팝", "K-pop"),
    pair("K-발라드", "korean ballad"),
    pair("트로트", "trot"),
    pair("J-팝", "J-pop"),
    pair("시티팝 일본", "japanese city pop"),
    pair("애시드 재즈", "acid jazz"),
    pair("프로그레시브 락", "progressive rock"),
    pair("싸이키델릭", "psychedelic"),
    pair("슈게이즈", "shoegaze"),
    pair("드림팝", "dream pop"),
    pair("베드룸 팝", "bedroom pop"),
    pair("힙합 재즈", "jazz hip hop"),
    pair("부기우기", "boogie woogie"),
    pair("랙타임", "ragtime"),
    pair("자이브", "jive"),
    pair("로커빌리", "rockabilly"),
    pair("서프 락", "surf rock"),
    pair("스카 펑크", "ska punk"),
  ];

  // 분위기 (100+)
  const MOOD = [
    pair("행복한", "happy"),
    pair("기쁜", "joyful"),
    pair("들뜬", "excited"),
    pair("신나는", "upbeat energetic"),
    pair("경쾌한", "cheerful"),
    pair("발랄한", "bubbly"),
    pair("귀여운", "cute"),
    pair("사랑스러운", "lovely"),
    pair("로맨틱한", "romantic"),
    pair("달콤한", "sweet"),
    pair("두근거리는", "fluttering"),
    pair("애틋한", "tender"),
    pair("따뜻한", "warm"),
    pair("포근한", "cozy"),
    pair("아늑한", "snug"),
    pair("편안한", "relaxed"),
    pair("느긋한", "laid-back"),
    pair("평화로운", "peaceful"),
    pair("고요한", "serene"),
    pair("차분한", "calm"),
    pair("잔잔한", "gentle and mellow"),
    pair("나른한", "languid"),
    pair("졸린", "drowsy"),
    pair("몽환적인", "dreamy"),
    pair("환상적인", "fantastical"),
    pair("신비로운", "mysterious"),
    pair("마법 같은", "magical"),
    pair("동화 같은", "fairytale-like"),
    pair("향수 어린", "nostalgic"),
    pair("아련한", "wistful"),
    pair("그리운", "longing"),
    pair("쓸쓸한", "lonely"),
    pair("외로운", "lonesome"),
    pair("슬픈", "sad"),
    pair("애잔한", "melancholic"),
    pair("우울한", "blue"),
    pair("처량한", "forlorn"),
    pair("비통한", "sorrowful"),
    pair("절절한", "heart-wrenching"),
    pair("희망찬", "hopeful"),
    pair("벅찬", "uplifting"),
    pair("감동적인", "moving"),
    pair("위로가 되는", "comforting"),
    pair("따스한 위로", "soothing"),
    pair("응원하는", "encouraging"),
    pair("씩씩한", "brave"),
    pair("당당한", "confident"),
    pair("도전적인", "challenging"),
    pair("열정적인", "passionate"),
    pair("뜨거운", "fiery"),
    pair("강렬한", "intense"),
    pair("웅장한", "epic majestic"),
    pair("거대한", "grand"),
    pair("드라마틱한", "dramatic"),
    pair("긴장감 있는", "suspenseful"),
    pair("스릴 있는", "thrilling"),
    pair("어두운", "dark"),
    pair("음산한", "eerie"),
    pair("으스스한", "spooky"),
    pair("기괴한", "uncanny"),
    pair("불안한", "uneasy"),
    pair("초조한", "anxious"),
    pair("화난", "angry"),
    pair("격앙된", "fierce"),
    pair("반항적인", "rebellious"),
    pair("차가운", "cold"),
    pair("쿨한", "cool"),
    pair("도시적인", "urban"),
    pair("세련된", "sophisticated"),
    pair("우아한", "elegant"),
    pair("고상한", "graceful"),
    pair("기품 있는", "dignified"),
    pair("장난기 있는", "playful"),
    pair("천진난만한", "innocent"),
    pair("순수한", "pure"),
    pair("개구쟁이 같은", "mischievous"),
    pair("우스꽝스러운", "goofy"),
    pair("코믹한", "comical"),
    pair("재미있는", "fun"),
    pair("기분 좋은", "feel-good"),
    pair("산뜻한", "refreshing"),
    pair("청량한", "crisp"),
    pair("청순한", "wholesome"),
    pair("순박한", "humble"),
    pair("정겨운", "heartwarming"),
    pair("쓸데없이 진지한", "absurdly serious"),
    pair("진중한", "thoughtful"),
    pair("사색적인", "contemplative"),
    pair("철학적인", "philosophical"),
    pair("명상적인", "meditative"),
    pair("영적인", "spiritual"),
    pair("성스러운", "sacred"),
    pair("경건한", "reverent"),
    pair("축제 같은", "festive"),
    pair("파티 분위기", "party vibe"),
    pair("여름밤 같은", "summer night feel"),
    pair("크리스마스 같은", "christmasy"),
    pair("새해 같은", "new year feel"),
    pair("가을밤 같은", "autumn night feel"),
    pair("봄날 같은", "spring day feel"),
    pair("겨울 아침 같은", "winter morning feel"),
    pair("바다 같은", "ocean-like vast"),
    pair("산 같은", "mountain-like grounded"),
  ];

  // 보컬
  const VOCAL = [
    pair("남성", "male vocalist"),
    pair("여성", "female vocalist"),
    pair("혼성", "mixed gender vocals"),
    pair("듀엣", "duet"),
    pair("그룹 합창", "group choir"),
    pair("가창력 있는", "powerful vocal performance"),
    pair("멜로디 라인 강조", "strong melodic line"),
    pair("저음", "low register baritone"),
    pair("고음", "high register vocals"),
    pair("허스키", "husky voice"),
    pair("부드러운 음색", "soft warm tone"),
    pair("맑은 음색", "clear tone"),
    pair("거친 음색", "raspy tone"),
    pair("속삭임", "whispered vocals"),
    pair("팔세토", "falsetto"),
    pair("스캣", "scat singing"),
    pair("랩", "rap"),
    pair("스포큰 워드", "spoken word"),
    pair("아카펠라", "a cappella"),
    pair("인스트루멘탈", "instrumental no vocals"),
  ];

  // 코러스
  const CHORUS = [
    pair("남성 영어 코러스", "male english background chorus"),
    pair("여성 영어 코러스", "female english background chorus"),
    pair("혼성 영어 코러스", "mixed english background chorus"),
    pair("코러스 없음", "no background chorus"),
  ];

  // 가사 언어
  const LYRIC_LANG = [
    pair("한글 가사", "korean lyrics"),
    pair("영문 가사", "english lyrics"),
    pair("혼합 (한영)", "mixed korean and english lyrics"),
    pair("가사 없음", "no lyrics, instrumental"),
  ];

  // ─────────────────────────────────────────────────────────
  // 탈무드 카테고리 × 스토리 (각 100개 — 시드+조합 생성)
  // 카테고리 ➜ 영문 + 시드 스토리들
  
  const NATURE_SOUNDS = [
    pair('바람소리', 'wind sounds'),
    pair('빗소리', 'rain sounds'),
    pair('계곡물', 'stream water'),
    pair('파도', 'ocean waves'),
    pair('모랫소리', 'sand sounds'),
    pair('새소리', 'birdsong'),
    pair('장작 타는 소리', 'crackling fire'),
    pair('숲 ambience', 'forest ambience'),
    pair('아이들 웃음소리', 'children laughing'),
    pair('고양이 우는 소리', 'cat meowing'),
    pair('개가 짖는 소리', 'dog barking'),
    pair('귀뚜라미 소리', 'crickets chirping'),
    pair('매미소리', 'cicadas buzzing'),
    pair('부엉이 소리', 'owl hooting'),
    pair('까마귀 소리', 'crow cawing'),
    pair('뻐꾹이 소리', 'cuckoo singing'),
    pair('휘파람 소리', 'whistling'),
    pair('여성의 허밍소리', 'female humming'),
    pair('실로폰 소리', 'xylophone'),
    pair('처마에서 바람에 흔들리는 종소리', 'wind chimes in the breeze')
  ];

  const TALMUD_CATEGORIES = {
    "지혜": {
      en: "wisdom",
      seeds: [
        "현명한 자는 듣고 어리석은 자는 말한다",
        "두 손에 떡을 쥐려다 둘 다 떨어뜨린다",
        "보이는 것이 전부가 아니다",
        "묻는 것이 잠시의 부끄러움, 모르는 것이 평생의 부끄러움",
        "지혜는 강요할 수 없고 스스로 깨달아야 한다",
        "현자에게는 모든 사람이 스승이다",
        "지식은 짐이 아니라 깃털처럼 가볍다",
        "어둠 속에서도 길은 반드시 있다",
        "작은 등불 하나가 큰 어둠을 밝힌다",
        "오래 바라보아야 보이는 것이 있다",
        "급히 내린 답은 천천히 후회를 부른다",
        "지혜로운 자는 답보다 질문을 먼저 다듬는다",
        "한 번 보고 판단하지 말고 세 번 돌아보라",
        "아는 길도 물어서 가면 잃지 않는다",
        "현명함은 많이 가진 것이 아니라 잘 쓰는 것이다",
        "남의 실수에서 배우는 자가 가장 영리하다",
        "지혜는 나이가 아니라 성찰에서 자란다",
        "조용한 강이 가장 깊게 흐른다",
        "답을 아는 것보다 때를 아는 것이 지혜다",
        "성급한 혀보다 느린 귀가 더 많이 배운다",
        "지혜는 빌릴 수 없고 길러야 하는 것이다",
        "한 권의 책도 끝까지 읽어야 제 뜻을 준다",
        "어리석음은 같은 돌에 두 번 걸린다",
        "지혜로운 자는 모르는 것을 모른다고 말한다",
        "멀리 보는 눈이 가까운 함정을 피한다",
        "작은 지혜가 큰 재앙을 막는다",
        "지식은 모으는 것, 지혜는 가려내는 것이다",
        "서두른 결정은 늦은 대가를 치른다",
        "현자는 침묵으로도 가르친다",
        "배움에는 끝이 없고 자만에는 바닥이 없다",
        "지혜는 듣는 데서 시작해 행하는 데서 완성된다",
        "거울보다 비판하는 친구가 나를 더 잘 비춘다",
        "모든 답을 안다고 믿는 순간 배움이 멈춘다",
        "지혜로운 자는 칭찬보다 충고를 귀히 여긴다",
        "한 발 물러서면 전체가 보인다",
        "어둠을 탓하기보다 등불을 켜는 자가 현명하다",
        "지혜는 경험을 곱씹어 얻은 열매다",
        "가벼운 말은 무거운 후회로 돌아온다",
        "현명함은 옳음을 아는 것이 아니라 옳게 행하는 것이다",
        "성숙한 이삭일수록 고개를 깊이 숙인다",
        "지혜는 위기 앞에서 그 진짜 모습을 드러낸다",
        "남의 말을 끝까지 듣는 것이 첫 번째 지혜다",
        "조급함은 눈을 가리고 인내는 눈을 밝힌다",
        "지혜로운 자는 적게 말하고 깊게 생각한다",
        "한 번의 깊은 생각이 백 번의 후회를 막는다",
        "길을 잃었을 때 멈추는 것도 지혜다",
        "지혜는 사실을 모으고 진실을 가려낸다",
        "어리석은 자는 답하고 현자는 되묻는다",
        "지혜로운 농부는 날씨를 탓하지 않고 대비한다",
        "작은 의심이 큰 속임수를 막는다",
        "지혜는 책에서 싹트고 삶에서 영근다",
        "현명한 자는 분노를 하루 묵혀 답한다",
        "보지 않고 믿지 말고, 알고서 함부로 말하지 마라",
        "지혜는 자신을 아는 데서 가장 깊어진다",
        "성난 바다에서는 노를 멈추는 것이 지혜다",
        "어리석음은 서두르고 지혜는 기다린다",
        "한 가지를 깊이 아는 자가 열을 얕게 아는 자를 이긴다",
        "지혜로운 자는 다리를 불태우지 않는다",
        "가르치려 들기 전에 먼저 배우려 하라",
        "현명함은 침묵해야 할 때를 아는 것이다",
        "지혜는 빛이 아니라 빛을 찾는 눈이다",
        "큰 결정일수록 하룻밤을 재워라",
        "남을 비추는 등불은 자기 앞도 밝힌다",
        "지혜로운 자는 작은 신호에서 큰 흐름을 읽는다",
        "모든 길을 가본 자보다 옳은 길을 아는 자가 낫다",
        "어리석은 자는 운을 믿고 현자는 준비를 믿는다",
        "지혜는 후회를 교훈으로 바꾸는 기술이다",
        "보석은 깊은 곳에, 지혜는 고요한 마음에 있다",
        "현명한 자는 이긴 자리에서도 배운다",
        "성급한 칼은 자기 손을 먼저 벤다",
        "지혜로운 자는 군중을 따르기 전에 멈춰 본다",
        "한 줄기 빛도 길을 찾기엔 충분하다",
        "지혜는 듣되 휘둘리지 않는 힘이다",
        "묻기를 부끄러워하면 평생 어둠 속에 산다",
        "현명함은 가진 패가 아니라 쓰는 손에 있다",
        "지혜로운 자는 다리를 건너기 전에 깊이를 잰다",
        "조용히 관찰하는 눈이 떠드는 입을 이긴다",
        "지혜는 나무처럼 천천히 그러나 깊게 자란다",
        "어리석은 자는 결과를 보고 현자는 원인을 본다",
        "한 박자 늦춘 대답이 한평생 평화를 지킨다",
        "지혜로운 자는 폭풍 속에서 닻을 내릴 줄 안다",
        "아는 만큼 보이고 보는 만큼 깊어진다",
        "현명함은 옳은 길을 외롭게라도 가는 것이다",
        "지혜는 의심에서 시작해 확신으로 끝난다",
        "성숙한 자는 칭찬에도 비판에도 흔들리지 않는다",
        "어둠이 깊을수록 작은 빛이 멀리 간다",
        "지혜로운 자는 남의 그릇 크기를 함부로 재지 않는다",
        "한 번의 깊은 침묵이 백 마디 말보다 무겁다",
        "지혜는 길을 아는 것이 아니라 길을 찾는 마음이다",
        "현명한 자는 작은 불씨를 미리 끈다",
        "배운 것을 행하지 않으면 모르는 것과 같다",
        "지혜로운 자는 적의 말에서도 배울 것을 찾는다",
        "급류를 거스르지 말고 흐름을 읽어라",
        "지혜는 오늘의 선택이 내일을 만든다는 깨달음이다",
        "어리석은 자는 자랑하고 현자는 점검한다",
        "한 걸음 물러선 자가 두 걸음 멀리 본다",
        "지혜는 빛을 모으는 거울 같은 마음에 깃든다",
        "현명한 자는 끝을 생각하고 첫발을 뗀다",
        "오늘 깨달은 작은 이치가 평생의 등불이 된다",
        "지혜는 멈출 줄 알 때 비로소 완성된다",
      ],
    },
    "우정": {
      en: "friendship",
      seeds: [
        "친구는 나를 비추는 거울이다",
        "함께 웃을 친구보다 함께 울 친구가 더 귀하다",
        "오래된 친구가 새 친구보다 따뜻하다",
        "친구의 결점을 덮어 주는 것이 우정이다",
        "친구를 시험하지 말고 믿어라",
        "한 친구가 천 명의 적보다 강하다",
        "친구의 그림자도 함께 걷는다",
        "비밀을 지키는 친구가 진짜 친구다",
        "친구는 받는 자가 아니라 주는 자다",
        "거리가 멀어도 마음이 가까우면 친구다",
        "넘어진 친구에게 내미는 손이 우정이다",
        "진짜 친구는 등 뒤에서도 같은 말을 한다",
        "기쁨은 친구와 나누면 두 배가 된다",
        "슬픔은 친구와 나누면 절반이 된다",
        "우정은 말이 아니라 함께한 시간으로 자란다",
        "친구의 침묵을 이해하는 것이 깊은 우정이다",
        "비를 함께 맞아 주는 이가 진짜 친구다",
        "친구는 화창한 날보다 폭풍 속에서 드러난다",
        "충고하는 친구가 아첨하는 무리보다 낫다",
        "우정에는 이자도 영수증도 없다",
        "친구의 성공을 진심으로 기뻐할 줄 알아야 한다",
        "오래 묵은 우정은 오래 묵은 포도주 같다",
        "친구를 얻으려면 먼저 친구가 되어 주어라",
        "우정은 한쪽이 끌면 끊어지는 외줄이 아니다",
        "친구의 짐을 함께 지면 길이 가벼워진다",
        "말없이 곁에 있어 주는 것도 큰 우정이다",
        "친구의 비밀은 내 입에서 무덤이 되어야 한다",
        "한 번의 배신이 천 번의 신뢰를 무너뜨린다",
        "진정한 친구는 거울처럼 솔직하다",
        "우정은 거리로 멀어지지 않고 무관심으로 식는다",
        "친구의 잘못을 사람들 앞에서 들추지 마라",
        "함께 늙어 갈 친구가 가장 큰 재산이다",
        "친구는 내가 약할 때 강해지는 사람이다",
        "받기만 하는 우정은 오래가지 못한다",
        "친구의 기쁜 날엔 가장 먼저 달려가라",
        "우정은 작은 안부로 매일 물을 준다",
        "친구를 의심하기 시작하면 우정은 금이 간다",
        "어려울 때 빌려준 손이 평생 기억된다",
        "친구의 단점까지 안아야 진짜 우정이다",
        "우정은 주고받는 거래가 아니라 함께 자라는 나무다",
        "친구의 충고는 쓰지만 약이 된다",
        "곁에 진실한 한 사람이면 외롭지 않다",
        "우정은 같은 곳을 함께 바라보는 것이다",
        "친구의 눈물을 외면하지 않는 것이 도리다",
        "오래 못 봐도 다시 만나면 어제 같은 사이가 친구다",
        "친구를 험담하는 입은 결국 나도 험담한다",
        "우정은 침묵 속에서도 따뜻할 수 있다",
        "친구의 약점을 무기로 삼지 마라",
        "한 친구의 진심이 백 사람의 인사보다 깊다",
        "우정은 베풀고 잊을 때 가장 빛난다",
        "친구가 길을 잃으면 등불을 들고 마중 나가라",
        "진짜 친구는 내 가면 뒤의 나를 안다",
        "함께 먹은 한 끼가 평생의 인연이 된다",
        "우정은 시험하는 것이 아니라 지키는 것이다",
        "친구의 그늘이 되어 줄 때 우정은 깊어진다",
        "멀리 있어도 마음으로 곁에 있는 이가 친구다",
        "우정에 금이 가면 침묵보다 솔직함으로 메워라",
        "친구의 기쁨을 시샘하면 우정이 먼저 떠난다",
        "오랜 친구는 말하지 않아도 마음을 읽는다",
        "곤경에 등을 보이지 않는 자가 친구다",
        "우정은 화려한 말보다 변치 않는 행동이다",
        "친구를 위해 한 번 손해 보는 것이 결국 남는다",
        "함께 견딘 겨울이 우정을 단단하게 한다",
        "친구의 비밀을 지키는 무게를 가볍게 보지 마라",
        "우정은 받은 만큼이 아니라 준 만큼 깊어진다",
        "넘어진 친구를 일으키면 나도 함께 일어선다",
        "진짜 친구는 칭찬보다 진실을 먼저 준다",
        "우정은 작은 오해를 큰 침묵으로 키우지 않는다",
        "친구의 그림자까지 함께 걷는 것이 동행이다",
        "한 사람의 진실한 친구가 인생을 버티게 한다",
        "우정은 약속이 아니라 매일의 안부로 증명된다",
        "친구가 흔들릴 때 흔들리지 않는 것이 사랑이다",
        "오래된 우정에는 침묵도 대화가 된다",
        "친구를 얻는 데는 시간, 잃는 데는 한순간이다",
        "우정은 서로의 부족함을 메워 주는 것이다",
        "친구의 잘못은 둘만 있을 때 조용히 말하라",
        "함께 웃고 함께 울 수 있으면 가족 같은 친구다",
        "우정은 거리보다 무관심에 약하다",
        "친구를 위해 진실을 말하는 것이 진짜 용기다",
        "오래 곁을 지킨 친구가 가장 빛나는 보석이다",
        "우정은 받으려 할 때 작아지고 줄 때 커진다",
        "친구의 어둠을 같이 견뎌 준 시간이 우정이다",
        "진정한 친구는 내 침묵의 이유를 묻지 않고 기다린다",
        "우정은 비 온 뒤에도 함께 걷는 길이다",
        "친구의 성공에 박수 칠 줄 알아야 진짜다",
        "한 친구의 손이 백 명의 박수보다 따뜻하다",
        "우정은 같은 짐을 나눠 질 때 단단해진다",
        "친구를 믿는 것이 의심하는 것보다 덜 외롭다",
        "오랜 우정은 흠을 알고도 곁에 남는 것이다",
        "친구의 등을 떠밀지 말고 곁에서 함께 걸어라",
        "우정은 화내고도 다시 손 내미는 용기다",
        "진짜 친구는 내가 가장 초라할 때 알아본다",
        "함께한 추억이 우정의 가장 큰 자산이다",
        "친구의 비밀은 내가 가진 가장 무거운 보석이다",
        "우정은 멀어질수록 먼저 안부를 묻는 것이다",
        "친구가 길을 잃으면 비추되 끌고 가지는 마라",
        "한 사람을 끝까지 믿어 주는 것이 우정이다",
        "우정은 받은 정을 다음에 갚는 긴 약속이다",
        "오늘 건넨 따뜻한 안부가 평생의 우정을 잇는다",
        "진짜 친구는 멀리 있어도 마음의 거리는 없다",
      ],
    },
    "정직": {
      en: "honesty",
      seeds: [
        "거짓말은 다리가 짧아 멀리 가지 못한다",
        "한 번의 거짓이 백 번의 진실을 가린다",
        "정직한 자는 베개를 높이 베고 잠든다",
        "남을 속이는 자는 결국 자신을 속인다",
        "진실은 무겁고 가볍게 만드는 것은 거짓이다",
        "진심은 시간이 증명한다",
        "약속은 종이가 아니라 마음에 적는 것이다",
        "정직은 가장 든든한 자본이다",
        "거짓으로 쌓은 성은 무너지기 마련이다",
        "진실은 가난해도 부끄럽지 않다",
        "작은 거짓을 덮으려면 더 큰 거짓이 필요하다",
        "정직한 손은 떳떳하게 펴진다",
        "감춘 진실은 언젠가 더 크게 드러난다",
        "한 번 무너진 신뢰는 다시 쌓기 어렵다",
        "정직은 손해처럼 보여도 가장 빠른 길이다",
        "거짓의 미소보다 진실의 침묵이 낫다",
        "약속을 가볍게 하면 사람이 가벼워진다",
        "정직한 자는 어둠 속에서도 같은 사람이다",
        "거짓말은 기억해야 하지만 진실은 그럴 필요가 없다",
        "양심은 아무도 안 볼 때 더 크게 말한다",
        "정직은 가장 값싸고 가장 강한 갑옷이다",
        "남의 것을 탐한 손은 결국 빈손이 된다",
        "진실을 말하는 입은 떨려도 떳떳하다",
        "거짓으로 얻은 것은 거짓으로 잃는다",
        "정직한 상인은 저울을 속이지 않는다",
        "한 마디 진실이 백 마디 변명을 이긴다",
        "감춘 잘못은 곪고 드러낸 잘못은 아문다",
        "정직은 평판이 아니라 혼자 있을 때의 모습이다",
        "거짓말의 성은 작은 진실 한 줄에 무너진다",
        "진실은 늦더라도 반드시 길을 찾는다",
        "약속을 지키는 사람의 말은 무게가 있다",
        "정직한 자는 잃을 비밀이 없어 자유롭다",
        "남을 속여 이긴 것은 진 것과 같다",
        "진실은 칼처럼 아파도 결국 낫게 한다",
        "정직은 작은 일에서 먼저 시험받는다",
        "거짓의 단맛은 짧고 그 쓴맛은 길다",
        "정직한 자는 같은 말을 누구 앞에서나 한다",
        "속인 만큼 자기 마음의 빚이 쌓인다",
        "진실을 말할 용기가 가장 큰 정직이다",
        "거짓으로 쌓은 명예는 모래성이다",
        "정직은 신뢰라는 가장 비싼 이자를 낳는다",
        "한 번의 정직이 평생의 평판을 지킨다",
        "거짓은 빨리 달리지만 진실이 끝내 따라잡는다",
        "양심에 진 빚은 어떤 돈으로도 못 갚는다",
        "정직한 자의 가난은 부끄럽지 않다",
        "거짓말은 입에서 가볍고 마음에서 무겁다",
        "정직은 어제와 오늘의 말이 같은 것이다",
        "속임수로 채운 곳간은 마음을 비운다",
        "진실을 두려워하는 자는 이미 진 자다",
        "정직한 길은 멀어 보여도 가장 곧다",
        "한 번 솔직하면 백 번의 거짓을 안 해도 된다",
        "거짓은 친구를 잃고 정직은 적도 존경하게 한다",
        "남이 안 봐도 옳게 행하는 것이 정직이다",
        "진실은 숨길수록 무겁고 밝힐수록 가볍다",
        "정직한 자는 거울 앞에서 떳떳하다",
        "속인 이익은 빌린 것일 뿐 내 것이 아니다",
        "약속을 어기는 것은 자기 이름을 깎는 일이다",
        "정직은 가장 조용하지만 가장 멀리 가는 힘이다",
        "거짓의 그림자는 햇빛 아래서 더 길어진다",
        "진실을 말한 밤이 가장 깊은 잠을 준다",
        "정직한 자는 변명 대신 사실을 말한다",
        "한 톨의 거짓이 한 가마의 신뢰를 망친다",
        "남을 속인 자는 자기 그림자를 두려워한다",
        "정직은 받는 것이 아니라 매일 지키는 것이다",
        "진실은 가난해도 고개를 들 수 있다",
        "거짓으로 산 평화는 더 큰 폭풍을 부른다",
        "정직한 자의 말은 도장이 필요 없다",
        "감추기보다 인정하는 것이 더 빠른 길이다",
        "진실은 칼날 같아도 손에 쥐면 방패가 된다",
        "정직은 손해의 얼굴을 한 가장 큰 이익이다",
        "거짓말 한 번에 사람의 무게가 가벼워진다",
        "양심이 깨끗하면 어떤 소문도 무섭지 않다",
        "정직한 자는 어둠을 두려워하지 않는다",
        "속여서 얻은 박수는 곧 야유로 변한다",
        "진실은 더디 와도 끝내 자리를 찾는다",
        "정직은 가장 단순하고 가장 강한 전략이다",
        "한 번 깨진 약속은 두 번 믿기 어렵다",
        "거짓의 무게는 시간이 갈수록 무거워진다",
        "정직한 손은 빈손이어도 부끄럽지 않다",
        "남을 속이려다 자기 눈을 먼저 가린다",
        "진실을 지키는 것이 가장 큰 용기다",
        "정직은 신용이라는 보이지 않는 재산을 쌓는다",
        "거짓으로 막은 둑은 더 크게 터진다",
        "솔직한 사과 한마디가 백 번의 변명을 이긴다",
        "정직한 자는 누가 보든 안 보든 같다",
        "거짓의 단맛에 길들면 진실이 쓰게 느껴진다",
        "진실은 무겁지만 들고 가면 가벼워진다",
        "정직은 작은 약속을 지키는 데서 자란다",
        "속임수는 한 번 이기고 영원히 진다",
        "양심의 소리를 끄면 더 큰 대가가 온다",
        "정직한 자의 가난은 부자의 거짓보다 떳떳하다",
        "한 줄의 진실이 거짓의 책 한 권을 덮는다",
        "거짓말은 자기가 판 함정에 자기가 빠진다",
        "정직은 늦어도 결국 빛을 본다",
        "진실을 두려워 말고 외면을 두려워하라",
        "정직한 자는 흙 묻은 손을 감추지 않는다",
        "속여서 큰 사람은 작아지고 솔직해서 작은 사람은 커진다",
        "진실은 가장 오래 남는 유일한 기록이다",
        "정직은 평생을 지키는 가장 든든한 방패다",
        "오늘의 솔직한 한마디가 평생의 신뢰를 만든다",
      ],
    },
    "인내": {
      en: "patience",
      seeds: [
        "기다리는 자에게 길이 열린다",
        "끝까지 참는 자가 이긴다",
        "조급함은 후회의 어머니다",
        "한 번 더 참으면 다른 길이 보인다",
        "씨앗은 흙 속에서 시간을 견딘다",
        "강물은 서두르지 않고도 멀리 간다",
        "참는 것은 약함이 아니라 큰 힘이다",
        "오늘의 인내가 내일의 기쁨이 된다",
        "분노가 입을 떠나기 전 셋을 세라",
        "기다림에도 연습이 필요하다",
        "급한 걸음은 돌부리에 먼저 걸린다",
        "느린 발걸음도 멈추지 않으면 정상에 닿는다",
        "참는 입이 평생의 화를 막는다",
        "겨울을 견딘 나무가 가장 단단하다",
        "조급한 손은 익지 않은 열매를 딴다",
        "인내는 쓴 뿌리에서 단 열매를 맺는다",
        "기다림은 게으름이 아니라 익히는 시간이다",
        "한 방울씩 떨어진 물이 바위를 뚫는다",
        "참을 인 자 셋이면 살인도 면한다",
        "분노의 순간에 멈추는 자가 가장 강하다",
        "급류를 거스르지 말고 때를 기다려라",
        "오래 끓인 국이 더 깊은 맛을 낸다",
        "인내는 폭풍이 지나가기를 아는 지혜다",
        "서두른 결실은 빨리 시든다",
        "기다릴 줄 아는 농부가 풍년을 거둔다",
        "참는 동안에도 뿌리는 자라고 있다",
        "조급함은 눈을 가리고 인내는 길을 연다",
        "한 박자 늦춘 대답이 평화를 지킨다",
        "인내는 멈춤이 아니라 견디며 나아가는 것이다",
        "성난 말은 하루 묵혔다 꺼내라",
        "기다림 끝에 핀 꽃이 가장 향기롭다",
        "참는 자의 침묵이 떠드는 자를 이긴다",
        "씨를 뿌린 날 거두려 하지 마라",
        "인내는 시간을 적이 아니라 친구로 만든다",
        "급한 불일수록 침착하게 꺼야 한다",
        "오늘 못 이룬 것을 내일이 마저 이룬다",
        "참고 견딘 어둠 끝에 새벽이 온다",
        "조급한 마음은 작은 돌에도 넘어진다",
        "인내는 분노를 지혜로 식히는 시간이다",
        "느려도 꾸준한 걸음이 결국 멀리 간다",
        "참을 줄 아는 자에게 기회가 찾아온다",
        "조급한 손은 익은 열매를 떨어뜨린다",
        "기다림은 빈 시간이 아니라 영그는 시간이다",
        "한 번 더 참으면 후회 하나가 사라진다",
        "강은 돌을 만나도 화내지 않고 돌아간다",
        "인내는 가장 조용한 승리의 기술이다",
        "조급함이 망친 일을 인내가 되살린다",
        "참는 것은 지는 것이 아니라 때를 기다리는 것이다",
        "묵묵히 견딘 시간이 가장 단단한 토대가 된다",
        "성낼 시간에 숨을 한 번 더 쉬어라",
        "기다림을 견디면 서두름이 놓친 것을 얻는다",
        "참는 자의 하루가 급한 자의 한 달을 이긴다",
        "겨울이 길수록 봄꽃은 더 진하다",
        "인내는 폭풍 속에서 닻을 내리는 힘이다",
        "조급한 씨앗은 싹을 보지 못한다",
        "한 걸음씩 견디면 가장 높은 곳에 닿는다",
        "참는 마음에는 후회가 깃들지 않는다",
        "성급함은 백 번의 노력을 한 번에 무너뜨린다",
        "인내는 결과를 기다릴 줄 아는 믿음이다",
        "느린 강물이 가장 깊은 골을 만든다",
        "참고 기다린 자만이 익은 열매를 안다",
        "조급함을 누르면 더 큰 길이 열린다",
        "기다림은 약속을 향한 가장 긴 발걸음이다",
        "분을 삭인 하룻밤이 평생의 적을 면하게 한다",
        "인내는 멈춰 선 듯해도 가장 멀리 가는 길이다",
        "급하게 오른 자는 급하게 굴러떨어진다",
        "참아 낸 고통이 가장 깊은 스승이 된다",
        "흙 속의 긴 기다림이 거목을 키운다",
        "조급한 자는 운을 탓하고 참는 자는 때를 만든다",
        "기다림은 포기가 아니라 더 단단해지는 과정이다",
        "한 번의 인내가 백 번의 다툼을 막는다",
        "느려도 옳은 길이 빠른 지름길을 이긴다",
        "참는 자의 침묵 속에서 답이 익는다",
        "성급한 결정은 늦은 대가를 부른다",
        "인내는 어둠을 견뎌 빛을 보는 눈이다",
        "조급함은 다 된 죽에 코를 빠뜨린다",
        "기다린 만큼 깊어지고 견딘 만큼 강해진다",
        "참아 낸 자리에서 가장 큰 꽃이 핀다",
        "급류 앞에서는 멈추는 것이 가장 빠른 길이다",
        "인내는 시간을 견디며 자신을 빚는 일이다",
        "한 번 더 견디면 무너질 벽도 문이 된다",
        "조급한 손은 매듭을 더 단단히 엉키게 한다",
        "기다림 끝의 한 걸음이 모든 인내를 보상한다",
        "참는 것은 분노에게 지지 않는 힘이다",
        "느린 발도 멈추지 않으면 결국 도착한다",
        "성급함은 익은 곡식을 비에 잃게 한다",
        "인내는 폭풍 뒤의 맑은 하늘을 믿는 것이다",
        "조급한 마음을 다스리면 세상이 넓어진다",
        "기다림은 가장 조용한 노력이다",
        "한 호흡 참은 자리에 평화가 머문다",
        "참고 견딘 겨울이 가장 깊은 뿌리를 만든다",
        "급한 길은 돌아가고 참는 길은 곧게 간다",
        "인내는 작은 견딤이 모여 큰 결실이 되는 길이다",
        "조급함이 닫은 문을 인내가 다시 연다",
        "기다림을 견디는 자만이 새벽을 본다",
        "참는 자의 하루가 후회 없는 평생을 만든다",
        "성낼수록 작아지고 참을수록 커진다",
        "인내는 시간을 내 편으로 만드는 지혜다",
        "조급함은 길을 잃고 인내는 길을 낸다",
        "오늘 견딘 한 시간이 내일의 단단한 하루가 된다",
      ],
    },
    "감사": {
      en: "gratitude",
      seeds: [
        "가진 것을 헤아리는 자가 부자다",
        "감사는 작게 시작해 크게 자란다",
        "받은 것을 잊지 않는 것이 예의다",
        "감사할 일이 없을 때 감사하라",
        "한 잔의 물도 감사하면 귀해진다",
        "오늘 하루도 받은 선물이다",
        "가족이 곁에 있는 것이 큰 복이다",
        "건강한 발걸음 자체가 감사다",
        "감사는 행복을 부르는 주문이다",
        "잃은 뒤에 알면 이미 늦다",
        "작은 것에 감사하면 큰 것이 따라온다",
        "감사하는 마음은 어둠 속에서도 빛을 찾는다",
        "받은 친절을 기억하는 것이 사람의 도리다",
        "감사는 가진 것을 두 배로 키운다",
        "불평이 머문 자리엔 감사가 깃들지 못한다",
        "감사할 줄 아는 자는 결코 가난하지 않다",
        "오늘 마신 공기 한 모금도 거저 받은 것이다",
        "감사는 비교를 멈추는 데서 시작된다",
        "받기만 하고 잊으면 마음이 메마른다",
        "감사하는 눈에는 평범한 하루도 기적이 된다",
        "한 끼의 밥상에도 수많은 손길이 담겨 있다",
        "감사는 행복을 만드는 가장 싼 재료다",
        "가진 것을 세는 자가 없는 것을 세는 자보다 부자다",
        "감사를 말로 전하면 두 사람이 따뜻해진다",
        "잃기 전에 감사하면 후회가 줄어든다",
        "감사는 받은 사랑을 갚으려는 마음이다",
        "비 온 뒤의 햇살도 당연한 것이 아니다",
        "감사할 거리는 찾는 자에게만 보인다",
        "오늘 누군가의 수고로 내 하루가 굴러간다",
        "감사는 마음의 곳간을 가득 채운다",
        "작은 친절에 고마움을 표하는 것이 큰 사람이다",
        "감사를 모르면 더 가져도 늘 부족하다",
        "건강한 두 다리로 걷는 것 자체가 복이다",
        "감사는 어제의 은혜를 오늘 기억하는 일이다",
        "받은 빵을 기억하는 자가 다음 빵을 나눈다",
        "감사하는 마음이 불행의 한가운데서도 웃게 한다",
        "잊지 않는 것이 가장 값진 보답이다",
        "감사는 가진 것을 다시 보게 하는 안경이다",
        "한 사람의 호의를 가볍게 흘리지 마라",
        "감사할 일을 적어 두면 행복이 보인다",
        "오늘 곁에 있는 사람이 가장 큰 선물이다",
        "감사는 부족함이 아니라 충분함을 보는 눈이다",
        "받은 은혜를 흘려보내면 나눔이 된다",
        "감사하는 자의 하루는 결코 헛되지 않다",
        "당연하게 여긴 것들이 사실은 다 선물이다",
        "감사는 마음이 가난해지지 않게 하는 약이다",
        "고마움을 미루지 말고 오늘 전하라",
        "감사할 줄 아는 마음에 불평이 머물지 못한다",
        "잃어 본 자가 가진 것의 무게를 안다",
        "감사는 평범함 속에서 기적을 발견하는 힘이다",
        "한 줌의 곡식에도 하늘과 땀이 담겨 있다",
        "감사하는 자는 작은 빛에도 미소 짓는다",
        "받은 친절은 다음 사람에게 흘려보내라",
        "감사는 행복으로 가는 가장 가까운 길이다",
        "오늘 숨 쉬는 것도 거저 얻은 은혜다",
        "감사할 줄 모르면 더 줘도 손이 비어 있다",
        "고마운 마음을 표현하는 것이 가장 큰 예의다",
        "감사는 어둠 속에서 켜는 마음의 등불이다",
        "가진 것에 만족하는 자가 진짜 부자다",
        "감사는 잃기 전에 알아보는 지혜다",
        "한 사람의 수고를 알아주는 것이 감사다",
        "감사하는 자의 그릇은 늘 넘친다",
        "받은 사랑을 세는 자가 가장 행복하다",
        "감사는 비교를 멈추고 누리는 마음이다",
        "오늘 누린 작은 평안도 누군가의 덕이다",
        "감사할 일이 없는 것이 아니라 못 본 것이다",
        "고마움을 표현하지 않으면 마음에서 식는다",
        "감사는 불행 속에서도 남은 빛을 세는 일이다",
        "받은 은혜를 기억하는 것이 사람됨의 시작이다",
        "감사하는 눈에는 세상이 따뜻하게 보인다",
        "당연한 하루는 없고 모든 날이 선물이다",
        "감사는 가진 것을 빛나게 닦는 천이다",
        "한 끼의 식사에 감사하면 그것이 잔치가 된다",
        "감사할 줄 아는 자는 마음이 늘 넉넉하다",
        "잃고 나서 후회하기 전에 지금 고마워하라",
        "감사는 작은 행복을 큰 행복으로 키운다",
        "받은 도움을 기억하는 자가 다음에 손 내민다",
        "감사하는 마음은 가장 든든한 부적이다",
        "오늘 누군가가 나를 위해 일하고 있다",
        "감사는 마음을 부유하게 하는 보이지 않는 재산이다",
        "고마움을 표한 자리엔 따뜻함이 남는다",
        "감사할 줄 모르는 부자는 가난한 부자다",
        "받은 것을 당연히 여기면 복이 멀어진다",
        "감사는 평범한 오늘을 특별하게 만든다",
        "한 사람의 친절이 하루를 살게 한다",
        "감사하는 마음이 행복을 끌어당긴다",
        "잃어 본 뒤에야 알면 너무 늦은 깨달음이다",
        "감사는 부족을 메우는 가장 빠른 길이다",
        "오늘 가진 것을 세면 부족함이 작아진다",
        "고마움은 표현할 때 비로소 완성된다",
        "감사는 어제의 은혜에 오늘 답하는 일이다",
        "받은 사랑을 흘려보내면 세상이 따뜻해진다",
        "감사하는 자는 작은 것에서 큰 기쁨을 얻는다",
        "당연하게 누린 것들이 가장 큰 선물이었다",
        "감사는 마음의 눈을 밝게 닦는다",
        "한 모금의 물에도 감사하면 메마르지 않는다",
        "감사할 줄 아는 자가 결국 가장 행복하다",
        "잃기 전에 알아보는 것이 가장 큰 지혜다",
        "감사는 행복을 부르는 가장 조용한 노래다",
        "오늘 누린 감사가 내일의 기쁨을 부른다",
      ],
    },
    "용기": {
      en: "courage",
      seeds: [
        "두려움을 느끼면서도 나아가는 것이 용기다",
        "넘어진 자리에서 일어서는 것이 진짜 힘이다",
        "작은 한 걸음이 큰 변화를 만든다",
        "혼자라도 옳은 길을 가는 것이 용기다",
        "모르는 것을 모른다고 말하는 것도 용기다",
        "도움을 청하는 것도 용기다",
        "포기하지 않는 것이 가장 큰 용기다",
        "어둠 속에서 빛을 찾아 나서는 자가 용감하다",
        "용기는 큰 소리가 아니라 작은 행동이다",
        "다시 시작할 용기가 가장 어렵다",
        "두려움이 없는 게 아니라 두려움을 이기는 게 용기다",
        "첫걸음을 떼는 순간 두려움은 절반이 된다",
        "옳다고 믿으면 박수 없어도 나아가라",
        "용기는 떨리는 손으로도 문을 여는 것이다",
        "주저앉은 자리가 다시 일어설 출발점이다",
        "용감한 자는 실패를 끝이 아니라 과정으로 본다",
        "침묵해야 안전할 때 진실을 말하는 것이 용기다",
        "용기는 큰 무대가 아니라 작은 결심에서 자란다",
        "넘어지는 것이 아니라 안 일어서는 것이 패배다",
        "두려운 일을 미루지 않는 것이 진짜 담력이다",
        "용기는 모두가 등 돌릴 때 한 발 더 가는 것이다",
        "한 번의 용기가 평생의 후회를 막는다",
        "겁이 나도 옳은 쪽에 서는 것이 용기다",
        "용감한 자는 변명 대신 시도를 택한다",
        "어둠을 탓하기보다 등불을 켜는 자가 용감하다",
        "용기는 큰 결심이 아니라 오늘의 작은 실행이다",
        "두려움에 이름을 붙이면 그것은 작아진다",
        "용감한 자는 실수를 인정할 줄 안다",
        "한 사람이 옳게 서면 군중도 결국 돌아본다",
        "용기는 안전한 길을 떠나 옳은 길로 가는 것이다",
        "넘어진 횟수보다 일어선 횟수가 그 사람을 말한다",
        "두려움을 마주 본 자만이 그것을 넘어선다",
        "용기는 떨면서도 한 걸음 더 내딛는 것이다",
        "포기하고 싶은 순간이 가장 가까운 결승점이다",
        "용감한 자는 남의 시선보다 양심을 따른다",
        "작은 용기가 모이면 세상을 바꾼다",
        "도움을 청하는 것은 약함이 아니라 용기다",
        "용기는 결과를 모른 채로 옳음을 택하는 것이다",
        "두려움 앞에서 멈추면 두려움이 주인이 된다",
        "용감한 자는 흔들려도 방향을 잃지 않는다",
        "한 번 더 일어서면 그것이 곧 승리다",
        "용기는 큰 외침이 아니라 묵묵한 한 걸음이다",
        "겁쟁이는 천 번 죽고 용감한 자는 한 번 산다",
        "용기는 두려움 속에서 옳음을 붙드는 손이다",
        "넘어진 김에 쉬어도 다시 일어서면 진 게 아니다",
        "두려운 진실을 말하는 입이 가장 용감하다",
        "용기는 모르는 길도 첫발을 떼게 한다",
        "주저하는 백 번보다 떨리는 한 번의 시도가 낫다",
        "용감한 자는 실패를 스승으로 삼는다",
        "혼자 옳은 길에 서는 외로움을 견디는 것이 용기다",
        "용기는 다시 시작할 줄 아는 마음이다",
        "두려움은 마주 볼수록 작아지고 피할수록 커진다",
        "용감한 자는 안 될 이유보다 될 방법을 찾는다",
        "한 걸음의 용기가 닫힌 문을 연다",
        "용기는 박수받지 못해도 옳음을 지키는 것이다",
        "넘어졌을 때 손을 짚는 그 자리가 다음 발판이다",
        "두려움에 지지 않은 하루가 사람을 키운다",
        "용감한 자는 약함을 숨기지 않고 마주한다",
        "용기는 큰 영웅이 아니라 작은 결심에서 시작된다",
        "포기를 이긴 자만이 끝을 본다",
        "용기는 떨리는 목소리로도 진실을 말하는 것이다",
        "안전한 침묵보다 떨리는 진실이 더 값지다",
        "용감한 자는 길이 없으면 길을 만든다",
        "한 번의 두려움을 넘으면 다음은 쉬워진다",
        "용기는 결과가 아니라 시도하는 마음에 있다",
        "넘어진 자리를 부끄러워 말고 발판으로 삼아라",
        "두려움을 인정하는 것이 용기의 시작이다",
        "용감한 자는 군중이 아니라 양심을 따른다",
        "작은 용기 하나가 큰 두려움을 무너뜨린다",
        "용기는 옳은 일을 미루지 않는 것이다",
        "포기하지 않는 마음이 가장 강한 무기다",
        "용기는 떨면서도 멈추지 않는 발걸음이다",
        "두려움 너머에 내가 원하던 길이 있다",
        "용감한 자는 실패해도 다시 도전한다",
        "한 사람의 용기가 침묵하던 이들을 일으킨다",
        "용기는 안전을 버리고 옳음을 택하는 결단이다",
        "넘어진 횟수는 일어설 기회의 수다",
        "두려운 일에 먼저 손드는 것이 진짜 담력이다",
        "용감한 자는 변명할 시간에 한 걸음 내딛는다",
        "용기는 큰 소리가 아니라 흔들림 없는 실행이다",
        "포기 직전이 가장 빛에 가까운 순간이다",
        "용기는 떨리는 가슴으로도 옳음을 붙드는 힘이다",
        "안 해서 남는 후회가 해서 남는 실패보다 무겁다",
        "용감한 자는 두려움을 길잡이로 삼는다",
        "한 번 더 일어서는 자를 아무도 못 이긴다",
        "용기는 모두가 침묵할 때 손을 드는 것이다",
        "넘어진 자리에서 배우면 그것은 패배가 아니다",
        "두려움을 향해 한 발 가면 그것이 줄어든다",
        "용감한 자는 약점을 인정하고도 나아간다",
        "용기는 작은 결심을 행동으로 옮기는 것이다",
        "포기하지 않는 한 길은 아직 끝나지 않았다",
        "용기는 떨면서도 옳은 쪽으로 도는 키다",
        "두려움은 멈춘 자에게만 주인 노릇을 한다",
        "용감한 자는 실패의 흙을 털고 다시 선다",
        "한 사람의 작은 용기가 큰 변화를 점화한다",
        "용기는 안전한 어둠보다 위험한 빛을 택한다",
        "넘어진 만큼 단단해지고 일어선 만큼 강해진다",
        "두려움을 이긴 오늘이 내일의 나를 만든다",
        "용기는 다시 시작할 수 있다는 믿음이다",
        "오늘 낸 작은 용기가 내일의 큰 길을 연다",
      ],
    },
    "겸손": {
      en: "humility",
      seeds: [
        "벼는 익을수록 고개를 숙인다",
        "내가 다 알지 못한다는 사실을 아는 것이 겸손이다",
        "남보다 한 발 뒤에 서는 자가 멀리 본다",
        "큰 그릇은 자기를 비운다",
        "자랑은 입에서 나오는 순간 가벼워진다",
        "겸손은 약함이 아니라 강함의 표시다",
        "낮은 자리에서 더 많이 보인다",
        "스승은 늘 자기를 학생이라 부른다",
        "박수받을 때 한 걸음 물러서라",
        "겸손한 자는 잃을 것이 없다",
        "익은 이삭일수록 깊이 머리를 숙인다",
        "비운 그릇만이 새것을 담을 수 있다",
        "자기를 낮추는 자가 결국 높아진다",
        "겸손은 남을 올려다볼 줄 아는 눈이다",
        "큰 산일수록 산자락을 넓게 내준다",
        "아는 척하는 입은 배움의 문을 닫는다",
        "겸손한 자는 모든 사람을 스승으로 본다",
        "자랑이 앞서면 존경이 뒤로 물러난다",
        "낮은 물이 모든 물을 받아 바다가 된다",
        "겸손은 자기를 잊고 일을 앞세우는 것이다",
        "고개를 숙일 줄 아는 자가 더 멀리 본다",
        "스스로 크다 하면 남이 작게 본다",
        "겸손은 칭찬 앞에서 한 발 물러서는 일이다",
        "빈 수레가 요란하고 익은 곡식은 조용하다",
        "자기를 비운 자리에 신뢰가 채워진다",
        "겸손한 자는 비판을 선물로 받는다",
        "낮은 자리를 택한 자가 결국 존경받는다",
        "교만은 추락의 문 앞에서 웃는다",
        "겸손은 더 배울 것이 있음을 아는 마음이다",
        "고개 든 벼는 쭉정이일 때가 많다",
        "자랑을 줄이면 신뢰가 늘어난다",
        "겸손한 자는 자기 그림자를 크게 그리지 않는다",
        "낮춤은 비굴이 아니라 단단한 자존이다",
        "큰 나무는 바람 앞에서도 뿌리를 자랑하지 않는다",
        "겸손은 옳음을 알아도 조용히 행하는 것이다",
        "스스로 낮춘 자는 떨어질 곳이 없다",
        "박수 소리에 취하면 발밑을 잃는다",
        "겸손한 자의 침묵이 자랑보다 깊다",
        "비울수록 담기고 낮출수록 높아진다",
        "교만한 자는 배우지 못해 늘 같은 자리다",
        "겸손은 남의 그릇을 함부로 재지 않는 것이다",
        "고개를 숙여야 문지방을 넘는다",
        "자기를 작게 여길수록 마음은 넓어진다",
        "겸손한 자는 공을 나누고 허물을 끌어안는다",
        "낮은 곳으로 흐르는 물이 가장 멀리 간다",
        "교만은 귀를 막고 겸손은 귀를 연다",
        "겸손은 모를 수도 있다는 가능성을 품는 것이다",
        "이긴 자리에서도 고개 숙이는 자가 진짜 강자다",
        "자랑한 만큼 무게가 가벼워진다",
        "겸손한 마음에는 시기가 깃들지 못한다",
        "낮춤을 아는 자가 가장 높이 선다",
        "큰 강은 소리 없이 깊게 흐른다",
        "겸손은 배움 앞에 무릎 꿇는 용기다",
        "스스로 스승이라 하면 제자가 떠난다",
        "박수 뒤에서 한 걸음 물러서면 길이 보인다",
        "겸손한 자는 자기 이름을 앞세우지 않는다",
        "교만의 탑은 높을수록 빨리 무너진다",
        "겸손은 남을 비추고 자기는 그늘에 서는 것이다",
        "익을수록 무거워지고 무거울수록 낮아진다",
        "자기를 낮춘 자리에 존경이 쌓인다",
        "겸손한 자는 칭찬을 빌린 것으로 안다",
        "낮은 문일수록 고개를 더 깊이 숙인다",
        "교만은 자기 눈을 가리는 가장 두꺼운 천이다",
        "겸손은 옳고도 다투지 않는 지혜다",
        "스스로 비운 자만이 더 채울 수 있다",
        "박수를 좇으면 길을 잃고 일을 좇으면 길이 열린다",
        "겸손한 자의 말은 짧고 행동은 깊다",
        "교만한 자는 정상에서 발을 헛디딘다",
        "겸손은 모두에게 배울 점이 있다고 믿는 것이다",
        "고개 숙인 자가 더 넓은 하늘을 본다",
        "자랑을 삼키면 신뢰가 자란다",
        "겸손한 자는 자기를 증명하려 애쓰지 않는다",
        "낮춤은 떨어지는 것이 아니라 단단해지는 것이다",
        "큰 사람일수록 자기를 작게 말한다",
        "겸손은 비판을 거울로 삼는 마음이다",
        "교만은 친구를 잃고 겸손은 스승을 얻는다",
        "겸손한 자는 공로를 나누고 잘못을 먼저 든다",
        "낮은 자리에서 보면 더 많은 것이 보인다",
        "스스로 높이는 자는 결국 혼자 남는다",
        "박수가 클수록 한 걸음 더 물러서라",
        "겸손한 마음은 비어 있어 무엇이든 담는다",
        "교만의 끝은 늘 추락의 시작이다",
        "겸손은 옳음을 알아도 조용히 내려놓는 것이다",
        "익은 벼처럼 무거운 자는 고개를 든다고 안 한다",
        "자기를 비운 그릇이 가장 쓸모 있다",
        "겸손한 자는 자기 자랑을 남에게 맡긴다",
        "낮춤을 아는 자가 가장 멀리 간다",
        "큰 그릇은 자기 크기를 떠벌리지 않는다",
        "겸손은 배움의 문을 늘 열어 두는 것이다",
        "교만한 귀에는 어떤 충고도 들리지 않는다",
        "겸손한 자는 정상에서도 첫걸음을 기억한다",
        "고개를 숙여야 더 깊은 우물을 들여다본다",
        "자랑을 줄인 만큼 사람이 다가온다",
        "겸손한 자는 빛을 받으면 남에게 비춘다",
        "낮은 곳에서 가장 단단한 뿌리가 자란다",
        "교만은 가졌다 믿고 겸손은 더 배우려 한다",
        "겸손은 자기를 잊고 옳음을 앞세우는 것이다",
        "스스로 작아질수록 그릇은 더 커진다",
        "오늘 한 번 고개 숙인 자가 내일 우러름을 받는다",
        "겸손은 비울수록 더 깊어지는 그릇이다",
      ],
    },
    "가족": {
      en: "family",
      seeds: [
        "가족은 마지막까지 남는 등불이다",
        "한 끼를 함께하는 것이 사랑이다",
        "부모의 마음은 멀어진 거리만큼 깊어진다",
        "형제는 같은 뿌리에서 난 두 가지다",
        "집이 클 필요는 없고 마음이 크면 된다",
        "함께 늙어 가는 것이 행복이다",
        "가족의 침묵에도 사랑이 담겨 있다",
        "잠든 모습을 지켜보는 것이 사랑이다",
        "다 큰 자식도 부모에겐 어린아이다",
        "집은 사람이 아니라 사랑이 만든다",
        "가족은 비바람을 함께 견디는 한 지붕이다",
        "밥상에 둘러앉은 시간이 가장 따뜻한 재산이다",
        "부모의 등은 말없이 길을 가르친다",
        "형제의 다툼도 한 뿌리 위의 일이다",
        "가족은 받은 사랑을 다음 세대로 잇는다",
        "집은 돌아갈 곳이 있다는 안심이다",
        "부모는 자식의 빈 그릇을 먼저 채운다",
        "가족의 손이 닿으면 상처도 빨리 아문다",
        "한 식탁의 온기가 하루의 피로를 녹인다",
        "가족은 가장 약할 때 곁에 남는 사람이다",
        "부모의 잔소리에는 못다 한 사랑이 섞여 있다",
        "형제는 멀어져도 같은 추억을 나눈 사이다",
        "가족은 자랑이 아니라 곁을 지키는 일이다",
        "잠든 아이의 숨소리가 부모의 평화다",
        "집의 불빛이 켜져 있으면 길이 멀지 않다",
        "가족의 사랑은 표현하지 않아도 흐른다",
        "부모의 굽은 등이 자식의 곧은 길이 된다",
        "함께 먹은 밥이 가족을 한 핏줄로 잇는다",
        "가족은 실수를 끌어안아 주는 품이다",
        "오래 곁에 있어 소중함을 잊기 쉬운 것이 가족이다",
        "부모의 기다림은 자식의 발걸음보다 길다",
        "형제의 우애가 부모의 가장 큰 효도다",
        "가족은 비를 함께 맞아 주는 우산이다",
        "집은 자식이 떠나도 불을 끄지 않는 곳이다",
        "부모는 자기 몫을 줄여 자식 몫을 늘린다",
        "가족의 한마디가 천 명의 위로보다 깊다",
        "함께 늙어 가는 손을 잡는 것이 사랑이다",
        "가족은 가면을 벗고도 편한 유일한 사이다",
        "부모의 침묵은 걱정을 삼킨 사랑이다",
        "한 가족의 화목이 가장 든든한 울타리다",
        "가족은 받기 전에 먼저 주는 관계다",
        "집으로 가는 길은 아무리 멀어도 가깝다",
        "부모의 사랑은 거리로 식지 않는다",
        "형제는 어려울 때 가장 먼저 떠오르는 이름이다",
        "가족의 식탁에는 빈자리가 가장 크게 보인다",
        "잠든 부모의 주름이 자식을 키운 세월이다",
        "집은 성공을 묻지 않고 안부를 묻는 곳이다",
        "가족은 자랑할 일에도 함께 울 일에도 곁에 있다",
        "부모는 자식의 뒷모습을 오래 바라본다",
        "한 끼라도 같이 먹는 마음이 가족을 잇는다",
        "가족의 사랑은 조건을 달지 않는다",
        "집의 온기는 크기가 아니라 마음에서 온다",
        "부모의 손은 거칠어도 가장 따뜻하다",
        "형제는 같은 부모를 추억하는 동행자다",
        "가족은 무너진 날 등을 받쳐 주는 벽이다",
        "떠난 자리에 남은 빈 그릇이 사랑을 말한다",
        "부모의 기도는 자식이 모르는 새 길을 닦는다",
        "가족은 작은 안부로 매일 사랑을 잇는다",
        "집은 잘잘못을 따지기 전에 안아 주는 곳이다",
        "함께한 밥상이 평생의 그리움이 된다",
        "가족은 자식의 침묵도 이해하는 사이다",
        "부모는 늙어서도 자식 걱정을 내려놓지 못한다",
        "형제의 손을 놓지 않는 것이 부모의 소원이다",
        "가족은 떠나 봐야 그 무게를 안다",
        "집의 불빛 하나가 지친 발걸음을 부른다",
        "부모의 사랑은 갚을 수 없어 흘려보내는 것이다",
        "가족의 포옹은 세상 어떤 약보다 깊다",
        "한 식탁의 웃음이 하루를 다시 살게 한다",
        "가족은 가장 초라한 날에도 곁을 지킨다",
        "부모의 발소리만으로 아이는 안심한다",
        "형제는 멀리 있어도 한 뿌리를 기억한다",
        "가족은 자랑이 아니라 함께 견딘 시간이다",
        "잠든 식구를 바라보는 눈빛이 곧 사랑이다",
        "집은 떠난 자식의 자리를 늘 비워 둔다",
        "부모의 그늘은 사라진 뒤에야 크게 보인다",
        "가족은 받은 사랑을 다음 사람에게 흘린다",
        "한마디 안부가 멀어진 가족을 다시 잇는다",
        "가족의 사랑은 표 나지 않게 곁을 지키는 것이다",
        "집은 성적표가 아니라 사람을 반긴다",
        "부모의 손길이 닿은 자리는 오래 따뜻하다",
        "형제의 화목이 부모를 가장 기쁘게 한다",
        "가족은 흔들릴 때 붙잡아 주는 손이다",
        "떠난 뒤 비로소 보이는 사랑이 부모의 사랑이다",
        "부모는 자식의 짐을 몰래 나눠 진다",
        "가족의 한 끼가 평생의 인연을 새긴다",
        "집은 실패한 날 가장 먼저 떠오르는 곳이다",
        "가족의 침묵 속에도 깊은 대화가 흐른다",
        "부모의 기다림은 자식이 잠든 뒤에도 깨어 있다",
        "형제는 부모가 남긴 가장 큰 선물이다",
        "가족은 자식이 커도 어린아이로 본다",
        "잠든 아이 곁의 부모가 가장 평온하다",
        "집의 온기는 함께 있는 사람이 만든다",
        "부모의 사랑은 셈하지 않고 흘러간다",
        "가족은 약점을 알고도 끝까지 곁에 남는다",
        "한 식탁의 따뜻함이 세상의 추위를 막는다",
        "가족은 떠나 봐야 그 자리가 보인다",
        "부모의 등을 기억하는 자가 길을 잃지 않는다",
        "가족의 사랑은 받은 자리에서 다시 자란다",
        "오늘 함께한 한 끼가 평생의 그리움이 된다",
        "가족은 멀어져도 한 뿌리를 잊지 않는다",
      ],
    },
    "노력": {
      en: "diligence",
      seeds: [
        "작은 물방울이 바위를 뚫는다",
        "재능보다 꾸준함이 멀리 간다",
        "노력은 결코 배신하지 않는다",
        "어제의 나를 이기는 자가 강한 자다",
        "씨를 뿌리지 않고는 거둘 수 없다",
        "한 걸음씩 디뎌야 정상에 닿는다",
        "성실은 가장 큰 재능이다",
        "내가 흘린 땀은 결국 내 것이 된다",
        "지름길보다 옳은 길이 더 빠르다",
        "오늘의 한 시간이 미래의 하루가 된다",
        "쉬지 않는 발걸음이 먼 길을 줄인다",
        "재능은 시작이고 노력은 완성이다",
        "땀은 거짓말을 하지 않는다",
        "느려도 멈추지 않으면 결국 도착한다",
        "오늘의 작은 노력이 내일의 큰 차이를 만든다",
        "꾸준함은 천재를 이기는 유일한 힘이다",
        "씨앗은 묵묵히 뿌린 자에게만 싹을 준다",
        "한 방울의 땀이 한 알의 결실로 돌아온다",
        "노력 없는 바람은 빈손으로 끝난다",
        "어제보다 한 걸음만 더 가면 그것이 성장이다",
        "재능을 믿는 자는 노력하는 자를 못 이긴다",
        "오늘 흘린 땀이 내일의 길을 닦는다",
        "쉬운 길은 빨리 끝나고 옳은 길은 멀리 간다",
        "노력은 눈에 안 보여도 뿌리에서 자란다",
        "한 번의 도약보다 매일의 한 걸음이 강하다",
        "성실한 손은 빈손으로 돌아가지 않는다",
        "포기하지 않는 끈기가 재능을 앞선다",
        "노력은 운이 들어올 문을 만든다",
        "오늘 게으른 한 시간이 내일의 후회가 된다",
        "땀 흘린 만큼 길은 단단해진다",
        "작은 정성이 쌓여 큰 결실이 된다",
        "노력하는 자에게는 실패도 스승이 된다",
        "꾸준함 앞에서는 큰 벽도 길이 된다",
        "씨를 뿌린 자만이 수확의 기쁨을 안다",
        "한 걸음의 노력이 천 리의 시작이다",
        "재능은 빌릴 수 있어도 노력은 못 빌린다",
        "오늘의 땀이 미래의 빵이 된다",
        "쉬어도 좋지만 멈추지는 마라",
        "노력은 가장 정직한 투자다",
        "어제와 같은 오늘은 제자리걸음이다",
        "꾸준한 물줄기가 골짜기를 깊게 판다",
        "성실은 시간이 증명하는 재능이다",
        "노력 없는 꿈은 잠에서 끝난다",
        "한 발 한 발이 모여 산을 넘는다",
        "땀의 무게만큼 결실이 무거워진다",
        "노력하는 자는 운을 기다리지 않고 만든다",
        "오늘 미룬 한 걸음은 내일 두 걸음이 된다",
        "지치는 것은 괜찮지만 멈추는 것은 다르다",
        "노력은 재능이라는 씨앗을 키우는 물이다",
        "꾸준함은 가장 더디지만 가장 확실한 길이다",
        "씨앗의 침묵이 거목의 시작이다",
        "한 시간의 집중이 하루의 흩어짐을 이긴다",
        "노력은 결과보다 먼저 사람을 단단하게 한다",
        "어제의 땀이 오늘의 디딤돌이 된다",
        "성실한 발걸음에는 헛걸음이 없다",
        "노력은 작은 차이를 큰 격차로 바꾼다",
        "포기하는 순간이 결승점에서 가장 가깝다",
        "꾸준히 두드린 자에게 문이 열린다",
        "땀으로 적신 길은 미끄러지지 않는다",
        "노력은 운이 깃들 자리를 마련하는 일이다",
        "오늘의 한 줄이 내일의 한 권이 된다",
        "재능이 잠든 사이 노력이 앞서 간다",
        "한 걸음의 꾸준함이 천 번의 결심을 이긴다",
        "노력은 보이지 않게 미래를 짓는다",
        "어제의 나를 넘어서는 것이 진짜 성공이다",
        "성실은 가장 오래 남는 능력이다",
        "노력 없는 재능은 녹슨 칼과 같다",
        "묵묵히 쌓은 하루가 가장 높은 탑이 된다",
        "씨를 뿌린 손만이 가을을 누린다",
        "한 시간의 노력이 미래의 하루를 산다",
        "노력하는 자는 핑계 대신 방법을 찾는다",
        "꾸준함은 천천히 그러나 깊게 자란다",
        "땀은 결국 자기 자리로 돌아온다",
        "노력은 운명을 바꾸는 가장 느린 마법이다",
        "오늘 쉬운 길은 내일 더 가파른 길이 된다",
        "성실한 하루가 모여 단단한 평생이 된다",
        "노력은 결과를 기다릴 줄 아는 믿음이다",
        "한 걸음씩이라도 멈추지 않으면 도착한다",
        "재능을 자랑하기보다 노력을 쌓아라",
        "꾸준한 자에게는 늦은 출발도 늦지 않다",
        "땀 흘린 자리에서 단단한 길이 자란다",
        "노력은 어제와 다른 오늘을 만드는 손이다",
        "포기 직전의 한 걸음이 모든 노력을 보상한다",
        "성실은 운보다 오래가는 재산이다",
        "노력하는 자는 흙 속에서도 길을 찾는다",
        "한 시간을 아낀 자가 미래의 하루를 번다",
        "재능은 출발선, 노력은 결승선을 정한다",
        "꾸준함은 작은 물방울로 바위를 가른다",
        "땀의 정직함이 결국 사람을 키운다",
        "노력은 보상이 늦어도 반드시 돌아온다",
        "오늘의 게으름은 내일의 빚으로 남는다",
        "성실한 손이 가장 단단한 미래를 짓는다",
        "노력은 운명에 던지는 가장 강한 한 수다",
        "한 걸음의 꾸준함이 천 리 길을 끝낸다",
        "재능보다 멈추지 않는 마음이 멀리 간다",
        "땀 흘린 만큼 길이 환해진다",
        "노력은 미래의 나에게 보내는 선물이다",
        "꾸준히 견딘 시간이 가장 값진 토대가 된다",
        "오늘 흘린 한 방울 땀이 내일의 결실을 부른다",
        "노력은 멈추지 않는 한 결코 헛되지 않는다",
      ],
    },
    "절제": {
      en: "self-control",
      seeds: [
        "혀를 다스리는 자가 자신을 다스린다",
        "성냄은 자기를 먼저 태우는 불이다",
        "한 입 덜 먹는 것이 보약이다",
        "욕심은 채울수록 더 멀어 보인다",
        "쉬는 것도 하나의 능력이다",
        "필요와 욕심을 구별할 줄 알아야 한다",
        "충분함을 아는 자가 진짜 부자다",
        "감정의 주인이 되어야 자유롭다",
        "참는 입이 인생을 살린다",
        "절제는 자유로 가는 길이다",
        "성난 말은 하루를 묵혀 꺼내라",
        "한 잔을 멈추는 것이 백 잔을 이긴다",
        "욕망을 다스리는 자가 가장 강한 자다",
        "절제는 덜어 내는 데서 채워진다",
        "분노가 입을 떠나기 전에 셋을 세라",
        "넘치기 전에 멈추는 것이 지혜다",
        "혀끝의 한마디가 평생을 가른다",
        "절제는 자기 안의 불을 끄는 물이다",
        "더 가지려는 손이 가진 것을 놓친다",
        "감정에 끌려가면 후회가 기다린다",
        "절제하는 자는 욕심의 노예가 아니다",
        "한 발 물러서는 자제가 큰 화를 막는다",
        "배부름을 멈출 줄 아는 것이 건강이다",
        "성냄을 참은 자리에 평화가 머문다",
        "절제는 오늘의 만족을 내일로 미루는 힘이다",
        "욕심의 그릇은 아무리 채워도 비어 있다",
        "혀를 멈추면 다툼의 절반이 사라진다",
        "절제는 작은 유혹을 이기는 데서 자란다",
        "분노는 칼을 쥐기 전에 내려놓아야 한다",
        "멈출 줄 아는 자가 끝까지 간다",
        "필요한 만큼만 가지는 것이 풍요다",
        "감정의 파도에 휩쓸리면 길을 잃는다",
        "절제는 자기를 이기는 가장 조용한 승리다",
        "한 입의 자제가 평생의 건강을 지킨다",
        "성난 마음으로 내린 결정은 늦게 후회된다",
        "욕심을 줄이면 마음이 넓어진다",
        "절제는 가진 것을 즐길 줄 아는 여유다",
        "참은 분노는 사라지고 터진 분노는 흉터를 남긴다",
        "혀를 다스리지 못하면 마음도 못 다스린다",
        "절제는 멈춰야 할 때를 아는 지혜다",
        "더 채우려다 있는 것마저 쏟는다",
        "감정의 주인이 된 자가 진정 자유롭다",
        "절제는 욕망을 누르는 것이 아니라 길들이는 것이다",
        "한 박자 멈춘 말이 평생의 적을 면하게 한다",
        "충분함을 모르면 더 가져도 가난하다",
        "성냄의 불은 부채질할수록 자기를 태운다",
        "절제하는 자는 유혹 앞에서 눈을 감을 줄 안다",
        "넘치는 욕심보다 비운 마음이 더 크다",
        "혀의 절제가 인간관계의 절반을 지킨다",
        "절제는 자유를 가두는 것이 아니라 지키는 것이다",
        "분노를 참은 하룻밤이 평생을 구한다",
        "멈출 줄 아는 손이 가진 것을 오래 누린다",
        "욕심은 가까울수록 더 멀어 보인다",
        "감정을 다스린 자가 상황도 다스린다",
        "절제는 작은 욕망을 미루는 큰 힘이다",
        "한 입 덜 먹은 자리에 건강이 깃든다",
        "성난 말은 주워 담을 수 없으니 삼켜라",
        "욕망의 끝을 좇으면 평생 목이 마르다",
        "절제는 자기 안의 폭풍을 잠재우는 닻이다",
        "참는 입이 천 번의 다툼을 막는다",
        "필요를 알면 욕심이 작아진다",
        "감정에 진 자는 두 번 패배한다",
        "절제는 오늘을 다스려 내일을 지키는 일이다",
        "넘치기 직전에 멈추는 자가 현명하다",
        "혀를 누른 침묵이 분노의 말보다 강하다",
        "절제는 자기를 이긴 자만 누리는 평화다",
        "더 가지려는 마음이 만족을 밀어낸다",
        "성냄을 식히면 길이 다시 보인다",
        "절제하는 자는 욕심에 끌려다니지 않는다",
        "한 잔의 자제가 무너질 하루를 세운다",
        "충분히 가졌음을 아는 것이 가장 큰 부유함이다",
        "감정의 불씨를 키우지 않는 것이 지혜다",
        "절제는 멈춤을 통해 더 멀리 가는 길이다",
        "참은 분노는 흩어지고 쏟은 분노는 남는다",
        "혀끝을 다스리는 자가 운명을 다스린다",
        "절제는 작은 유혹 앞에서 먼저 시험받는다",
        "욕망을 비우면 마음의 곳간이 넓어진다",
        "성난 결정은 늘 늦은 청구서를 보낸다",
        "멈출 때를 아는 것이 끝까지 가는 비결이다",
        "필요와 욕심 사이에 절제가 서 있다",
        "감정을 누를 줄 아는 자가 진짜 강자다",
        "절제는 오늘의 유혹을 이긴 작은 승리들이다",
        "한 입의 멈춤이 평생의 무게를 줄인다",
        "성냄의 말은 하루 묵히면 절반이 사라진다",
        "욕심의 강은 채워도 마르지 않는다",
        "절제는 자기 안의 불을 다스리는 손이다",
        "참는 입술이 깨질 인연을 붙든다",
        "충분함을 아는 마음에 평화가 산다",
        "감정의 노예가 되면 자유를 잃는다",
        "절제는 멈출 줄 아는 용기에서 나온다",
        "넘치는 욕심보다 비운 마음이 더 멀리 본다",
        "혀를 다스린 하루가 후회 없는 잠을 준다",
        "절제는 욕망을 끄는 것이 아니라 길들이는 일이다",
        "분노를 참은 자리마다 평화가 자란다",
        "멈춤을 아는 자가 가장 오래 누린다",
        "욕심을 덜어 낸 만큼 마음이 가벼워진다",
        "감정의 주인이 되는 것이 진짜 자유다",
        "절제는 자기를 다스려 세상을 얻는 길이다",
        "오늘 누른 작은 욕심이 내일의 자유를 만든다",
        "절제는 멈출 줄 아는 마음에서 완성된다",
      ],
    },
    "베풂": {
      en: "generosity",
      seeds: [
        "주는 손이 받는 손보다 행복하다",
        "작은 친절은 큰 파도가 된다",
        "베풂은 손해가 아니라 투자다",
        "이름 없이 베푼 자가 가장 큰 사람이다",
        "남을 비추면 나도 밝아진다",
        "나누면 가벼워지고 움켜쥐면 무거워진다",
        "가난해도 베풀 마음은 부자다",
        "한 끼의 나눔이 평생의 인연이 된다",
        "베풂은 마음의 운동이다",
        "주는 자가 결국 더 받는다",
        "빈손으로도 따뜻한 말은 줄 수 있다",
        "작은 빵 한 조각이 누군가의 하루를 살린다",
        "베풂에는 영수증이 필요 없다",
        "받을 것을 세지 않는 손이 진짜 베푸는 손이다",
        "그늘을 만드는 나무는 제 열매를 먹지 않는다",
        "도움은 받은 사람보다 준 사람을 더 오래 따뜻하게 한다",
        "손을 펴야 더 많이 담을 수 있다",
        "베풂은 씨앗이고 시간은 그것을 나무로 키운다",
        "가진 것이 적어도 마음은 넉넉할 수 있다",
        "누군가의 짐을 들어 주면 내 어깨도 가벼워진다",
        "나눈 기쁨은 두 배가 되고 나눈 슬픔은 절반이 된다",
        "베풂은 돌려받기 위한 거래가 아니다",
        "보이지 않는 곳에서 베푼 친절이 가장 빛난다",
        "한 사람의 작은 도움이 다른 이의 큰 용기가 된다",
        "베풀 줄 아는 사람은 외롭지 않다",
        "줄 것이 없다면 미소라도 건네라",
        "친절은 이자 없이 돌아오는 빚이다",
        "베풂은 부의 크기가 아니라 마음의 크기다",
        "빈 그릇을 채워 주는 손이 가장 아름답다",
        "베풂은 받은 은혜를 다음 사람에게 흘려보내는 일이다",
        "작은 등불 하나가 어두운 길을 여러 사람에게 밝힌다",
        "줄 때 망설이면 그 마음은 이미 절반이 식는다",
        "베풂의 크기보다 베푸는 마음의 온도가 중요하다",
        "누군가에게 길을 알려 주는 것도 베풂이다",
        "베풂은 가진 자의 의무가 아니라 모두의 기쁨이다",
        "한 번의 나눔이 누군가의 평생 기억이 된다",
        "베풀고 잊는 사람이 가장 크게 베푸는 사람이다",
        "도움을 청한 손을 잡아 주는 것이 사람의 도리다",
        "베풂은 강물처럼 흘러야 썩지 않는다",
        "가장 가난한 날에 베푼 한 끼가 가장 귀하다",
        "베풂은 남을 위한 것 같지만 결국 나를 키운다",
        "따뜻한 말 한마디도 누군가에겐 큰 선물이다",
        "베풀 때는 오른손이 한 일을 왼손이 모르게 하라",
        "나눔은 나누는 사람을 먼저 부자로 만든다",
        "베풂에 조건을 달면 그것은 거래일 뿐이다",
        "어려운 이웃을 외면하지 않는 것이 진짜 부유함이다",
        "베풂은 작게 시작해도 크게 번진다",
        "누군가의 눈물을 닦아 주는 손이 가장 깨끗하다",
        "베풂은 받을 사람을 가리지 않는다",
        "줄수록 마음의 곳간이 커진다",
        "베풂은 오늘 심어 내일 거두는 농사다",
        "가진 것을 움켜쥐면 더 가난해진다",
        "베풂은 세상을 조금 더 살 만하게 만든다",
        "작은 선의가 모이면 큰 강이 된다",
        "베풀 줄 아는 아이가 마음 넉넉한 어른이 된다",
        "도움은 미루지 않을 때 가장 값지다",
        "베풂은 자랑하는 순간 빛을 잃는다",
        "빈 주머니로도 마음은 나눌 수 있다",
        "베풂은 받는 이의 자존심을 다치지 않게 하는 기술이다",
        "누군가를 도운 날의 잠은 더 깊고 평안하다",
        "나눔에는 끝이 없고 베풂에는 후회가 없다",
        "베풂은 마음의 문을 여는 열쇠다",
        "작은 친절이 큰 적의도 녹인다",
        "베풀면 잃는 것 같지만 사실은 쌓이는 것이다",
        "한 그루의 나무가 수많은 새를 쉬게 한다",
        "베풂은 가르치지 않아도 전염된다",
        "도움을 받은 기억은 사람을 더 따뜻하게 만든다",
        "베풂은 부자의 특권이 아니라 사람의 본성이다",
        "줄 수 있을 때 주는 것이 가장 큰 행운이다",
        "베풂은 보답을 기다리지 않을 때 완성된다",
        "마음을 나누면 적도 친구가 된다",
        "베풂은 손해처럼 보이지만 가장 확실한 이득이다",
        "누군가의 빈자리를 채워 주는 것이 베풂이다",
        "작은 도움이라도 늦지 않게 건네라",
        "베풂은 받은 사랑을 세상에 되돌리는 길이다",
        "가진 것을 자랑하지 말고 나눈 것을 기억하라",
        "베풂은 메마른 땅에 내리는 비와 같다",
        "누군가를 일으켜 세우면 나도 함께 일어선다",
        "베풂은 입으로 하는 것이 아니라 손으로 하는 것이다",
        "작은 나눔이 큰 신뢰를 만든다",
        "베풂은 마음이 가난해지지 않게 하는 약이다",
        "줄 것을 아끼면 받을 마음도 줄어든다",
        "베풂은 오늘의 나를 내일의 누군가에게 보내는 일이다",
        "한 사람의 따뜻함이 마을 전체를 데운다",
        "베풂은 헤아리지 않을수록 커진다",
        "도움을 준 손은 시간이 지나도 부끄럽지 않다",
        "베풂은 가장 조용한 영웅의 행동이다",
        "나눌수록 마음의 그릇은 깊어진다",
        "베풂은 받는 자를 빚쟁이로 만들지 않는다",
        "작은 정성이 큰 감동을 만든다",
        "베풂은 세상에 빚을 갚는 가장 아름다운 방법이다",
        "누군가의 추위를 덜어 주면 내 봄이 빨리 온다",
        "베풂은 후하게, 자랑은 인색하게 하라",
        "가진 것보다 나눈 것이 그 사람을 말해 준다",
        "베풂은 끝났다고 생각할 때 다시 시작된다",
        "한 손을 내밀면 두 사람이 함께 걷는다",
        "베풂은 마음의 근육이라 쓸수록 단단해진다",
        "도움은 작아도 진심이면 무겁다",
        "베풂은 받을 자격을 묻지 않는다",
        "오늘 베푼 친절이 내일의 누군가를 살린다",
      ],
    },
    "성찰": {
      en: "self-reflection",
      seeds: [
        "남을 탓하기 전에 자신을 먼저 돌아보라",
        "거울은 흙 묻은 얼굴을 가리지 않는다",
        "고요할 때 비로소 자신이 보인다",
        "하루의 끝에 자신을 한 줄로 적어 두어라",
        "잘못은 인정할수록 작아진다",
        "후회는 배움의 어머니다",
        "남의 허물은 작게, 내 허물은 크게 보라",
        "내일을 위해 오늘의 나를 돌아보라",
        "성찰은 가장 조용한 성장이다",
        "자신을 아는 사람이 세상을 안다",
        "거울 앞에서 솔직한 사람이 가장 용감하다",
        "멈춰 서야 자신이 어디 있는지 보인다",
        "변명은 성장을 가로막는 가장 부드러운 벽이다",
        "자기를 속이는 자는 가장 가까운 적을 가진 셈이다",
        "반성 없는 하루는 흘러간 모래와 같다",
        "잘못을 덮으면 자라고 마주하면 사라진다",
        "자신을 비추는 거울은 마음 안에 있다",
        "남을 가리키는 손가락 셋은 나를 향한다",
        "침묵 속에서 양심의 목소리가 들린다",
        "어제의 나를 평가할 줄 알아야 내일이 달라진다",
        "성찰은 자신과 나누는 가장 정직한 대화다",
        "깨진 그릇도 들여다봐야 다시 빚을 수 있다",
        "잘못을 웃어넘기는 사람은 같은 실수를 반복한다",
        "마음의 먼지는 자주 닦아야 쌓이지 않는다",
        "성찰은 채찍이 아니라 등불이다",
        "나를 향한 질문이 가장 어렵고 가장 값지다",
        "후회를 곱씹지 말고 교훈으로 빚어라",
        "자신을 미워하지 말되 자신에게 무르지도 마라",
        "거울은 정직하지만 그 앞에 설 용기는 내 몫이다",
        "하루를 돌아보지 않으면 같은 하루를 또 산다",
        "성찰은 과거를 후회하는 것이 아니라 다듬는 것이다",
        "내 마음을 모르면 누구의 마음도 알 수 없다",
        "잘못 앞에서 멈추는 사람이 멀리 간다",
        "자신을 들여다보는 눈이 가장 밝은 눈이다",
        "반성은 무릎 꿇는 것이 아니라 다시 서는 것이다",
        "남의 평가보다 자신의 점검이 먼저다",
        "흔들릴수록 내면을 들여다보라",
        "성찰은 마음의 거울을 닦는 일이다",
        "자기 그림자를 외면하면 빛도 보이지 않는다",
        "오늘의 실수를 적어 두면 내일의 스승이 된다",
        "자신에게 솔직한 사람만이 진짜로 자유롭다",
        "성찰 없는 경험은 나이만 먹게 한다",
        "깊은 우물일수록 조용히 자신을 비춘다",
        "마음을 들여다보는 시간이 가장 생산적인 휴식이다",
        "잘못을 변명하면 두 번 잘못하는 것이다",
        "점검하는 사람은 같은 함정에 두 번 빠지지 않는다",
        "성찰은 어제의 나에게 배우는 일이다",
        "거울을 깨지 말고 얼굴을 닦아라",
        "내 안의 소리를 들으려면 바깥의 소음을 줄여야 한다",
        "반성은 짧게, 다짐은 분명하게 하라",
        "자신을 속인 거짓말이 가장 오래 남는다",
        "하루의 끝에서 묻는 한마디가 사람을 키운다",
        "성찰은 패배의 기록이 아니라 성장의 지도다",
        "마음의 방을 자주 청소해야 어둠이 머물지 않는다",
        "자기 잘못을 먼저 보는 눈이 가장 어른스럽다",
        "후회가 깊을수록 다짐은 단단해야 한다",
        "성찰은 멈춤이 아니라 더 멀리 가기 위한 숨고르기다",
        "자신을 똑바로 본 사람만이 남을 너그럽게 본다",
        "마음의 거울에 김이 서리면 잠시 멈춰 닦아라",
        "어제와 같은 나라면 오늘은 헛산 것이다",
        "성찰은 자신을 벌하는 것이 아니라 이해하는 것이다",
        "잘못을 마주한 밤이 가장 깊은 배움의 밤이다",
        "내 안을 모르고 멀리 가면 길을 잃는다",
        "반성하는 사람의 발걸음은 흔들려도 앞을 향한다",
        "자기 점검은 가장 값싸고 가장 확실한 스승이다",
        "마음을 비추는 빛은 조용한 시간에 켜진다",
        "성찰은 어제의 나와 화해하는 일이다",
        "흠을 숨기면 곪고 드러내면 아문다",
        "자신에게 던지는 정직한 질문이 인생을 바꾼다",
        "거울은 답을 주지 않지만 진실은 보여 준다",
        "성찰 없는 성공은 다음 실패의 씨앗이다",
        "돌아본 사람은 같은 돌부리에 다시 걸리지 않는다",
        "마음의 흙탕물은 가만히 두어야 맑아진다",
        "반성은 과거를 향하지만 그 빛은 미래를 비춘다",
        "자신을 아는 깊이만큼 사람을 품을 수 있다",
        "오늘 나를 점검하지 않으면 내일이 나를 시험한다",
        "성찰은 가장 작은 방에서 일어나는 가장 큰 변화다",
        "잘못을 부끄러워하되 자신을 미워하지는 마라",
        "내면을 들여다본 사람의 말은 가볍지 않다",
        "거울 앞 1분이 헛된 하루를 구한다",
        "성찰은 자랑할 일이 아니라 조용히 할 일이다",
        "마음의 주인이 되려면 먼저 자기를 살펴야 한다",
        "흔들린 날일수록 자신에게 더 정직하라",
        "반성은 어제를 지우는 것이 아니라 다듬는 것이다",
        "자신을 비춘 빛이 결국 남도 비춘다",
        "마음의 장부는 매일 정산해야 빚이 쌓이지 않는다",
        "성찰은 멈춰 선 자리에서 길을 다시 찾는 일이다",
        "자기 허물을 아는 것이 지혜의 첫걸음이다",
        "후회만 하면 제자리, 돌아보면 한 걸음 앞이다",
        "내 안의 어둠을 인정해야 빛을 들일 수 있다",
        "성찰은 조용하지만 가장 멀리 가는 발걸음이다",
        "자신을 속이지 않는 하루가 가장 든든한 하루다",
        "거울을 자주 보는 사람이 길을 잃지 않는다",
        "반성은 어제의 나를 오늘의 스승으로 삼는 일이다",
        "마음을 들여다본 만큼 세상이 넓게 보인다",
        "성찰은 끝이 아니라 더 나은 시작의 문이다",
        "점검을 게을리한 마음에는 먼지가 쌓인다",
        "잘못 앞 솔직한 한마디가 백 마디 변명을 이긴다",
        "자신을 돌아본 밤이 다음 날을 다르게 만든다",
        "오늘의 성찰이 내일의 나를 빚는다",
      ],
    },
  };

  // 카테고리당 100개로 패딩 (시드 + 변형)
  const STORY_VARIANTS = [
    "에 관한 이야기",
    "의 다른 얼굴",
    "이 작은 마을에서 일어난 일",
    "을 깨달은 어느 날",
    "을 잊고 살았던 시간",
    "이 가르쳐준 교훈",
    "을 다시 배우다",
    "을 시험받는 순간",
    "이 빛나는 순간",
    "을 둘러싼 작은 소동",
  ];

  for (const cat of Object.keys(TALMUD_CATEGORIES)) {
    const seeds = TALMUD_CATEGORIES[cat].seeds;
    const out = [];
    let i = 0;
    while (out.length < 100) {
      const base = seeds[i % seeds.length];
      const variantIdx = Math.floor(i / seeds.length);
      if (variantIdx === 0) {
        out.push(base);
      } else {
        const suffix = STORY_VARIANTS[(variantIdx - 1) % STORY_VARIANTS.length];
        out.push(`${base}${suffix}`);
      }
      i++;
    }
    TALMUD_CATEGORIES[cat].stories = out;
  }

  return {
    CHARACTER_PRESETS,
    ANIMAL_KEYS,
    TIME_OF_DAY,
    WEATHER,
    SCENE,
    CAMERA,
    LIGHTING,
    STYLE,
    TECHNIQUE,
    RATIO,
    GENRE,
    MOOD,
    VOCAL,
    CHORUS,
    LYRIC_LANG,
    NATURE_SOUNDS,
    TALMUD_CATEGORIES,
  };
})();
